-- Generated by dbmigration.
-- View dbo.v_ActiveCustomers -> livebit_dbo.v_activecustomers
-- Original T-SQL: source/views/livebit_dbo__v_activecustomers.sql

CREATE OR REPLACE VIEW "livebit_dbo"."v_activecustomers" AS
SELECT c.id, c.name, d.fulldate AS signupdate
FROM "livebit_dbo".customers c
LEFT JOIN "livebit_divadim".dimdate d ON d.datekey = c.signupdatekey
WHERE COALESCE(c.name, '') <> '';
