-- Generated by dbmigration. Data for dbo.DMS_ConfigIDBusinessPartnerPercetage -> livebit_dbo.dms_configidbusinesspartnerpercetage.
INSERT INTO "livebit_dbo"."dms_configidbusinesspartnerpercetage" ("configid", "totalbp", "matchedbp", "percetagematchedbp", "notmatchedbp", "percetagenotmatchedbp") VALUES
(1, 30, 30, 100.0, 0, 0.0),
(2, 30, 28, 93.33, 2, 6.67),
(3, 30, 20, 66.67, 10, 33.33),
(4, 30, 30, 100.0, 0, 0.0),
(5, 30, 20, 66.67, 10, 33.33),
(6, 30, 20, 66.67, 10, 33.33),
(7, 30, 30, 100.0, 0, 0.0),
(8, 30, 30, 100.0, 0, 0.0),
(9, 30, 20, 66.67, 10, 33.33),
(10, 30, 30, 100.0, 0, 0.0),
(11, 30, 30, 100.0, 0, 0.0),
(12, 30, 30, 100.0, 0, 0.0);
