-- Generated by dbmigration. Data for dbo.chat_context_config -> livebit_dbo.chat_context_config.
INSERT INTO "livebit_dbo"."chat_context_config" ("id", "table_name", "enable_for_chat", "category", "description") VALUES
(1, 'divadim.DimPlanet', TRUE, 'planet_data', 'Planet dimension data'),
(2, 'dbo.DMS_FactAttributeStats', TRUE, 'stats', 'Attribute-level statistics'),
(3, 'dbo.DMS_FactFunctionaStatsBRIMArchive', FALSE, 'archive_stats', 'Archived BRIM functional stats'),
(4, 'dbo.DMS_FactFunctionaStatsBRIM', TRUE, 'functional_stats', 'Active BRIM functional stats'),
(5, 'dbo.IndustryType', TRUE, 'industry_lookup', 'Industry type reference table');
