-- Generated by dbmigration. Data for dbo.DMS_CustDynamicConfig -> livebit_dbo.dms_custdynamicconfig.
INSERT INTO "livebit_dbo"."dms_custdynamicconfig" ("configid", "generalcolumnname", "sapsourcetablename", "sapsourcecolumnname", "sapstagetablename", "sapstagcolumnname", "sappostupdate", "sapispart", "sqlsourcetablename", "sqlsourcecolumnname", "sqlstagetablename", "sqlstagcolumnname", "sqlpostupdate", "sqlispart", "sharepointsourcetablename", "sharepointsourcecolumnname", "sharepointstagetablename", "sharepointstagcolumnname", "sharepointpostupdate", "sharepointispart", "ftpsourcetablename", "ftpsourcecolumnname", "ftpstagetablename", "ftpstagcolumnname", "ftpispart", "executionsequence", "isdatetype", "isnumerictype", "isfloattype", "ispk", "overallstatus", "statusdesc", "isready", "hashcolumnname", "isl1only", "isl2only", "sapstagetablenamepk", "sqlstagetablenamepk", "ftpstagetablenamepk", "sharepointstagetablenamepk", "criteriacolumn", "criteriavalue", "issharepointrequired", "groupid", "subgroupid", "syncdatatype", "fields", "dqrule", "sapsourcequery", "sqlsourcequery", "sharepointsourcequery", "ftpsourcequery", "configcategory", "businsspriority", "distinctsqlsapstagcolumnname", "distinctsqlsqlstagcolumnname", "distinctsqlsharepointstagcolumnname", "distinctsqlftpstagcolumnname", "nullsqlsapcolumnname", "nullsqlsqlcolumnname", "nullsqlsharepointcolumnname", "nullsqlftpcolumnname", "unionsqlall", "unionsqlallexecute", "loadsqlfactl1monitor", "dmsstatus", "dmsstatuscomment", "dmsadolink") VALUES
(1, 'Medicine ID should Match in FTP, SAP, SharePoint,SQL ', 'SAP_Medicine', 'MedicineID', 'DMS_SAP_Medicine', 'MedicineID', NULL, TRUE, 'SQL_Medicine', 'MedicineID', 'DMS_SQL_Medicine', 'MedicineID', NULL, TRUE, 'SharePoint_Medicine', 'MedicineID', 'DMS_SharePoint_Medicine', 'MedicineID', NULL, TRUE, 'FTP_Medicine', 'MedicineID', 'DMS_FTP_Medicine', 'MedicineID', '1', 1, NULL, TRUE, NULL, FALSE, 'Present in All Sources', NULL, TRUE, '[MedicineConfig]', TRUE, TRUE, 'MedicineID', 'MedicineID', 'MedicineID', 'MedicineID', NULL, NULL, FALSE, 2, 19, 'MedicineConfig', 'MedicineID', 'Medicine ID should Match in FTP, SAP, SharePoint,SQL ', NULL, NULL, NULL, NULL, 'ShP+FTP+SAP+SQL', 2, 'SELECT Distinct MedicineID From DMS_SAP_Medicine', 'SELECT Distinct MedicineID From DMS_SQL_Medicine', 'SELECT Distinct MedicineID From DMS_SharePoint_Medicine', 'SELECT Distinct MedicineID From DMS_FTP_Medicine', 'UPDATE DMS_SAP_Medicine SET MedicineID = null Where MedicineID is null or MedicineID=''NULL''', 'UPDATE DMS_SQL_Medicine SET MedicineID = null Where MedicineID is null or MedicineID=''NULL''', 'UPDATE DMS_SharePoint_Medicine SET MedicineID = null Where MedicineID is null or MedicineID=''NULL''', 'UPDATE DMS_FTP_Medicine SET MedicineID = null Where MedicineID is null or MedicineID=''NULL''', 'SELECT Distinct MedicineID From DMS_SAP_Medicine UNION SELECT Distinct MedicineID From DMS_SQL_Medicine UNION SELECT Distinct MedicineID From DMS_SharePoint_Medicine UNION SELECT Distinct MedicineID From DMS_FTP_Medicine', 'INSERT INTO #TempConfigValueL2
(BusinessPartner, ConfigValue)
SELECT Distinct Cast(MedicineID As Varchar(200)) AS [BusinessPartner], Cast(MedicineID As Varchar(200)) AS ConfigValue From DMS_SAP_Medicine UNION SELECT Distinct Cast(MedicineID As Varchar(200)) AS [BusinessPartner], Cast(MedicineID As Varchar(200)) From DMS_SQL_Medicine UNION SELECT Distinct Cast(MedicineID As Varchar(200)) AS [BusinessPartner], Cast(MedicineID As Varchar(200)) From DMS_FTP_Medicine UNION SELECT Distinct Cast(MedicineID As Varchar(200)) AS [BusinessPartner], Cast(MedicineID As Varchar(200)) From DMS_SharePoint_Medicine', 'INSERT INTO #DMS_FactL2Monitor
( [BusinessPartner],[ConfigValue], [IsSAP], [IsSQL],[IsFTP],[IsSharePoint])
SELECT Distinct 
MAIN.[BusinessPartner]
,MAIN.ConfigValue
, CASE WHEN  SAP.ConfigValue IS NULL THEN 0 ELSE 1 END AS IsSAP
, CASE WHEN  SQL.ConfigValue  IS NULL THEN 0 ELSE 1 END AS IsSQL
, CASE WHEN  FTP.ConfigValue  IS NULL THEN 0 ELSE 1 END AS IsFTP
, CASE WHEN  ShP.ConfigValue  IS NULL THEN 0 ELSE 1 END AS IsSharePoint
FROM #TempConfigValueL2 main
LEFT JOIN (SELECT Cast(MedicineID As Varchar(200)) AS [BusinessPartner], Cast(MedicineID As Varchar(200)) AS ConfigValue FROM DMS_SAP_Medicine ) SAP  
ON MAIN.ConfigValue = SAP.ConfigValue AND main.[BusinessPartner]=SAP.[BusinessPartner] 
LEFT JOIN (SELECT Cast(MedicineID As Varchar(200))  AS [BusinessPartner], Cast(MedicineID As Varchar(200)) AS ConfigValue From DMS_SQL_Medicine  ) SQL  
ON MAIN.ConfigValue = SQL.ConfigValue AND main.[BusinessPartner]=SQL.[BusinessPartner] 
LEFT JOIN (SELECT Cast(MedicineID As Varchar(200))  AS [BusinessPartner], Cast(MedicineID As Varchar(200)) AS ConfigValue From DMS_FTP_Medicine ) FTP  
ON MAIN.ConfigValue = FTP.ConfigValue AND main.[BusinessPartner]=FTP.[BusinessPartner] 
LEFT JOIN (SELECT Cast(MedicineID As Varchar(200))  AS [BusinessPartner], Cast(MedicineID As Varchar(200)) AS ConfigValue From DMS_SharePoint_Medicine ) ShP  
ON MAIN.ConfigValue = ShP.ConfigValue AND main.[BusinessPartner]=ShP.[BusinessPartner] 
Where  MAIN.ConfigValue is not null and len(MAIN.ConfigValue)>0 and MAIN.[BusinessPartner] is not null', 'DMS Passed', 'Percentage Matched > 80, Rules applied as per Sync rule and spot checked from 1 matched and not matched with source system', NULL),
(2, 'MedicineName should Match in FTP, SAP, SharePoint,SQL ', 'SAP_Medicine', 'MedicineName', 'DMS_SAP_Medicine', 'MedicineName', NULL, TRUE, 'SQL_Medicine', 'MedicineName', 'DMS_SQL_Medicine', 'MedicineName', NULL, TRUE, 'SharePoint_Medicine', 'MedicineName', 'DMS_SharePoint_Medicine', 'MedicineName', NULL, TRUE, 'FTP_Medicine', 'MedicineName', 'DMS_FTP_Medicine', 'MedicineName', '1', 1, NULL, TRUE, NULL, FALSE, 'Present in All Sources', NULL, TRUE, '[MedicineConfig]', TRUE, TRUE, 'MedicineID', 'MedicineID', 'MedicineID', 'MedicineID', NULL, NULL, FALSE, 2, 19, 'MedicineConfig', 'MedicineName', 'MedicineName should Match in FTP, SAP, SharePoint,SQL ', NULL, NULL, NULL, NULL, 'ShP+FTP+SAP+SQL', 2, 'SELECT Distinct MedicineName From DMS_SAP_Medicine', 'SELECT Distinct MedicineName From DMS_SQL_Medicine', 'SELECT Distinct MedicineName From DMS_SharePoint_Medicine', 'SELECT Distinct MedicineName From DMS_FTP_Medicine', 'UPDATE DMS_SAP_Medicine SET MedicineName = null Where MedicineName is null or MedicineName=''NULL''', 'UPDATE DMS_SQL_Medicine SET MedicineName = null Where MedicineName is null or MedicineName=''NULL''', 'UPDATE DMS_SharePoint_Medicine SET MedicineName = null Where MedicineName is null or MedicineName=''NULL''', 'UPDATE DMS_FTP_Medicine SET MedicineName = null Where MedicineName is null or MedicineName=''NULL''', 'SELECT Distinct MedicineName From DMS_SAP_Medicine UNION SELECT Distinct MedicineName From DMS_SQL_Medicine UNION SELECT Distinct MedicineName From DMS_SharePoint_Medicine UNION SELECT Distinct MedicineName From DMS_FTP_Medicine', 'INSERT INTO #TempConfigValueL2
(BusinessPartner, ConfigValue)
SELECT Distinct Cast(MedicineID As Varchar(200)) AS [BusinessPartner], Cast(MedicineName As Varchar(200)) AS ConfigValue From DMS_SAP_Medicine UNION SELECT Distinct Cast(MedicineID As Varchar(200)) AS [BusinessPartner], Cast(MedicineName As Varchar(200)) From DMS_SQL_Medicine UNION SELECT Distinct Cast(MedicineID As Varchar(200)) AS [BusinessPartner], Cast(MedicineName As Varchar(200)) From DMS_FTP_Medicine UNION SELECT Distinct Cast(MedicineID As Varchar(200)) AS [BusinessPartner], Cast(MedicineName As Varchar(200)) From DMS_SharePoint_Medicine', 'INSERT INTO #DMS_FactL2Monitor
( [BusinessPartner],[ConfigValue], [IsSAP], [IsSQL],[IsFTP],[IsSharePoint])
SELECT Distinct 
MAIN.[BusinessPartner]
,MAIN.ConfigValue
, CASE WHEN  SAP.ConfigValue IS NULL THEN 0 ELSE 1 END AS IsSAP
, CASE WHEN  SQL.ConfigValue  IS NULL THEN 0 ELSE 1 END AS IsSQL
, CASE WHEN  FTP.ConfigValue  IS NULL THEN 0 ELSE 1 END AS IsFTP
, CASE WHEN  ShP.ConfigValue  IS NULL THEN 0 ELSE 1 END AS IsSharePoint
FROM #TempConfigValueL2 main
LEFT JOIN (SELECT Cast(MedicineID As Varchar(200)) AS [BusinessPartner], Cast(MedicineName As Varchar(200)) AS ConfigValue FROM DMS_SAP_Medicine ) SAP  
ON MAIN.ConfigValue = SAP.ConfigValue AND main.[BusinessPartner]=SAP.[BusinessPartner] 
LEFT JOIN (SELECT Cast(MedicineID As Varchar(200))  AS [BusinessPartner], Cast(MedicineName As Varchar(200)) AS ConfigValue From DMS_SQL_Medicine  ) SQL  
ON MAIN.ConfigValue = SQL.ConfigValue AND main.[BusinessPartner]=SQL.[BusinessPartner] 
LEFT JOIN (SELECT Cast(MedicineID As Varchar(200))  AS [BusinessPartner], Cast(MedicineName As Varchar(200)) AS ConfigValue From DMS_FTP_Medicine ) FTP  
ON MAIN.ConfigValue = FTP.ConfigValue AND main.[BusinessPartner]=FTP.[BusinessPartner] 
LEFT JOIN (SELECT Cast(MedicineID As Varchar(200))  AS [BusinessPartner], Cast(MedicineName As Varchar(200)) AS ConfigValue From DMS_SharePoint_Medicine ) ShP  
ON MAIN.ConfigValue = ShP.ConfigValue AND main.[BusinessPartner]=ShP.[BusinessPartner] 
Where  MAIN.ConfigValue is not null and len(MAIN.ConfigValue)>0 and MAIN.[BusinessPartner] is not null', 'DMS Not Passed', 'DMS Team looking into Processing Issue', NULL),
(3, 'MedicineCategory should Match in FTP, SAP, SharePoint,SQL ', 'SAP_Medicine', 'MedicineCategory', 'DMS_SAP_Medicine', 'MedicineCategory', NULL, TRUE, 'SQL_Medicine', 'MedicineCategory', 'DMS_SQL_Medicine', 'MedicineCategory', NULL, TRUE, 'SharePoint_Medicine', 'MedicineCategory', 'DMS_SharePoint_Medicine', 'MedicineCategory', NULL, TRUE, 'FTP_Medicine', 'MedicineCategory', 'DMS_FTP_Medicine', 'MedicineCategory', '1', 1, NULL, TRUE, NULL, FALSE, 'Present in All Sources', NULL, TRUE, '[MedicineConfig]', TRUE, TRUE, 'MedicineID', 'MedicineID', 'MedicineID', 'MedicineID', NULL, NULL, FALSE, 2, 19, 'MedicineConfig', 'MedicineCategory', 'MedicineCategory should Match in FTP, SAP, SharePoint,SQL ', NULL, NULL, NULL, NULL, 'ShP+FTP+SAP+SQL', 2, 'SELECT Distinct MedicineCategory From DMS_SAP_Medicine', 'SELECT Distinct MedicineCategory From DMS_SQL_Medicine', 'SELECT Distinct MedicineCategory From DMS_SharePoint_Medicine', 'SELECT Distinct MedicineCategory From DMS_FTP_Medicine', 'UPDATE DMS_SAP_Medicine SET MedicineCategory = null Where MedicineCategory is null or MedicineCategory=''NULL''', 'UPDATE DMS_SQL_Medicine SET MedicineCategory = null Where MedicineCategory is null or MedicineCategory=''NULL''', 'UPDATE DMS_SharePoint_Medicine SET MedicineCategory = null Where MedicineCategory is null or MedicineCategory=''NULL''', 'UPDATE DMS_FTP_Medicine SET MedicineCategory = null Where MedicineCategory is null or MedicineCategory=''NULL''', 'SELECT Distinct MedicineCategory From DMS_SAP_Medicine UNION SELECT Distinct MedicineCategory From DMS_SQL_Medicine UNION SELECT Distinct MedicineCategory From DMS_SharePoint_Medicine UNION SELECT Distinct MedicineCategory From DMS_FTP_Medicine', 'INSERT INTO #TempConfigValueL2
(BusinessPartner, ConfigValue)
SELECT Distinct Cast(MedicineID As Varchar(200)) AS [BusinessPartner], Cast(MedicineCategory As Varchar(200)) AS ConfigValue From DMS_SAP_Medicine UNION SELECT Distinct Cast(MedicineID As Varchar(200)) AS [BusinessPartner], Cast(MedicineCategory As Varchar(200)) From DMS_SQL_Medicine UNION SELECT Distinct Cast(MedicineID As Varchar(200)) AS [BusinessPartner], Cast(MedicineCategory As Varchar(200)) From DMS_FTP_Medicine UNION SELECT Distinct Cast(MedicineID As Varchar(200)) AS [BusinessPartner], Cast(MedicineCategory As Varchar(200)) From DMS_SharePoint_Medicine', 'INSERT INTO #DMS_FactL2Monitor
( [BusinessPartner],[ConfigValue], [IsSAP], [IsSQL],[IsFTP],[IsSharePoint])
SELECT Distinct 
MAIN.[BusinessPartner]
,MAIN.ConfigValue
, CASE WHEN  SAP.ConfigValue IS NULL THEN 0 ELSE 1 END AS IsSAP
, CASE WHEN  SQL.ConfigValue  IS NULL THEN 0 ELSE 1 END AS IsSQL
, CASE WHEN  FTP.ConfigValue  IS NULL THEN 0 ELSE 1 END AS IsFTP
, CASE WHEN  ShP.ConfigValue  IS NULL THEN 0 ELSE 1 END AS IsSharePoint
FROM #TempConfigValueL2 main
LEFT JOIN (SELECT Cast(MedicineID As Varchar(200)) AS [BusinessPartner], Cast(MedicineCategory As Varchar(200)) AS ConfigValue FROM DMS_SAP_Medicine ) SAP  
ON MAIN.ConfigValue = SAP.ConfigValue AND main.[BusinessPartner]=SAP.[BusinessPartner] 
LEFT JOIN (SELECT Cast(MedicineID As Varchar(200))  AS [BusinessPartner], Cast(MedicineCategory As Varchar(200)) AS ConfigValue From DMS_SQL_Medicine  ) SQL  
ON MAIN.ConfigValue = SQL.ConfigValue AND main.[BusinessPartner]=SQL.[BusinessPartner] 
LEFT JOIN (SELECT Cast(MedicineID As Varchar(200))  AS [BusinessPartner], Cast(MedicineCategory As Varchar(200)) AS ConfigValue From DMS_FTP_Medicine ) FTP  
ON MAIN.ConfigValue = FTP.ConfigValue AND main.[BusinessPartner]=FTP.[BusinessPartner] 
LEFT JOIN (SELECT Cast(MedicineID As Varchar(200))  AS [BusinessPartner], Cast(MedicineCategory As Varchar(200)) AS ConfigValue From DMS_SharePoint_Medicine ) ShP  
ON MAIN.ConfigValue = ShP.ConfigValue AND main.[BusinessPartner]=ShP.[BusinessPartner] 
Where  MAIN.ConfigValue is not null and len(MAIN.ConfigValue)>0 and MAIN.[BusinessPartner] is not null', 'DMS Not Passed', 'DMS Team looking into Processing Issue', NULL),
(4, 'Patient Id should Match in FTP, SAP, SharePoint,SQL', 'SAP_Patient', 'PatientID', 'DMS_SAP_Patient', 'PatientID', NULL, TRUE, 'SQL_Patient', 'PatientID', 'DMS_SQL_Patient', 'PatientID', NULL, TRUE, 'SharePoint_Patient', 'PatientID', 'DMS_SharePoint_Patient', 'PatientID', NULL, TRUE, 'FTP_Patient', 'PatientID', 'DMS_FTP_Patient', 'PatientID', '1', 1, NULL, TRUE, NULL, FALSE, 'Present in All Sources', NULL, TRUE, '[PatientConfig]', TRUE, TRUE, 'PatientID', 'PatientID', 'PatientID', 'PatientID', NULL, NULL, FALSE, 2, 20, 'PatientConfig', 'PatientID', 'Patient ID Should Match in FTP, SAP, SharePoint,SQL', NULL, NULL, NULL, NULL, 'ShP+FTP+SAP+SQL', 2, 'SELECT Distinct PatientID From DMS_SAP_Patient', 'SELECT Distinct PatientID From DMS_SQL_Patient', 'SELECT Distinct PatientID From DMS_SharePoint_Patient', 'SELECT Distinct PatientID From DMS_FTP_Patient', 'UPDATE DMS_SAP_Patient SET PatientID = null Where PatientID is null or PatientID=''NULL''', 'UPDATE DMS_SQL_Patient SET PatientID = null Where PatientID is null or PatientID=''NULL''', 'UPDATE DMS_SharePoint_Patient SET PatientID = null Where PatientID is null or PatientID=''NULL''', 'UPDATE DMS_FTP_Patient SET PatientID = null Where PatientID is null or PatientID=''NULL''', 'SELECT Distinct PatientID From DMS_SAP_Patient UNION SELECT Distinct PatientID From DMS_SQL_Patient UNION SELECT Distinct PatientID From DMS_SharePoint_Patient UNION SELECT Distinct PatientID From DMS_FTP_Patient', 'INSERT INTO #TempConfigValueL2
(BusinessPartner, ConfigValue)
SELECT Distinct Cast(PatientID As Varchar(200)) AS [BusinessPartner], Cast(PatientID As Varchar(200)) AS ConfigValue From DMS_SAP_Patient UNION SELECT Distinct Cast(PatientID As Varchar(200)) AS [BusinessPartner], Cast(PatientID As Varchar(200)) From DMS_SQL_Patient UNION SELECT Distinct Cast(PatientID As Varchar(200)) AS [BusinessPartner], Cast(PatientID As Varchar(200)) From DMS_FTP_Patient UNION SELECT Distinct Cast(PatientID As Varchar(200)) AS [BusinessPartner], Cast(PatientID As Varchar(200)) From DMS_SharePoint_Patient', 'INSERT INTO #DMS_FactL2Monitor
( [BusinessPartner],[ConfigValue], [IsSAP], [IsSQL],[IsFTP],[IsSharePoint])
SELECT Distinct 
MAIN.[BusinessPartner]
,MAIN.ConfigValue
, CASE WHEN  SAP.ConfigValue IS NULL THEN 0 ELSE 1 END AS IsSAP
, CASE WHEN  SQL.ConfigValue  IS NULL THEN 0 ELSE 1 END AS IsSQL
, CASE WHEN  FTP.ConfigValue  IS NULL THEN 0 ELSE 1 END AS IsFTP
, CASE WHEN  ShP.ConfigValue  IS NULL THEN 0 ELSE 1 END AS IsSharePoint
FROM #TempConfigValueL2 main
LEFT JOIN (SELECT Cast(PatientID As Varchar(200)) AS [BusinessPartner], Cast(PatientID As Varchar(200)) AS ConfigValue FROM DMS_SAP_Patient ) SAP  
ON MAIN.ConfigValue = SAP.ConfigValue AND main.[BusinessPartner]=SAP.[BusinessPartner] 
LEFT JOIN (SELECT Cast(PatientID As Varchar(200))  AS [BusinessPartner], Cast(PatientID As Varchar(200)) AS ConfigValue From DMS_SQL_Patient  ) SQL  
ON MAIN.ConfigValue = SQL.ConfigValue AND main.[BusinessPartner]=SQL.[BusinessPartner] 
LEFT JOIN (SELECT Cast(PatientID As Varchar(200))  AS [BusinessPartner], Cast(PatientID As Varchar(200)) AS ConfigValue From DMS_FTP_Patient ) FTP  
ON MAIN.ConfigValue = FTP.ConfigValue AND main.[BusinessPartner]=FTP.[BusinessPartner] 
LEFT JOIN (SELECT Cast(PatientID As Varchar(200))  AS [BusinessPartner], Cast(PatientID As Varchar(200)) AS ConfigValue From DMS_SharePoint_Patient ) ShP  
ON MAIN.ConfigValue = ShP.ConfigValue AND main.[BusinessPartner]=ShP.[BusinessPartner] 
Where  MAIN.ConfigValue is not null and len(MAIN.ConfigValue)>0 and MAIN.[BusinessPartner] is not null', 'DMS Not Passed', 'DMS Team looking into Processing Issue', NULL),
(5, 'Patient Name should Match in FTP, SAP, SQL', 'SAP_Patient', 'FirstName+LastName', 'DMS_SAP_Patient', 'PatientName', NULL, TRUE, 'SQL_Patient', 'FirstName+LastName', 'DMS_SQL_Patient', 'PatientName', NULL, TRUE, NULL, NULL, NULL, NULL, NULL, NULL, 'FTP_Patient', 'FirstName+LastName', 'DMS_FTP_Patient', 'PatientName', '1', 1, NULL, TRUE, NULL, FALSE, 'Present in FTP, SAP, SQL Sources', NULL, TRUE, '[PatientConfig]', TRUE, TRUE, 'PatientID', 'PatientID', 'PatientID', 'PatientID', NULL, NULL, FALSE, 2, 20, 'PatientConfig', 'PatientName', 'Patient Name Should Match in FTP, SAP, SQL', NULL, NULL, NULL, NULL, 'FTP+SAP+SQL', 2, 'SELECT Distinct PatientName From DMS_SAP_Patient', 'SELECT Distinct PatientName From DMS_SQL_Patient', NULL, 'SELECT Distinct PatientName From DMS_FTP_Patient', 'UPDATE DMS_SAP_Patient SET PatientName = null Where PatientName is null or PatientName=''NULL''', 'UPDATE DMS_SQL_Patient SET PatientName = null Where PatientName is null or PatientName=''NULL''', NULL, 'UPDATE DMS_FTP_Patient SET PatientName = null Where PatientName is null or PatientName=''NULL''', 'SELECT Distinct PatientName From DMS_SAP_Patient UNION SELECT Distinct PatientName From DMS_SQL_Patient UNION SELECT Distinct PatientName From DMS_FTP_Patient', 'INSERT INTO #TempConfigValueL2
(BusinessPartner, ConfigValue)
SELECT Distinct Cast(PatientID As Varchar(200)) AS [BusinessPartner], Cast(PatientName As Varchar(200)) AS ConfigValue From DMS_SAP_Patient UNION SELECT Distinct Cast(PatientID As Varchar(200)) AS [BusinessPartner], Cast(PatientName As Varchar(200)) From DMS_SQL_Patient UNION SELECT Distinct Cast(PatientID As Varchar(200)) AS [BusinessPartner], Cast(PatientName As Varchar(200)) From DMS_FTP_Patient', 'INSERT INTO #DMS_FactL2Monitor
( [BusinessPartner],[ConfigValue], [IsSAP], [IsSQL],[IsFTP])
SELECT Distinct 
MAIN.[BusinessPartner]
,MAIN.ConfigValue
, CASE WHEN  SAP.ConfigValue IS NULL THEN 0 ELSE 1 END AS IsSAP
, CASE WHEN  SQL.ConfigValue  IS NULL THEN 0 ELSE 1 END AS IsSQL
, CASE WHEN  FTP.ConfigValue  IS NULL THEN 0 ELSE 1 END AS IsFTP
FROM #TempConfigValueL2 main
LEFT JOIN (SELECT Cast(PatientID As Varchar(200)) AS [BusinessPartner], Cast(PatientName As Varchar(200)) AS ConfigValue FROM DMS_SAP_Patient ) SAP  
ON MAIN.ConfigValue = SAP.ConfigValue AND main.[BusinessPartner]=SAP.[BusinessPartner] 
LEFT JOIN (SELECT Cast(PatientID As Varchar(200))  AS [BusinessPartner], Cast(PatientName As Varchar(200)) AS ConfigValue From DMS_SQL_Patient  ) SQL  
ON MAIN.ConfigValue = SQL.ConfigValue AND main.[BusinessPartner]=SQL.[BusinessPartner] 
LEFT JOIN (SELECT Cast(PatientID As Varchar(200))  AS [BusinessPartner], Cast(PatientName As Varchar(200)) AS ConfigValue From DMS_FTP_Patient ) FTP  
ON MAIN.ConfigValue = FTP.ConfigValue AND main.[BusinessPartner]=FTP.[BusinessPartner] 
Where  MAIN.ConfigValue is not null and len(MAIN.ConfigValue)>0 and MAIN.[BusinessPartner] is not null', 'DMS Not Passed', 'DMS Team looking into Processing Issue', NULL),
(6, 'Insurance Provider should Match in FTP, SAP, SQL', 'SAP_Patient', 'InsuranceProvider', 'DMS_SAP_Patient', 'InsuranceProvider', NULL, TRUE, 'SQL_Patient', 'InsuranceProvider', 'DMS_SQL_Patient', 'InsuranceProvider', NULL, TRUE, NULL, NULL, NULL, NULL, NULL, NULL, 'FTP_Patient', 'InsuranceProvider', 'DMS_FTP_Patient', 'InsuranceProvider', '1', 1, NULL, TRUE, NULL, FALSE, 'Present in FTP, SAP, SQL Sources', NULL, TRUE, '[PatientConfig]', TRUE, TRUE, 'PatientID', 'PatientID', 'PatientID', 'PatientID', NULL, NULL, FALSE, 2, 20, 'PatientConfig', 'InsuranceProvider', 'Insurance Provider Should Match in FTP, SAP, SQL', NULL, NULL, NULL, NULL, 'FTP+SAP+SQL', 2, 'SELECT Distinct InsuranceProvider From DMS_SAP_Patient', 'SELECT Distinct InsuranceProvider From DMS_SQL_Patient', NULL, 'SELECT Distinct InsuranceProvider From DMS_FTP_Patient', 'UPDATE DMS_SAP_Patient SET InsuranceProvider = null Where InsuranceProvider is null or InsuranceProvider=''NULL''', 'UPDATE DMS_SQL_Patient SET InsuranceProvider = null Where InsuranceProvider is null or InsuranceProvider=''NULL''', NULL, 'UPDATE DMS_FTP_Patient SET InsuranceProvider = null Where InsuranceProvider is null or InsuranceProvider=''NULL''', 'SELECT Distinct InsuranceProvider From DMS_SAP_Patient UNION SELECT Distinct InsuranceProvider From DMS_SQL_Patient UNION SELECT Distinct InsuranceProvider From DMS_FTP_Patient', 'INSERT INTO #TempConfigValueL2
(BusinessPartner, ConfigValue)
SELECT Distinct Cast(PatientID As Varchar(200)) AS [BusinessPartner], Cast(InsuranceProvider As Varchar(200)) AS ConfigValue From DMS_SAP_Patient UNION SELECT Distinct Cast(PatientID As Varchar(200)) AS [BusinessPartner], Cast(InsuranceProvider As Varchar(200)) From DMS_SQL_Patient UNION SELECT Distinct Cast(PatientID As Varchar(200)) AS [BusinessPartner], Cast(InsuranceProvider As Varchar(200)) From DMS_FTP_Patient', 'INSERT INTO #DMS_FactL2Monitor
( [BusinessPartner],[ConfigValue], [IsSAP], [IsSQL],[IsFTP])
SELECT Distinct 
MAIN.[BusinessPartner]
,MAIN.ConfigValue
, CASE WHEN  SAP.ConfigValue IS NULL THEN 0 ELSE 1 END AS IsSAP
, CASE WHEN  SQL.ConfigValue  IS NULL THEN 0 ELSE 1 END AS IsSQL
, CASE WHEN  FTP.ConfigValue  IS NULL THEN 0 ELSE 1 END AS IsFTP
FROM #TempConfigValueL2 main
LEFT JOIN (SELECT Cast(PatientID As Varchar(200)) AS [BusinessPartner], Cast(InsuranceProvider As Varchar(200)) AS ConfigValue FROM DMS_SAP_Patient ) SAP  
ON MAIN.ConfigValue = SAP.ConfigValue AND main.[BusinessPartner]=SAP.[BusinessPartner] 
LEFT JOIN (SELECT Cast(PatientID As Varchar(200))  AS [BusinessPartner], Cast(InsuranceProvider As Varchar(200)) AS ConfigValue From DMS_SQL_Patient  ) SQL  
ON MAIN.ConfigValue = SQL.ConfigValue AND main.[BusinessPartner]=SQL.[BusinessPartner] 
LEFT JOIN (SELECT Cast(PatientID As Varchar(200))  AS [BusinessPartner], Cast(InsuranceProvider As Varchar(200)) AS ConfigValue From DMS_FTP_Patient ) FTP  
ON MAIN.ConfigValue = FTP.ConfigValue AND main.[BusinessPartner]=FTP.[BusinessPartner] 
Where  MAIN.ConfigValue is not null and len(MAIN.ConfigValue)>0 and MAIN.[BusinessPartner] is not null', 'DMS Not Passed', 'DMS Team looking into Processing Issue', NULL),
(7, 'Allergies should Match in SAP, SQL', 'SAP_Patient', 'Allergies', 'DMS_SAP_Patient', 'Allergies', NULL, TRUE, 'SQL_Patient', 'Allergies', 'DMS_SQL_Patient', 'Allergies', NULL, TRUE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, TRUE, NULL, FALSE, 'Present in SAP and SQL Sources', NULL, TRUE, '[PatientConfig]', TRUE, TRUE, 'PatientID', 'PatientID', 'PatientID', 'PatientID', NULL, NULL, FALSE, 2, 20, 'PatientConfig', 'Allergies', 'Allergies Should Match in SAP, SQL', NULL, NULL, NULL, NULL, 'SAP+SQL', 2, 'SELECT Distinct Allergies From DMS_SAP_Patient', 'SELECT Distinct Allergies From DMS_SQL_Patient', NULL, NULL, 'UPDATE DMS_SAP_Patient SET Allergies = null Where Allergies is null or Allergies=''NULL''', 'UPDATE DMS_SQL_Patient SET Allergies = null Where Allergies is null or Allergies=''NULL''', NULL, NULL, 'SELECT Distinct Allergies From DMS_SAP_Patient UNION SELECT Distinct Allergies From DMS_SQL_Patient', 'INSERT INTO #TempConfigValueL2
(BusinessPartner, ConfigValue)
SELECT Distinct Cast(PatientID As Varchar(200)) AS [BusinessPartner], Cast(Allergies As Varchar(200)) AS ConfigValue From DMS_SAP_Patient UNION SELECT Distinct Cast(PatientID As Varchar(200)) AS [BusinessPartner], Cast(Allergies As Varchar(200)) From DMS_SQL_Patient', 'INSERT INTO #DMS_FactL2Monitor
( [BusinessPartner],[ConfigValue], [IsSAP], [IsSQL])
SELECT Distinct 
MAIN.[BusinessPartner]
,MAIN.ConfigValue
, CASE WHEN  SAP.ConfigValue IS NULL THEN 0 ELSE 1 END AS IsSAP
, CASE WHEN  SQL.ConfigValue  IS NULL THEN 0 ELSE 1 END AS IsSQL

FROM #TempConfigValueL2 main
LEFT JOIN (SELECT Cast(PatientID As Varchar(200)) AS [BusinessPartner], Cast(Allergies As Varchar(200)) AS ConfigValue FROM DMS_SAP_Patient ) SAP  
ON MAIN.ConfigValue = SAP.ConfigValue AND main.[BusinessPartner]=SAP.[BusinessPartner] 
LEFT JOIN (SELECT Cast(PatientID As Varchar(200))  AS [BusinessPartner], Cast(Allergies As Varchar(200)) AS ConfigValue From DMS_SQL_Patient  ) SQL  
ON MAIN.ConfigValue = SQL.ConfigValue AND main.[BusinessPartner]=SQL.[BusinessPartner] 
Where  MAIN.ConfigValue is not null and len(MAIN.ConfigValue)>0 and MAIN.[BusinessPartner] is not null', 'DMS Not Passed', 'DMS Team looking into Processing Issue', NULL),
(8, 'Medical History should Match in ShP, SAP', 'SAP_Patient', 'MedicalHistory', 'DMS_SAP_Patient', 'MedicalHistory', NULL, TRUE, NULL, NULL, NULL, NULL, NULL, NULL, 'SharePoint_Patient', 'MedicalHistory', 'DMS_SharePoint_Patient', 'MedicalHistory', NULL, TRUE, NULL, NULL, NULL, NULL, NULL, 1, NULL, TRUE, NULL, FALSE, 'Present in  ShP and SAP Sources', NULL, TRUE, '[PatientConfig]', TRUE, TRUE, 'PatientID', 'PatientID', 'PatientID', 'PatientID', NULL, NULL, FALSE, 2, 20, 'PatientConfig', 'MedicalHistory', 'Medical History Should Match in ShP, SAP', NULL, NULL, NULL, NULL, 'ShP+SAP', 2, 'SELECT Distinct MedicalHistory From DMS_SharePoint_Patient', NULL, 'SELECT Distinct MedicalHistory From DMS_SAP_Patient', NULL, 'UPDATE DMS_SharePoint_Patient SET MedicalHistory = null Where MedicalHistory is null or MedicalHistory=''NULL''', NULL, 'UPDATE DMS_SAP_Patient SET MedicalHistory = null Where MedicalHistory is null or MedicalHistory=''NULL''', NULL, 'SELECT Distinct MedicalHistory From DMS_SAP_Patient UNION SELECT Distinct MedicalHistory From DMS_SharePoint_Patient', 'INSERT INTO #TempConfigValueL2
(BusinessPartner, ConfigValue)
SELECT Distinct Cast(PatientID As Varchar(200)) AS [BusinessPartner], Cast(MedicalHistory As Varchar(200)) AS ConfigValue From DMS_SAP_Patient UNION SELECT Distinct Cast(PatientID As Varchar(200)) AS [BusinessPartner], Cast(MedicalHistory As Varchar(200)) From DMS_SharePoint_Patient', 'INSERT INTO #DMS_FactL2Monitor
( [BusinessPartner],[ConfigValue], [IsSAP], [IsSharePoint])
SELECT Distinct 
MAIN.[BusinessPartner]
,MAIN.ConfigValue
, CASE WHEN  SAP.ConfigValue IS NULL THEN 0 ELSE 1 END AS IsSAP
, CASE WHEN  ShP.ConfigValue  IS NULL THEN 0 ELSE 1 END AS IsSharePoint
FROM #TempConfigValueL2 main
LEFT JOIN (SELECT Cast(PatientID As Varchar(200)) AS [BusinessPartner], Cast(MedicalHistory As Varchar(200)) AS ConfigValue FROM DMS_SAP_Patient ) SAP  
ON MAIN.ConfigValue = SAP.ConfigValue AND main.[BusinessPartner]=SAP.[BusinessPartner] 
LEFT JOIN (SELECT Cast(PatientID As Varchar(200))  AS [BusinessPartner], Cast(MedicalHistory As Varchar(200)) AS ConfigValue From DMS_SharePoint_Patient  ) ShP  
ON MAIN.ConfigValue = ShP.ConfigValue AND main.[BusinessPartner]=ShP.[BusinessPartner] 
Where  MAIN.ConfigValue is not null and len(MAIN.ConfigValue)>0', 'DMS Not Passed', 'DMS Team looking into Processing Issue', NULL),
(9, 'Insurance Number should Match in FTP, SAP, SQL', 'SAP_Patient', 'InsuranceNumber', 'DMS_SAP_Patient', 'InsuranceNumber', NULL, TRUE, 'SQL_Patient', 'InsuranceNumber', 'DMS_SQL_Patient', 'InsuranceNumber', NULL, TRUE, NULL, NULL, NULL, NULL, NULL, NULL, 'FTP_Patient', 'InsuranceNumber', 'DMS_FTP_Patient', 'InsuranceNumber', '1', 1, NULL, TRUE, NULL, FALSE, 'Present in FTP, SAP, SQL Sources', NULL, TRUE, '[PatientConfig]', TRUE, TRUE, 'PatientID', 'PatientID', 'PatientID', 'PatientID', NULL, NULL, FALSE, 2, 20, 'PatientConfig', 'InsuranceNumber', 'Insurance Number Should Match in FTP, SAP, SQL', NULL, NULL, NULL, NULL, 'FTP+SAP+SQL', 2, 'SELECT Distinct InsuranceNumber From DMS_SAP_Patient', 'SELECT Distinct InsuranceNumber From DMS_SQL_Patient', NULL, 'SELECT Distinct InsuranceNumber From DMS_FTP_Patient', 'UPDATE DMS_SAP_Patient SET InsuranceNumber = null Where InsuranceNumber is null or InsuranceNumber=''NULL''', 'UPDATE DMS_SQL_Patient SET InsuranceNumber = null Where InsuranceNumber is null or InsuranceNumber=''NULL''', NULL, 'UPDATE DMS_FTP_Patient SET InsuranceNumber = null Where InsuranceNumber is null or InsuranceNumber=''NULL''', 'SELECT Distinct InsuranceNumber From DMS_SAP_Patient UNION SELECT Distinct InsuranceNumber From DMS_SQL_Patient UNION SELECT Distinct InsuranceNumber From DMS_FTP_Patient', 'INSERT INTO #TempConfigValueL2
(BusinessPartner, ConfigValue)
SELECT Distinct Cast(PatientID As Varchar(200)) AS [BusinessPartner], Cast(InsuranceNumber As Varchar(200)) AS ConfigValue From DMS_SAP_Patient UNION SELECT Distinct Cast(PatientID As Varchar(200)) AS [BusinessPartner], Cast(InsuranceNumber As Varchar(200)) From DMS_SQL_Patient UNION SELECT Distinct Cast(PatientID As Varchar(200)) AS [BusinessPartner], Cast(InsuranceNumber As Varchar(200)) From DMS_FTP_Patient', 'INSERT INTO #DMS_FactL2Monitor
( [BusinessPartner],[ConfigValue], [IsSAP], [IsSQL],[IsFTP])
SELECT Distinct 
MAIN.[BusinessPartner]
,MAIN.ConfigValue
, CASE WHEN  SAP.ConfigValue IS NULL THEN 0 ELSE 1 END AS IsSAP
, CASE WHEN  SQL.ConfigValue  IS NULL THEN 0 ELSE 1 END AS IsSQL
, CASE WHEN  FTP.ConfigValue  IS NULL THEN 0 ELSE 1 END AS IsFTP
FROM #TempConfigValueL2 main
LEFT JOIN (SELECT Cast(PatientID As Varchar(200)) AS [BusinessPartner], Cast(InsuranceNumber As Varchar(200)) AS ConfigValue FROM DMS_SAP_Patient ) SAP  
ON MAIN.ConfigValue = SAP.ConfigValue AND main.[BusinessPartner]=SAP.[BusinessPartner] 
LEFT JOIN (SELECT Cast(PatientID As Varchar(200))  AS [BusinessPartner], Cast(InsuranceNumber As Varchar(200)) AS ConfigValue From DMS_SQL_Patient  ) SQL  
ON MAIN.ConfigValue = SQL.ConfigValue AND main.[BusinessPartner]=SQL.[BusinessPartner] 
LEFT JOIN (SELECT Cast(PatientID As Varchar(200))  AS [BusinessPartner], Cast(InsuranceNumber As Varchar(200)) AS ConfigValue From DMS_FTP_Patient ) FTP  
ON MAIN.ConfigValue = FTP.ConfigValue AND main.[BusinessPartner]=FTP.[BusinessPartner] 
Where  MAIN.ConfigValue is not null and len(MAIN.ConfigValue)>0 and MAIN.[BusinessPartner] is not null', 'DMS Not Passed', 'DMS Team looking into Processing Issue', NULL),
(10, 'Purchase Type should Match in SAP, SQL', 'SAP_MedicinePurchaseType', 'PurchaseType', 'DMS_SAP_MedicinePurchaseType', 'PurchaseType', NULL, TRUE, 'SQL_MedicinePurchaseType', 'PurchaseType', 'DMS_SQL_MedicinePurchaseType', 'PurchaseType', NULL, TRUE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, TRUE, NULL, FALSE, 'Present in SAP, SQL Sources', NULL, TRUE, '[MedicinePurchaseType]', TRUE, TRUE, 'PurchaseID', 'PurchaseID', NULL, 'PurchaseID', NULL, NULL, FALSE, 2, 21, 'MedicinePurchaseType', 'PurchaseType', 'Purchase Type Should Match in SAP, SQL', NULL, NULL, NULL, NULL, 'SAP+SQL', 2, 'SELECT Distinct PurchaseType From DMS_SAP_MedicinePurchaseType', 'SELECT Distinct PurchaseType From DMS_SQL_MedicinePurchaseType', NULL, NULL, 'UPDATE DMS_SAP_MedicinePurchaseType SET PurchaseType = null Where PurchaseType is null or PurchaseType=''NULL''', 'UPDATE DMS_SQL_MedicinePurchaseType SET PurchaseType = null Where PurchaseType is null or PurchaseType=''NULL''', NULL, NULL, 'SELECT Distinct PurchaseType From DMS_SAP_MedicinePurchaseType UNION SELECT Distinct PurchaseType From DMS_SQL_MedicinePurchaseType', 'INSERT INTO #TempConfigValueL2
(BusinessPartner, ConfigValue)
SELECT Distinct Cast(PurchaseID As Varchar(200)) AS [BusinessPartner], Cast(PurchaseType As Varchar(200)) AS ConfigValue From DMS_SAP_MedicinePurchaseType UNION SELECT Distinct Cast(PurchaseID As Varchar(200)) AS [BusinessPartner], Cast(PurchaseType As Varchar(200)) From DMS_SQL_MedicinePurchaseType', 'INSERT INTO #DMS_FactL2Monitor
( [BusinessPartner],[ConfigValue], [IsSAP], [IsSQL])
SELECT Distinct 
MAIN.[BusinessPartner]
,MAIN.ConfigValue
, CASE WHEN  SAP.ConfigValue IS NULL THEN 0 ELSE 1 END AS IsSAP
, CASE WHEN  SQL.ConfigValue  IS NULL THEN 0 ELSE 1 END AS IsSQL

FROM #TempConfigValueL2 main
LEFT JOIN (SELECT Cast(PurchaseID As Varchar(200)) AS [BusinessPartner], Cast(PurchaseType As Varchar(200)) AS ConfigValue FROM DMS_SAP_MedicinePurchaseType ) SAP  
ON MAIN.ConfigValue = SAP.ConfigValue AND main.[BusinessPartner]=SAP.[BusinessPartner] 
LEFT JOIN (SELECT Cast(PurchaseID As Varchar(200))  AS [BusinessPartner], Cast(PurchaseType As Varchar(200)) AS ConfigValue From DMS_SQL_MedicinePurchaseType  ) SQL  
ON MAIN.ConfigValue = SQL.ConfigValue AND main.[BusinessPartner]=SQL.[BusinessPartner] 
Where  MAIN.ConfigValue is not null and len(MAIN.ConfigValue)>0 and MAIN.[BusinessPartner] is not null', 'DMS Not Passed', 'DMS Team looking into Processing Issue', NULL),
(11, 'Payment Method should Match in SAP, SQL', 'SAP_MedicinePurchaseType', 'PaymentMethod', 'DMS_SAP_MedicinePurchaseType', 'PaymentMethod', NULL, TRUE, 'SQL_MedicinePurchaseType', 'PaymentMethod', 'DMS_SQL_MedicinePurchaseType', 'PaymentMethod', NULL, TRUE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, TRUE, NULL, FALSE, 'Present in SAP, SQL Sources', NULL, TRUE, '[MedicinePurchaseType]', TRUE, TRUE, 'PurchaseID', 'PurchaseID', NULL, 'PurchaseID', NULL, NULL, FALSE, 2, 21, 'MedicinePurchaseType', 'PaymentMethod', 'Payment Method Should Match in SAP, SQL', NULL, NULL, NULL, NULL, 'SAP+SQL', 2, 'SELECT Distinct PaymentMethod From DMS_SAP_MedicinePurchaseType', 'SELECT Distinct PaymentMethod From DMS_SQL_MedicinePurchaseType', NULL, NULL, 'UPDATE DMS_SAP_MedicinePurchaseType SET PaymentMethod = null Where PaymentMethod is null or PaymentMethod=''NULL''', 'UPDATE DMS_SQL_MedicinePurchaseType SET PaymentMethod = null Where PaymentMethod is null or PaymentMethod=''NULL''', NULL, NULL, 'SELECT Distinct PaymentMethod From DMS_SAP_MedicinePurchaseType UNION SELECT Distinct PaymentMethod From DMS_SQL_MedicinePurchaseType', 'INSERT INTO #TempConfigValueL2
(BusinessPartner, ConfigValue)
SELECT Distinct Cast(PurchaseID As Varchar(200)) AS [BusinessPartner], Cast(PaymentMethod As Varchar(200)) AS ConfigValue From DMS_SAP_MedicinePurchaseType UNION SELECT Distinct Cast(PurchaseID As Varchar(200)) AS [BusinessPartner], Cast(PaymentMethod As Varchar(200)) From DMS_SQL_MedicinePurchaseType', 'INSERT INTO #DMS_FactL2Monitor
( [BusinessPartner],[ConfigValue], [IsSAP], [IsSQL])
SELECT Distinct 
MAIN.[BusinessPartner]
,MAIN.ConfigValue
, CASE WHEN  SAP.ConfigValue IS NULL THEN 0 ELSE 1 END AS IsSAP
, CASE WHEN  SQL.ConfigValue  IS NULL THEN 0 ELSE 1 END AS IsSQL

FROM #TempConfigValueL2 main
LEFT JOIN (SELECT Cast(PurchaseID As Varchar(200)) AS [BusinessPartner], Cast(PaymentMethod As Varchar(200)) AS ConfigValue FROM DMS_SAP_MedicinePurchaseType ) SAP  
ON MAIN.ConfigValue = SAP.ConfigValue AND main.[BusinessPartner]=SAP.[BusinessPartner] 
LEFT JOIN (SELECT Cast(PurchaseID As Varchar(200))  AS [BusinessPartner], Cast(PaymentMethod As Varchar(200)) AS ConfigValue From DMS_SQL_MedicinePurchaseType  ) SQL  
ON MAIN.ConfigValue = SQL.ConfigValue AND main.[BusinessPartner]=SQL.[BusinessPartner] 
Where  MAIN.ConfigValue is not null and len(MAIN.ConfigValue)>0 and MAIN.[BusinessPartner] is not null', 'DMS Not Passed', 'DMS Team looking into Processing Issue', NULL),
(12, 'Insurance Covered should Match in Shp, SAP', 'SAP_MedicinePurchaseType', 'InsuranceCovered', 'DMS_SAP_MedicinePurchaseType', 'InsuranceCovered', NULL, TRUE, NULL, NULL, NULL, NULL, NULL, NULL, 'SharePoint_MedicinePurchaseType', 'InsuranceCovered', 'DMS_SharePoint_MedicinePurchaseType', 'InsuranceCovered', NULL, TRUE, NULL, NULL, NULL, NULL, NULL, 1, NULL, TRUE, NULL, FALSE, 'Present in ShP, SAP Sources', NULL, TRUE, '[MedicinePurchaseType]', TRUE, TRUE, 'PurchaseID', 'PurchaseID', NULL, 'PurchaseID', NULL, NULL, FALSE, 2, 21, 'MedicinePurchaseType', 'PaymentMethod', 'Payment Method Should Match in ShP, SAP', NULL, NULL, NULL, NULL, 'ShP+SAP', 2, 'SELECT Distinct InsuranceCovered From DMS_SharePoint_MedicinePurchaseType', NULL, 'SELECT Distinct InsuranceCovered From DMS_SAP_MedicinePurchaseType', NULL, 'UPDATE DMS_SharePoint_MedicinePurchaseType SET InsuranceCovered = null Where InsuranceCovered is null or InsuranceCovered=''NULL''', NULL, 'UPDATE DMS_SAP_MedicinePurchaseType SET InsuranceCovered = null Where InsuranceCovered is null or InsuranceCovered=''NULL''', NULL, 'SELECT Distinct InsuranceCovered From DMS_SAP_MedicinePurchaseType UNION SELECT Distinct InsuranceCovered From DMS_SharePoint_MedicinePurchaseType', 'INSERT INTO #TempConfigValueL2
(BusinessPartner, ConfigValue)
SELECT Distinct Cast(PurchaseID As Varchar(200)) AS [BusinessPartner], Cast(InsuranceCovered As Varchar(200)) AS ConfigValue From DMS_SAP_MedicinePurchaseType UNION SELECT Distinct Cast(PurchaseID As Varchar(200)) AS [BusinessPartner], Cast(InsuranceCovered As Varchar(200)) From DMS_SharePoint_MedicinePurchaseType', 'INSERT INTO #DMS_FactL2Monitor
( [BusinessPartner],[ConfigValue], [IsSAP], [IsSharePoint])
SELECT Distinct 
MAIN.[BusinessPartner]
,MAIN.ConfigValue
, CASE WHEN  SAP.ConfigValue IS NULL THEN 0 ELSE 1 END AS IsSAP
, CASE WHEN  ShP.ConfigValue  IS NULL THEN 0 ELSE 1 END AS IsSharePoint
FROM #TempConfigValueL2 main
LEFT JOIN (SELECT Cast(PurchaseID As Varchar(200)) AS [BusinessPartner], Cast(InsuranceCovered As Varchar(200)) AS ConfigValue FROM DMS_SAP_MedicinePurchaseType ) SAP  
ON MAIN.ConfigValue = SAP.ConfigValue AND main.[BusinessPartner]=SAP.[BusinessPartner] 
LEFT JOIN (SELECT Cast(PurchaseID As Varchar(200))  AS [BusinessPartner], Cast(InsuranceCovered As Varchar(200)) AS ConfigValue From DMS_SharePoint_MedicinePurchaseType  ) ShP  
ON MAIN.ConfigValue = ShP.ConfigValue AND main.[BusinessPartner]=ShP.[BusinessPartner] 
Where  MAIN.ConfigValue is not null and len(MAIN.ConfigValue)>0', 'DMS Not Passed', 'DMS Team looking into Processing Issue', NULL);
