-- Generated by dbmigration. Data for aidd.llm_providers -> livebit_aidd.llm_providers.
INSERT INTO "livebit_aidd"."llm_providers" ("id", "name", "base_url", "status", "created_at", "updated_at") VALUES
('e43c68ca-e3e6-4c9a-86ac-5c5e95e5810b', 'Azure AI', 'https://aidd-azureaifoundry.cognitiveservices.azure.com/openai/v1/', 'active', '2025-09-29 07:36:14.669000+00:00', '2025-09-29 07:36:14.669000+00:00');
