-- Generated by dbmigration. Data for divaconfig.StoredProcSubTabOperation -> livebit_divaconfig.storedprocsubtaboperation.
INSERT INTO "livebit_divaconfig"."storedprocsubtaboperation" ("spstid", "procedureid", "subtabid", "createddate", "modifieddate", "status", "defaultparameterlist", "spstidsq", "spstidesc") VALUES
(1, 30, 81, '2025-01-23 09:46:15.610000', NULL, 'Active', NULL, NULL, NULL),
(2, 12, 81, '2025-01-23 09:46:19.120000', NULL, 'Active', NULL, NULL, NULL),
(3, 33, 81, '2025-01-23 09:46:43.620000', NULL, 'Active', NULL, NULL, NULL),
(4, 30, 100, '2025-01-23 09:46:48.133000', NULL, 'Active', NULL, NULL, NULL),
(5, 12, 100, '2025-01-23 09:47:00.930000', NULL, 'Active', NULL, NULL, NULL),
(6, 33, 100, '2025-01-23 09:47:04.947000', NULL, 'Active', NULL, NULL, NULL),
(7, 2, 81, NULL, NULL, 'Active', NULL, NULL, NULL),
(8, 50, 84, '2025-02-07 03:55:04.817000', NULL, 'Active', NULL, NULL, 'Load Special Table Card Chart'),
(9, 120, 110, '2025-02-07 04:17:24.377000', NULL, 'Active', NULL, NULL, 'Update Company Info');
