-- Generated by dbmigration. Data for divaconfig.Roles -> livebit_divaconfig.roles.
INSERT INTO "livebit_divaconfig"."roles" ("roleid", "rolename", "description") VALUES
(1, 'App Admin', 'Super Admin, Access to all'),
(2, 'Admin', 'Company Admin access to all except core configuration'),
(3, 'User', 'Read only'),
(4, 'Contributor', 'Access to certain areas except admin level');
