-- Generated by dbmigration. Data for dbo.DMS_FactFunctionaStats -> livebit_dbo.dms_factfunctionastats.
INSERT INTO "livebit_dbo"."dms_factfunctionastats" ("syncdatatype", "configidcount", "totoalattributevalue", "attributevaluematched", "attributevaluenotmatched", "percentagematched", "percentagenotmatched") VALUES
('MedicineConfig', 3, 104, 78, 26, 75.0, 25.0),
('MedicinePurchaseType', 3, 90, 90, 0, 100.0, 0.0),
('PatientConfig', 6, 222, 150, 72, 67.57, 32.43);
