-- Generated by dbmigration. Data for dbo.ExecutionLog -> livebit_dbo.executionlog.
INSERT INTO "livebit_dbo"."executionlog" ("logid", "executionguid", "procedurename", "starttime", "endtime", "parameterdetails", "status", "errormessage", "openaistepname", "openaiparameterdetails", "openaiprompt", "additionalloggingdetails", "surveyid", "surveyproductid", "step3_query", "step3_q_output", "step4_query", "step4_resp_output") VALUES
(1, '9CCD456C-6A57-4559-90BB-83690CEB31E3', 'Procedure1', '2024-09-10 19:44:37.640000', '2024-09-10 19:45:48.330000', 'Param1=Value1', 'Completed', NULL, 'Step1', 'OpenAIParam1=Value1', 'OpenAI prompt example', 'Execution completed successfully', NULL, NULL, NULL, NULL, NULL, NULL),
(4, NULL, 'Procedure2', '1900-01-13 00:00:00', '1900-05-04 00:00:00', NULL, 'Not Completed', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5, NULL, 'Procedure3', '1900-01-13 00:00:00', '1900-05-04 00:00:00', NULL, 'InProgress', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(6, NULL, 'Procedure3', '1900-01-13 00:00:00', '1900-05-04 00:00:00', NULL, 'InProgress', NULL, NULL, NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
    SELECT ''Assessment'',
           ''SAP Basis154'',
           ''Evaluation of knowledge and performance in SAP Basis154 assessment'',
      (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 
           0
    WHERE NOT EXISTS
        (SELECT 1 
         FROM [dbo].[SurveyGroup]
         WHERE SurveyProductName = ''SAP Basis154''
           AND SurveyProductCategory = ''Assessment'');
    SELECT SCOPE_IDENTITY();', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11, NULL, 'Procedure3', '2024-09-20 12:00:12.337000', '2024-09-20 12:00:29.430000', NULL, 'Started', 'no error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'',
       ''sap basis176'',
       ''Evaluation assessment using knowledge performing assessment in Assessment for sap basis176'',
  (SELECT MAX(SurveyProductSort) + 1
   FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS
    (SELECT 1
     FROM [dbo].[SurveyGroup]
     WHERE SurveyProductName = ''sap basis176''
       AND SurveyProductCategory = ''Assessment'');


SELECT SCOPE_IDENTITY();', NULL, NULL, '1592', 'NULL', 'NULL', 'NULL', 'NULL'),
(12, NULL, 'Procedure3', '2024-09-20 12:18:38.813000', '2024-09-20 12:19:09.280000', NULL, 'Started', 'no error', '2', NULL, 'INSERT INTO [dbo].[Survey] ([SurveyProductID], [SurveyCategory], [SurveyName], [SurveyDesc], [SurveyLastUpdated], [SurveyStartDate], [SurveyEndDate], [SurveySalesYearDate], [SurveyNextResetRunningWindowInDays], [SurveyIsLockedForSeason], [SurveyGenratedByAI], [SurveyAIVerifiedByHuman], [SurveyApprovedByUserID], [SurveyRequestByUserID])
SELECT 1593,
       ''Assessment'',
       ''sap basis177 - sap basis advanced'',
       ''This assessment evaluates the maturity of an organizations sap basis177 program. It consists of ${NumberOfQ} questions that aim to guide the organization on its next steps towards improving its sap basis177 practices.'',
       GETDATE(),
       GETDATE(),
       ''12-31-9999'',
       GETDATE(),
       30,
       1,
       1,
       0,
       NULL,
       NULL
WHERE NOT EXISTS
    (SELECT 1
     FROM [dbo].[Survey]
     WHERE [SurveyName] = ''sap basis177 - sap basis advanced'')', NULL, '467', '1593', 'NULL', 'NULL', 'NULL', 'NULL'),
(13, NULL, 'Procedure3', '2024-09-20 12:31:58.017000', '2024-09-20 12:32:15.110000', NULL, 'Started', 'no error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'',
       ''sap basis178'',
       ''Evaluation of knowledge and performance in sap basis178 with respect to Assessment'',
  (SELECT MAX(SurveyProductSort) + 1
   FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS
    (SELECT 1
     FROM [dbo].[SurveyGroup]
     WHERE SurveyProductName = ''sap basis178''
       AND SurveyProductCategory = ''Assessment'');


SELECT SCOPE_IDENTITY();', NULL, NULL, '1594', 'NULL', 'NULL', 'NULL', 'NULL'),
(14, NULL, 'Procedure3', '2024-09-20 12:31:58.017000', '2024-09-20 12:32:15.110000', NULL, 'Started', 'no error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'',
       ''sap basis178'',
       ''Evaluation of knowledge and performance in sap basis178 with respect to Assessment'',
  (SELECT MAX(SurveyProductSort) + 1
   FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS
    (SELECT 1
     FROM [dbo].[SurveyGroup]
     WHERE SurveyProductName = ''sap basis178''
       AND SurveyProductCategory = ''Assessment'');


SELECT SCOPE_IDENTITY();', NULL, NULL, '1594', 'NULL', 'NULL', 'NULL', 'NULL'),
(15, NULL, 'Procedure3', '2024-09-20 12:44:32.753000', '2024-09-20 12:44:54.100000', NULL, 'InProgress', 'no error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''sap basis179'', ''Evaluation assessment using knowledge performing assessment in Assessment for sap basis179'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''sap basis179'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, NULL, '1595', 'NULL', 'NULL', 'NULL', 'NULL'),
(16, NULL, 'Procedure3', '2024-09-20 12:44:32.753000', '2024-09-20 12:45:03.493000', NULL, 'InProgress', 'name ''SurveyID'' is not defined', '2', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''sap basis179'', ''Evaluation assessment using knowledge performing assessment in Assessment for sap basis179'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''sap basis179'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, NULL, '1595', 'NULL', 'NULL', 'NULL', 'NULL'),
(17, NULL, 'Procedure3', '2024-09-20 14:32:24.073000', '2024-09-20 14:32:59.187000', NULL, 'InProgress', 'name ''step3_sql_command'' is not defined', '2', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''sap basis180'', ''Evaluation assessment using knowledge performing assessment in Assessment for sap basis180'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''sap basis180'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, '4', '1', 'NULL', 'NULL', 'NULL', 'NULL'),
(18, NULL, 'Procedure3', '2024-09-20 14:41:04.150000', '2024-09-20 14:41:41.037000', NULL, 'InProgress', 'name ''step3_sql_command'' is not defined', '2', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''sap basis182'', ''Evaluation of knowledge and performance in sap basis182 with respect to Assessment'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''sap basis182'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, '4', '1', 'NULL', 'NULL', 'NULL', 'NULL'),
(19, NULL, 'Procedure3', '2024-09-20 14:48:33.323000', '2024-09-20 14:48:55.197000', NULL, 'InProgress', 'no error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''sap basis185'', ''Evaluation assessment using knowledge performing assessment in Assessment for sap basis185'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''sap basis185'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, NULL, '1601', 'NULL', 'NULL', 'NULL', 'NULL'),
(20, NULL, 'Procedure3', '2024-09-20 14:48:33.323000', '2024-09-20 14:49:06.463000', NULL, 'InProgress', 'name ''SurveyID'' is not defined', '2', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''sap basis185'', ''Evaluation assessment using knowledge performing assessment in Assessment for sap basis185'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''sap basis185'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, NULL, '1601', 'NULL', 'NULL', 'NULL', 'NULL'),
(21, NULL, 'Procedure3', '2024-09-20 14:51:59.540000', '2024-09-20 14:52:20.460000', NULL, 'InProgress', 'no error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''sap basis186'', ''Evaluation assessment using knowledge performing assessment in Assessment for sap basis186'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''sap basis186'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, NULL, '1602', 'NULL', 'NULL', 'NULL', 'NULL'),
(22, NULL, 'Procedure3', '2024-09-20 14:51:59.540000', '2024-09-20 14:52:30.037000', NULL, 'InProgress', 'name ''SurveyID'' is not defined', '2', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''sap basis186'', ''Evaluation assessment using knowledge performing assessment in Assessment for sap basis186'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''sap basis186'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, NULL, '1602', 'NULL', 'NULL', 'NULL', 'NULL'),
(23, NULL, 'Procedure3', '2024-09-20 15:09:24.483000', '2024-09-20 15:09:44.893000', NULL, 'InProgress', 'no error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''sap basis188'', ''Evaluation assessment using knowledge performing assessment in Assessment for sap basis188'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''sap basis188'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, NULL, '1604', 'NULL', 'NULL', 'NULL', 'NULL'),
(24, NULL, 'Procedure3', '2024-09-20 15:09:24.483000', '2024-09-20 15:09:54.727000', NULL, 'InProgress', 'name ''SurveyID'' is not defined', '2', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''sap basis188'', ''Evaluation assessment using knowledge performing assessment in Assessment for sap basis188'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''sap basis188'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, NULL, '1604', 'NULL', 'NULL', 'NULL', 'NULL'),
(25, NULL, 'Procedure3', '2024-09-20 15:23:38.820000', '2024-09-20 15:24:00.580000', NULL, 'InProgress', 'no error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''sap basis190'', ''Evaluation assessment using knowledge performing assessment in Assessment for sap basis190'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''sap basis190'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, NULL, '1606', 'NULL', 'NULL', 'NULL', 'NULL'),
(26, NULL, 'Procedure3', '2024-09-20 15:23:38.820000', '2024-09-20 15:24:10.797000', NULL, 'InProgress', 'name ''SurveyID'' is not defined', '2', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''sap basis190'', ''Evaluation assessment using knowledge performing assessment in Assessment for sap basis190'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''sap basis190'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, NULL, '1606', 'NULL', 'NULL', 'NULL', 'NULL'),
(27, NULL, 'Procedure3', '2024-09-20 15:39:08.207000', '2024-09-20 15:39:31.207000', NULL, 'InProgress', 'no error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''sap basis195'', ''Evaluation of knowledge and performance in Assessment for sap basis195'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''sap basis195'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, NULL, '1611', 'NULL', 'NULL', 'NULL', 'NULL'),
(28, NULL, 'Procedure3', '2024-09-20 15:39:08.207000', '2024-09-20 15:39:41.827000', NULL, 'InProgress', 'name ''SurveyID'' is not defined', '2', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''sap basis195'', ''Evaluation of knowledge and performance in Assessment for sap basis195'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''sap basis195'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, NULL, '1611', 'NULL', 'NULL', 'NULL', 'NULL'),
(33, NULL, 'Procedure3', '2024-09-20 16:10:19.183000', '2024-09-20 16:10:34.660000', NULL, 'Started', 'no error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'',
       ''sap basis200'',
       ''Evaluation of knowledge and performance in sap basis200 with respect to Assessment'',
  (SELECT MAX(SurveyProductSort) + 1
   FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS
    (SELECT 1
     FROM [dbo].[SurveyGroup]
     WHERE SurveyProductName = ''sap basis200''
       AND SurveyProductCategory = ''Assessment'');


SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1616', 'NULL', 'NULL', 'NULL', 'NULL'),
(34, NULL, 'Procedure3', '2024-09-20 16:54:30.053000', '2024-09-20 16:54:46.683000', NULL, 'Started', 'no error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'',
       ''sap basis202'',
       ''Evaluation of knowledge and performance in sap basis202 with respect to Assessment'',
  (SELECT MAX(SurveyProductSort) + 1
   FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS
    (SELECT 1
     FROM [dbo].[SurveyGroup]
     WHERE SurveyProductName = ''sap basis202''
       AND SurveyProductCategory = ''Assessment'');


SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1618', 'NULL', 'NULL', 'NULL', 'NULL'),
(35, NULL, 'Procedure3', '2024-09-20 16:54:30.053000', '2024-09-20 16:55:02.030000', NULL, 'Started', 'no error', '2', NULL, 'INSERT INTO [dbo].[Survey] ([SurveyProductID], [SurveyCategory], [SurveyName], [SurveyDesc], [SurveyLastUpdated], [SurveyStartDate], [SurveyEndDate], [SurveySalesYearDate], [SurveyNextResetRunningWindowInDays], [SurveyIsLockedForSeason], [SurveyGroup1], [SurveyGroup2], [SurveyGroup3], [SurveyGenratedByAI], [SurveyAIVerifiedByHuman], [SurveyApprovedByUserID], [SurveyRequestByUserID])
SELECT 1618,
       ''Assessment'',
       ''sap basis202 - sap basis advanced'',
       ''This assessment evaluates the maturity of an organizations sap basis202 program. It consists of ${NumberOfQ} questions that aim to guide the organization on its next steps towards improving its sap basis202 practices.'',
       GETDATE(),
       GETDATE(),
       ''12-31-9999'',
       GETDATE(),
       30,
       1,
       NULL,
       NULL,
       NULL,
       1,
       0,
       NULL,
       NULL
WHERE NOT EXISTS
    (SELECT 1
     FROM [dbo].[Survey]
     WHERE [SurveyName] = ''sap basis202 - sap basis advanced'')', NULL, '470', '1618', 'NULL', 'NULL', 'NULL', 'NULL'),
(36, NULL, 'Procedure3', '2024-09-20 16:59:16.397000', '2024-09-20 16:59:38.923000', NULL, 'InProgress', 'no error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''sap basis203'', ''Evaluation of knowledge and performance in Assessment for sap basis203'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''sap basis203'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, NULL, '1619', 'NULL', 'NULL', 'NULL', 'NULL'),
(37, NULL, 'Procedure3', '2024-09-20 16:59:16.397000', '2024-09-20 16:59:53.473000', NULL, 'InProgress', 'name ''step3_sql_command'' is not defined', '2', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''sap basis203'', ''Evaluation of knowledge and performance in Assessment for sap basis203'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''sap basis203'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, '471', '1619', 'NULL', 'NULL', 'NULL', 'NULL'),
(38, NULL, 'Procedure3', '2024-09-20 17:28:06.713000', '2024-09-20 17:28:23.153000', NULL, 'Started', 'no error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'',
       ''sap basis204'',
       ''Evaluation of knowledge and performance in sap basis204 for Assessment'',
  (SELECT MAX(SurveyProductSort) + 1
   FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS
    (SELECT 1
     FROM [dbo].[SurveyGroup]
     WHERE SurveyProductName = ''sap basis204''
       AND SurveyProductCategory = ''Assessment'');


SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1620', 'NULL', 'NULL', 'NULL', 'NULL'),
(39, NULL, 'Procedure3', '2024-09-20 17:28:06.713000', '2024-09-20 17:28:39.747000', NULL, 'Started', 'no error', '2', NULL, 'INSERT INTO [dbo].[Survey] ([SurveyProductID], [SurveyCategory], [SurveyName], [SurveyDesc], [SurveyLastUpdated], [SurveyStartDate], [SurveyEndDate], [SurveySalesYearDate], [SurveyNextResetRunningWindowInDays], [SurveyIsLockedForSeason], [SurveyGenratedByAI], [SurveyAIVerifiedByHuman], [SurveyApprovedByUserID], [SurveyRequestByUserID])
SELECT 1620,
       ''Assessment'',
       ''sap basis204 - sap basis advanced'',
       ''This assessment evaluates the maturity of an organizations sap basis204 program. It consists of ${NumberOfQ} questions that aim to guide the organization on its next steps towards improving its sap basis204 practices.'',
       GETDATE(),
       GETDATE(),
       ''12-31-9999'',
       GETDATE(),
       30,
       1,
       1,
       0,
       NULL,
       NULL
WHERE NOT EXISTS
    (SELECT 1
     FROM [dbo].[Survey]
     WHERE [SurveyName] = ''sap basis204 - sap basis advanced'')', NULL, '472', '1620', 'NULL', 'NULL', 'NULL', 'NULL'),
(40, NULL, 'Procedure3', '2024-09-20 18:15:34.303000', '2024-09-20 18:15:45.120000', NULL, 'Started', 'no error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'',
       ''sap basis205'',
       ''Evaluation of knowledge and performance in sap basis205 for Assessment'',
  (SELECT MAX(SurveyProductSort) + 1
   FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS
    (SELECT 1
     FROM [dbo].[SurveyGroup]
     WHERE SurveyProductName = ''sap basis205''
       AND SurveyProductCategory = ''Assessment'');


SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1621', 'NULL', 'NULL', 'NULL', 'NULL'),
(41, NULL, 'Procedure3', '2024-09-20 18:15:34.303000', '2024-09-20 18:15:55.143000', NULL, 'Started', 'no error', '2', NULL, 'INSERT INTO [dbo].[Survey] ([SurveyProductID], [SurveyCategory], [SurveyName], [SurveyDesc], [SurveyLastUpdated], [SurveyStartDate], [SurveyEndDate], [SurveySalesYearDate], [SurveyNextResetRunningWindowInDays], [SurveyIsLockedForSeason], [SurveyGroup1], [SurveyGroup2], [SurveyGroup3], [SurveyGenratedByAI], [SurveyAIVerifiedByHuman], [SurveyApprovedByUserID], [SurveyRequestByUserID])
SELECT 1621,
       ''Assessment'',
       ''sap basis205 - sap basis advanced'',
       ''This assessment evaluates the maturity of an organizations sap basis205 program. It consists of ${NumberOfQ} questions that aim to guide the organization on its next steps towards improving its sap basis205 practices.'',
       GETDATE(),
       GETDATE(),
       ''12-31-9999'',
       GETDATE(),
       30,
       1,
       NULL,
       NULL,
       NULL,
       1,
       0,
       NULL,
       NULL
WHERE NOT EXISTS
    (SELECT 1
     FROM [dbo].[Survey]
     WHERE [SurveyName] = ''sap basis205 - sap basis advanced'')', NULL, '473', '1621', 'NULL', 'NULL', 'NULL', 'NULL'),
(42, NULL, 'Procedure3', '2024-09-20 18:15:34.303000', '2024-09-20 18:16:02.150000', NULL, 'Started', 'no error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'',
       ''sap basis206'',
       ''Evaluation of knowledge and performance in sap basis206 with respect to Assessment'',
  (SELECT MAX(SurveyProductSort) + 1
   FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS
    (SELECT 1
     FROM [dbo].[SurveyGroup]
     WHERE SurveyProductName = ''sap basis206''
       AND SurveyProductCategory = ''Assessment'');


SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1622', 'NULL', 'NULL', 'NULL', 'NULL'),
(44, NULL, 'Procedure3', '2024-09-20 18:20:41.493000', '2024-09-20 18:20:54.887000', NULL, 'InProgress', 'no error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''sap basis207'', ''Evaluation of knowledge and performance in sap basis207 with respect to Assessment'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''sap basis207'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1623', 'NULL', 'NULL', 'NULL', 'NULL'),
(46, NULL, 'Procedure3', '2024-09-20 18:20:41.493000', '2024-09-20 18:21:02.883000', NULL, 'InProgress', 'name ''step3_sql_command'' is not defined', '2', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''sap basis207'', ''Evaluation of knowledge and performance in sap basis207 with respect to Assessment'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''sap basis207'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, '474', '1623', 'NULL', 'NULL', 'NULL', 'NULL'),
(47, NULL, 'Procedure3', '2024-09-20 18:24:27.703000', '2024-09-20 18:24:38.227000', NULL, 'Started', 'no error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'',
       ''sap basis208'',
       ''Evaluation assessment using knowledge performing assessment in Assessment for sap basis208'',
  (SELECT MAX(SurveyProductSort) + 1
   FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS
    (SELECT 1
     FROM [dbo].[SurveyGroup]
     WHERE SurveyProductName = ''sap basis208''
       AND SurveyProductCategory = ''Assessment'');


SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1624', 'NULL', 'NULL', 'NULL', 'NULL'),
(50, NULL, 'Procedure3', '2024-09-20 18:26:30.167000', '2024-09-20 18:26:40.663000', NULL, 'Started', 'no error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'',
       ''sap basis209'',
       ''Evaluation of knowledge and performance in sap basis209 with respect to Assessment'',
  (SELECT MAX(SurveyProductSort) + 1
   FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS
    (SELECT 1
     FROM [dbo].[SurveyGroup]
     WHERE SurveyProductName = ''sap basis209''
       AND SurveyProductCategory = ''Assessment'');


SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1625', 'NULL', 'NULL', 'NULL', 'NULL'),
(54, NULL, 'Procedure3', '2024-09-20 18:44:46.950000', '2024-09-20 18:44:57.877000', NULL, 'Started', 'no error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'',
       ''sap basis212'',
       ''Evaluation of knowledge and performance in sap basis212 for Assessment'',
  (SELECT MAX(SurveyProductSort) + 1
   FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS
    (SELECT 1
     FROM [dbo].[SurveyGroup]
     WHERE SurveyProductName = ''sap basis212''
       AND SurveyProductCategory = ''Assessment'');


SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1628', 'NULL', 'NULL', 'NULL', 'NULL'),
(56, NULL, 'Procedure3', '2024-09-23 11:15:50.493000', '2024-09-23 11:16:06.787000', NULL, 'Started', 'no error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'',
       ''sap basis214'',
       ''Evaluation assessment using knowledge performing assessment in Assessment for sap basis214'',
  (SELECT MAX(SurveyProductSort) + 1
   FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS
    (SELECT 1
     FROM [dbo].[SurveyGroup]
     WHERE SurveyProductName = ''sap basis214''
       AND SurveyProductCategory = ''Assessment'');


SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1630', 'NULL', 'NULL', 'NULL', 'NULL'),
(57, NULL, 'Procedure3', '2024-09-23 11:15:50.493000', '2024-09-23 11:16:21.747000', NULL, 'Started', 'no error', '2', NULL, 'INSERT INTO [dbo].[Survey] ([SurveyProductID], [SurveyCategory], [SurveyName], [SurveyDesc], [SurveyLastUpdated], [SurveyStartDate], [SurveyEndDate], [SurveySalesYearDate], [SurveyNextResetRunningWindowInDays], [SurveyIsLockedForSeason], [SurveyGroup1], [SurveyGroup2], [SurveyGroup3], [SurveyGenratedByAI], [SurveyAIVerifiedByHuman], [SurveyApprovedByUserID], [SurveyRequestByUserID])
SELECT 1630,
       ''Assessment'',
       ''sap basis214 - sap basis advanced'',
       ''This assessment evaluates the maturity of an organizations sap basis214 program. It consists of ${NumberOfQ} questions that aim to guide the organization on its next steps towards improving its sap basis214 practices.'',
       GETDATE(),
       GETDATE(),
       ''12-31-9999'',
       GETDATE(),
       30,
       1,
       NULL,
       NULL,
       NULL,
       1,
       0,
       NULL,
       NULL
WHERE NOT EXISTS
    (SELECT 1
     FROM [dbo].[Survey]
     WHERE [SurveyName] = ''sap basis214 - sap basis advanced'')', NULL, '476', '1630', 'NULL', 'NULL', 'NULL', 'NULL'),
(58, NULL, 'Procedure3', '2024-09-23 11:17:17.690000', '2024-09-23 11:17:33.210000', NULL, 'Started', 'no error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'',
       ''sap basis215'',
       ''Evaluation assessment using knowledge performing assessment in Assessment for sap basis215'',
  (SELECT MAX(SurveyProductSort) + 1
   FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS
    (SELECT 1
     FROM [dbo].[SurveyGroup]
     WHERE SurveyProductName = ''sap basis215''
       AND SurveyProductCategory = ''Assessment'');


SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1631', 'NULL', 'NULL', 'NULL', 'NULL'),
(59, NULL, 'Procedure3', '2024-09-23 11:21:13.483000', '2024-09-23 11:21:29.767000', NULL, 'Started', 'no error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'',
       ''sap basis216'',
       ''Evaluation assessment using knowledge performing assessment in Assessment for sap basis216'',
  (SELECT MAX(SurveyProductSort) + 1
   FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS
    (SELECT 1
     FROM [dbo].[SurveyGroup]
     WHERE SurveyProductName = ''sap basis216''
       AND SurveyProductCategory = ''Assessment'');


SELECT SCOPE_IDENTITY();', NULL, NULL, '1632', 'NULL', 'NULL', 'NULL', 'NULL'),
(60, NULL, 'Procedure3', '2024-09-23 11:30:15.770000', '2024-09-23 11:30:39.997000', NULL, 'Started', 'no error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'',
       ''sap basis218'',
       ''Evaluation assessment using knowledge performing assessment in Assessment for sap basis218'',
  (SELECT MAX(SurveyProductSort) + 1
   FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS
    (SELECT 1
     FROM [dbo].[SurveyGroup]
     WHERE SurveyProductName = ''sap basis218''
       AND SurveyProductCategory = ''Assessment'');


SELECT SCOPE_IDENTITY();', NULL, NULL, '1634', 'NULL', 'NULL', 'NULL', 'NULL'),
(61, NULL, 'Procedure3', '2024-09-23 11:31:49.800000', '2024-09-23 11:32:13.857000', NULL, 'Started', 'no error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'',
       ''sap abap1'',
       ''Evaluation assessment using knowledge performing assessment in Assessment for sap abap1'',
  (SELECT MAX(SurveyProductSort) + 1
   FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS
    (SELECT 1
     FROM [dbo].[SurveyGroup]
     WHERE SurveyProductName = ''sap abap1''
       AND SurveyProductCategory = ''Assessment'');


SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1635', 'NULL', 'NULL', 'NULL', 'NULL'),
(62, NULL, 'Procedure3', '2024-09-23 11:35:14.467000', '2024-09-23 11:35:46.737000', NULL, 'Started', 'no error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'',
       ''sap abap2'',
       ''Evaluation of knowledge and performance in sap abap2 with respect to Assessment'',
  (SELECT MAX(SurveyProductSort) + 1
   FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS
    (SELECT 1
     FROM [dbo].[SurveyGroup]
     WHERE SurveyProductName = ''sap abap2''
       AND SurveyProductCategory = ''Assessment'');


SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1636', 'NULL', 'NULL', 'NULL', 'NULL'),
(63, NULL, 'Procedure3', '2024-09-23 11:38:19.500000', '2024-09-23 11:38:37.197000', NULL, 'Started', 'no error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'',
       ''sap abap3'',
       ''Evaluation assessment using knowledge performing assessment in Assessment for sap abap3'',
  (SELECT MAX(SurveyProductSort) + 1
   FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS
    (SELECT 1
     FROM [dbo].[SurveyGroup]
     WHERE SurveyProductName = ''sap abap3''
       AND SurveyProductCategory = ''Assessment'');


SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1637', 'NULL', 'NULL', 'NULL', 'NULL'),
(64, NULL, 'Procedure3', '2024-09-23 11:40:37.247000', '2024-09-23 11:40:51.877000', NULL, 'Started', 'no error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'',
       ''sap abap4'',
       ''Evaluation of knowledge and performance in sap abap4 with respect to Assessment'',
  (SELECT MAX(SurveyProductSort) + 1
   FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS
    (SELECT 1
     FROM [dbo].[SurveyGroup]
     WHERE SurveyProductName = ''sap abap4''
       AND SurveyProductCategory = ''Assessment'');


SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1638', 'NULL', 'NULL', 'NULL', 'NULL'),
(65, NULL, 'Procedure3', '2024-09-23 11:40:37.247000', '2024-09-23 11:41:08.190000', NULL, 'Started', 'no error', '2', NULL, 'INSERT INTO [dbo].[Survey] ([SurveyProductID], [SurveyCategory], [SurveyName], [SurveyDesc], [SurveyLastUpdated], [SurveyStartDate], [SurveyEndDate], [SurveySalesYearDate], [SurveyNextResetRunningWindowInDays], [SurveyIsLockedForSeason], [SurveyGroup1], [SurveyGroup2], [SurveyGroup3], [SurveyGenratedByAI], [SurveyAIVerifiedByHuman], [SurveyApprovedByUserID], [SurveyRequestByUserID])
SELECT 1638,
       ''Assessment'',
       ''sap abap4 - sap abap advanced'',
       ''This assessment evaluates the maturity of an organizations sap abap4 program. It consists of ${NumberOfQ} questions that aim to guide the organization on its next steps towards improving its sap abap4 practices.'',
       GETDATE(),
       GETDATE(),
       ''12-31-9999'',
       GETDATE(),
       30,
       1,
       NULL,
       NULL,
       NULL,
       1,
       0,
       NULL,
       NULL
WHERE NOT EXISTS
    (SELECT 1
     FROM [dbo].[Survey]
     WHERE [SurveyName] = ''sap abap4 - sap abap advanced'')', NULL, '477', '1638', 'NULL', 'NULL', 'NULL', 'NULL'),
(66, NULL, 'Procedure3', '2024-09-23 12:03:04.617000', '2024-09-23 12:03:21.027000', NULL, 'Started', 'no error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'',
       ''sap abap8'',
       ''Evaluation of knowledge and performance in sap abap8 with respect to Assessment'',
  (SELECT MAX(SurveyProductSort) + 1
   FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS
    (SELECT 1
     FROM [dbo].[SurveyGroup]
     WHERE SurveyProductName = ''sap abap8''
       AND SurveyProductCategory = ''Assessment'');


SELECT SCOPE_IDENTITY();', NULL, '[(None,)]', '[(1642,)]', 'NULL', 'NULL', 'NULL', 'NULL'),
(67, NULL, 'Procedure3', '2024-09-23 12:03:04.617000', '2024-09-23 12:03:26.067000', NULL, 'InProgress', 'no error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''sap abap8'', ''Evaluation of knowledge and performance in sap abap8 with respect to Assessment'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''sap abap8'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1642', 'NULL', 'NULL', 'NULL', 'NULL'),
(68, NULL, 'Procedure3', '2024-09-23 12:03:04.617000', '2024-09-23 12:03:36.807000', NULL, 'InProgress', 'name ''SurveyID'' is not defined', '2', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''sap abap8'', ''Evaluation of knowledge and performance in sap abap8 with respect to Assessment'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''sap abap8'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1642', 'NULL', 'NULL', 'NULL', 'NULL'),
(69, NULL, 'Procedure3', '2024-09-23 15:32:13.810000', '2024-09-23 15:32:24.903000', NULL, 'InProgress', 'name ''SurveyID'' is not defined', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''sap sol mgr03'', ''Evaluation assessment using knowledge performing assessment in Assessment for sap solution manager03'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''sap sol mgr03'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL'),
(70, NULL, 'Procedure3', '2024-09-23 15:33:28.407000', '2024-09-23 15:33:39.610000', NULL, 'InProgress', 'name ''SurveyID'' is not defined', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''sap sol man99'', ''Evaluation assessment using knowledge performing assessment in Assessment for sap solution manager99'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''sap sol man99'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL'),
(71, NULL, 'Procedure3', '2024-09-23 15:44:26.900000', '2024-09-23 15:44:37.833000', NULL, 'InProgress', 'name ''SurveyID'' is not defined', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''sap sol man101'', ''Evaluation assessment using knowledge performing assessment in Assessment for sap sol man101'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''sap sol man101'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL'),
(72, NULL, 'Procedure3', '2024-09-23 15:55:32.393000', '2024-09-23 15:55:44.137000', NULL, 'InProgress', 'name ''SurveyID'' is not defined', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP SM104'', ''Evaluation of knowledge and performance in Assessment for SAP SM104'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP SM104'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL'),
(73, NULL, 'Procedure3', '2024-09-23 16:20:50.780000', '2024-09-23 16:21:07.583000', NULL, 'InProgress', 'name ''SurveyID'' is not defined', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM13'', ''Evaluation of knowledge and performance in Assessment for SAP MM13'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM13'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL'),
(74, NULL, 'Procedure3', '2024-09-23 16:32:16.307000', '2024-09-23 16:32:33.040000', NULL, 'InProgress', 'name ''SurveyProductID'' is not defined', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM14'', ''Evaluation of knowledge and performance in Assessment for SAP MM14'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM14'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL'),
(75, NULL, 'Procedure3', '2024-09-23 16:38:11.063000', '2024-09-23 16:38:27.987000', NULL, 'InProgress', 'name ''SurveyProductID'' is not defined', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM15'', ''Evaluation of knowledge and performance in SAP MM15 for Assessment'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM15'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL'),
(76, NULL, 'Procedure3', '2024-09-23 17:10:39.880000', '2024-09-23 17:10:56.867000', NULL, 'In-progess', 'No error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM18'', ''Evaluation of knowledge and performance in SAP MM18 assessment'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM18'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1657', 'NULL', 'NULL', 'NULL', 'NULL'),
(77, NULL, 'Procedure3', '2024-09-23 17:14:41.783000', '2024-09-23 17:14:58.347000', NULL, 'In-progess', 'No error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM19'', ''Evaluation of knowledge and performance in SAP MM19 assessment'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM19'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1658', 'NULL', 'NULL', 'NULL', 'NULL'),
(78, NULL, 'Procedure3', '2024-09-23 17:18:39.580000', '2024-09-23 17:19:03.070000', NULL, 'In-progess', 'No error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM20'', ''Evaluation of knowledge and performance in SAP MM20 assessment'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM20'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1659', 'NULL', 'NULL', 'NULL', 'NULL'),
(79, NULL, 'Procedure3', '2024-09-23 17:20:09.560000', '2024-09-23 17:20:29.093000', NULL, 'In-progess', 'No error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM21'', ''Evaluation of knowledge and performance in SAP MM21 assessment'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM21'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1660', 'NULL', 'NULL', 'NULL', 'NULL'),
(80, NULL, 'Procedure3', '2024-09-23 17:20:09.560000', '2024-09-23 17:20:47.173000', NULL, 'InProgress', 'no error', '2', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM21'', ''Evaluation of knowledge and performance in SAP MM21 assessment'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM21'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, '485', '1660', 'NULL', 'NULL', 'NULL', 'NULL'),
(81, NULL, 'Procedure3', '2024-09-23 17:24:18.510000', '2024-09-23 17:24:39.153000', NULL, 'In-progess', 'No error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM22'', ''Evaluation of knowledge and performance in SAP MM22 assessment'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM22'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1661', 'NULL', 'NULL', 'NULL', 'NULL'),
(82, NULL, 'Procedure3', '2024-09-23 17:24:18.510000', '2024-09-23 17:24:56.153000', NULL, 'InProgress', 'no error', '2', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM22'', ''Evaluation of knowledge and performance in SAP MM22 assessment'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM22'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, '486', '1661', 'NULL', 'NULL', 'NULL', 'NULL'),
(83, NULL, 'Procedure3', '2024-09-23 17:26:37.620000', '2024-09-23 17:26:55.347000', NULL, 'In-progess', 'No error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM23'', ''Evaluation of knowledge and performance in Assessment for SAP MM23'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM23'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1662', 'NULL', 'NULL', 'NULL', 'NULL'),
(84, NULL, 'Procedure3', '2024-09-23 17:28:34.527000', '2024-09-23 17:28:52.287000', NULL, 'In-progess', 'No error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM24'', ''Evaluation of knowledge and performance in SAP MM24 assessment'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM24'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1663', 'NULL', 'NULL', 'NULL', 'NULL'),
(85, NULL, 'Procedure3', '2024-09-23 17:28:34.527000', '2024-09-23 17:29:06.610000', NULL, 'InProgress', 'name ''SurveyID'' is not defined', '2', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM24'', ''Evaluation of knowledge and performance in SAP MM24 assessment'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM24'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1663', 'NULL', 'NULL', 'NULL', 'NULL'),
(86, NULL, 'Procedure3', '2024-09-23 17:30:10.340000', '2024-09-23 17:30:29.220000', NULL, 'In-progess', 'No error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM25'', ''Evaluation of knowledge and performance in SAP MM25'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM25'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1664', 'NULL', 'NULL', 'NULL', 'NULL'),
(87, NULL, 'Procedure3', '2024-09-23 17:30:10.340000', '2024-09-23 17:30:47.233000', NULL, 'InProgress', 'no error', '2', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM25'', ''Evaluation of knowledge and performance in SAP MM25'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM25'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, '487', '1664', 'NULL', 'NULL', 'NULL', 'NULL'),
(88, NULL, 'Procedure3', '2024-09-23 17:37:08.367000', '2024-09-23 17:37:29.070000', NULL, 'In-progess', 'No error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM26'', ''Evaluation of knowledge and performance in Assessment for SAP MM26'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM26'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1665', 'NULL', 'NULL', 'NULL', 'NULL'),
(89, NULL, 'Procedure3', '2024-09-23 17:37:08.367000', '2024-09-23 17:37:48.027000', NULL, 'InProgress', 'no error', '2', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM26'', ''Evaluation of knowledge and performance in Assessment for SAP MM26'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM26'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, '488', '1665', 'NULL', 'NULL', 'NULL', 'NULL'),
(90, NULL, 'Procedure3', '2024-09-23 17:41:33.913000', '2024-09-23 17:41:52.177000', NULL, 'In-progess', 'No error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM27'', ''Evaluation of knowledge and performance in SAP MM27 assessment'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM27'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1666', 'NULL', 'NULL', 'NULL', 'NULL'),
(91, NULL, 'Procedure3', '2024-09-23 17:41:33.913000', '2024-09-23 17:42:08.143000', NULL, 'InProgress', 'no error', '2', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM27'', ''Evaluation of knowledge and performance in SAP MM27 assessment'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM27'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, '489', '1666', 'NULL', 'NULL', 'NULL', 'NULL'),
(92, NULL, 'Procedure3', '2024-09-23 17:47:50.907000', '2024-09-23 17:48:07.853000', NULL, 'In-progess', 'No error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM28'', ''Evaluation of knowledge and performance in SAP MM28 assessment'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM28'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1667', 'NULL', 'NULL', 'NULL', 'NULL'),
(93, NULL, 'Procedure3', '2024-09-23 17:47:50.907000', '2024-09-23 17:48:24.570000', NULL, 'InProgress', 'no error', '2', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM28'', ''Evaluation of knowledge and performance in SAP MM28 assessment'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM28'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, '490', '1667', 'NULL', 'NULL', 'NULL', 'NULL'),
(94, NULL, 'Procedure3', '2024-09-23 17:53:22.997000', '2024-09-23 17:53:39.737000', NULL, 'In-progess', 'No error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM29'', ''Evaluation of knowledge and performance in SAP MM29 assessment'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM29'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1668', 'NULL', 'NULL', 'NULL', 'NULL'),
(95, NULL, 'Procedure3', '2024-09-23 17:53:22.997000', '2024-09-23 17:53:55.300000', NULL, 'InProgress', 'no error', '2', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM29'', ''Evaluation of knowledge and performance in SAP MM29 assessment'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM29'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1668', 'NULL', 'NULL', 'NULL', 'NULL'),
(96, NULL, 'Procedure3', '2024-09-23 17:53:22.997000', '2024-09-23 17:53:55.300000', NULL, 'InProgress', 'No Error', '3', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM29'', ''Evaluation of knowledge and performance in SAP MM29 assessment'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM29'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1668', 'INSERT INTO [dbo].[Question] ([QuestionSurveyID], [QuestionText], [QuestionShortText], [QuestionGroupText], [QuestionShortAbbrev], [QuestionSort], [QuestionIsMultiMark], [QuestionIsScale], [QuestionIsTopBox], [QuestionIsSkipQuestion], [QuestionSkipToQuestionID], [QuestionGroup1Text], [QuestionGroup2Text], [QuestionGroup3Text], [QuestionGroup4Text], [QuestionGroup5Text], [QuestionChoiceAIGenrated], [QuestionScale])
VALUES 
(1, ''What is SAP MM?'', ''SAP MM'', ''Level 1'', ''SMM'', 1, NULL, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''1-Beginner-I don''''t know what SAP MM is-0-0-0-0-0'', 10),
(1, ''What are the basic features of SAP MM?'', ''SAP MM Features'', ''Level 1'', ''SMMF'', 2, NULL, 20, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''1-Beginner-I don''''t know the basic features of SAP MM-0-0-0-0-0'', 20),
(1, ''How to create a purchase order in SAP MM?'', ''Purchase Order Creation'', ''Level 2'', ''POC'', 3, NULL, 30, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''1-Beginner-I don''''t know how to create a purchase order in SAP MM-2-Basic + on a journey-I have created a few purchase orders-3-Average Skill-I can create purchase orders with ease-4-Lead level-I can create complex purchase orders-5-Expert-I can train others to create purchase orders'', 30),
(1, ''What is the difference between a purchase order and a purchase requisition in SAP MM?'', ''PO vs PR'', ''Level 2'', ''PvP'', 4, NULL, 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''1-Beginner-I don''''t know the difference between a purchase order and a purchase requisition in SAP MM-2-Basic + on a journey-I have heard of both but not sure about the difference-3-Average Skill-I know the basic difference-4-Lead level-I can explain the difference in detail-5-Expert-I can train others on the difference'', 40),
(1, ''How to create a material master record in SAP MM?'', ''Material Master Creation'', ''Level 3'', ''MMC'', 5, NULL, 50, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''1-Beginner-I don''''t know how to create a material master record in SAP MM-2-Basic + on a journey-I have created a few material master records-3-Average Skill-I can create material master records with ease-4-Lead level-I can create complex material master records-5-Expert-I can train others to create material master records'', 50),
(1, ''What is the process of goods receipt in SAP MM?'', ''Goods Receipt Process'', ''Level 3'', ''GRP'', 6, NULL, 60, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''1-Beginner-I don''''t know the process of goods receipt in SAP MM-2-Basic + on a journey-I have heard of goods receipt but not sure about the process-3-Average Skill-I know the basic process-4-Lead level-I can explain the process in detail-5-Expert-I can train others on the process'', 60),
(1, ''How to create a source list in SAP MM?'', ''Source List Creation'', ''Level 4'', ''SLC'', 7, NULL, 70, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''1-Beginner-I don''''t know how to create a source list in SAP MM-2-Basic + on a journey-I have created a few source lists-3-Average Skill-I can create source lists with ease-4-Lead level-I can create complex source lists-5-Expert-I can train others to create source lists'', 70),
(1, ''What is the process of invoice verification in SAP MM?'', ''Invoice Verification Process'', ''Level 4'', ''IVP'', 8, NULL, 80, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''1-Beginner-I don''''t know the process of invoice verification in SAP MM-2-Basic + on a journey-I have heard of invoice verification but not sure about the process-3-Average Skill-I know the basic process-4-Lead level-I can explain the process in detail-5-Expert-I can train others on the process'', 80),
(1, ''How to create a custom report in SAP MM?'', ''Custom Report Creation'', ''Level 4'', ''CRC'', 9, NULL, 90, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''1-Beginner-I don''''t know how to create a custom report in SAP MM-2-Basic + on a journey-I have created a few custom reports-3-Average Skill-I can create custom reports with ease-4-Lead level-I can create complex custom reports-5-Expert-I can train others to create custom reports'', 90),
(1, ''What is the process of inventory management in SAP MM?'', ''Inventory Management Process'', ''Level 5'', ''IMP'', 10, NULL, 100, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, ''1-Beginner-I don''''t know the process of inventory management in SAP MM-2-Basic + on a journey-I have heard of inventory management but not sure about the process-3-Average Skill-I know the basic process-4-Lead level-I can explain the process in detail-5-Expert-I can train others on the process'', 100)', '([(1668,)], [(None,)], None, None)', 'NULL', 'NULL'),
(97, NULL, 'Procedure3', '2024-09-23 18:33:49.920000', '2024-09-23 18:34:06.010000', NULL, 'In-progess', 'No error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM30'', ''Evaluation of knowledge and performance in SAP MM30 assessment'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM30'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1669', 'NULL', 'NULL', 'NULL', 'NULL'),
(98, NULL, 'Procedure3', '2024-09-23 18:33:49.920000', '2024-09-23 18:34:23.217000', NULL, 'InProgress', 'no error', '2', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM30'', ''Evaluation of knowledge and performance in SAP MM30 assessment'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM30'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, '492', '1669', 'NULL', 'NULL', 'NULL', 'NULL'),
(99, NULL, 'Procedure3', '2024-09-24 10:58:17.667000', '2024-09-24 10:58:43.367000', NULL, 'In-progess', 'No error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM31'', ''Evaluation of knowledge and performance in SAP MM31 assessment'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM31'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1670', 'NULL', 'NULL', 'NULL', 'NULL'),
(100, NULL, 'Procedure3', '2024-09-24 10:58:17.667000', '2024-09-24 10:58:55.797000', NULL, 'InProgress', 'name ''SurveyID'' is not defined', '2', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM31'', ''Evaluation of knowledge and performance in SAP MM31 assessment'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM31'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1670', 'NULL', 'NULL', 'NULL', 'NULL'),
(101, NULL, 'Procedure3', '2024-09-24 11:15:09.343000', '2024-09-24 11:15:24.870000', NULL, 'In-progess', 'No error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM32'', ''Evaluation of knowledge and performance in SAP MM32 assessment'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM32'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1671', 'NULL', 'NULL', 'NULL', 'NULL'),
(102, NULL, 'Procedure3', '2024-09-24 11:15:09.343000', '2024-09-24 11:15:40.233000', NULL, 'InProgress', 'name ''SurveyID'' is not defined', '2', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM32'', ''Evaluation of knowledge and performance in SAP MM32 assessment'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM32'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1671', 'NULL', 'NULL', 'NULL', 'NULL'),
(103, NULL, 'Procedure3', '2024-09-24 11:27:17.207000', '2024-09-24 11:27:33.163000', NULL, 'In-progess', 'No error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM33'', ''Evaluation of knowledge and performance in Assessment for SAP MM33'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM33'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1672', 'NULL', 'NULL', 'NULL', 'NULL'),
(104, NULL, 'Procedure3', '2024-09-24 11:27:17.207000', '2024-09-24 11:27:46.793000', NULL, 'InProgress', 'name ''step3_sql_command'' is not defined', '2', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM33'', ''Evaluation of knowledge and performance in Assessment for SAP MM33'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM33'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1672', 'NULL', 'NULL', 'NULL', 'NULL'),
(105, NULL, 'Procedure3', '2024-09-24 11:58:10.467000', '2024-09-24 11:58:26.850000', NULL, 'In-progess', 'No error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM35'', ''Evaluation of knowledge and performance in SAP MM35 for Assessment'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM35'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1674', NULL, NULL, NULL, NULL),
(106, NULL, 'Procedure3', '2024-09-24 11:58:10.467000', '2024-09-24 11:58:40.163000', NULL, 'InProgress', 'No result returned for Step 2 SQL Command', '2', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM35'', ''Evaluation of knowledge and performance in SAP MM35 for Assessment'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM35'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1674', NULL, NULL, NULL, NULL),
(107, NULL, 'Procedure3', '2024-09-24 12:04:49.287000', '2024-09-24 12:05:05.393000', NULL, 'In-progess', 'No error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM36'', ''Evaluation of knowledge and performance in Assessment for SAP MM36'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM36'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1675', NULL, NULL, NULL, NULL),
(108, NULL, 'Procedure3', '2024-09-24 12:04:49.287000', '2024-09-24 12:05:19.123000', NULL, 'InProgress', 'No result returned for Step 2 SQL Command', '2', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM36'', ''Evaluation of knowledge and performance in Assessment for SAP MM36'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM36'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1675', NULL, NULL, NULL, NULL),
(109, NULL, 'Procedure3', '2024-09-24 12:10:26.067000', '2024-09-24 12:10:43.117000', NULL, 'In-progess', 'No error', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM37'', ''Evaluation of knowledge and performance in Assessment for SAP MM37'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM37'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1676', NULL, NULL, NULL, NULL),
(110, NULL, 'Procedure3', '2024-09-24 12:10:26.067000', '2024-09-24 12:10:55.600000', NULL, 'InProgress', 'No result returned for Step 2 SQL Command', '2', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM37'', ''Evaluation of knowledge and performance in Assessment for SAP MM37'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM37'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', '1676', NULL, NULL, NULL, NULL),
(111, NULL, 'Procedure3', '2024-09-24 12:11:33.283000', '2024-09-24 12:12:20.747000', NULL, 'InProgress', 'name ''SurveyProductID'' is not defined', '1', NULL, 'INSERT INTO [dbo].[SurveyGroup] (SurveyProductCategory, SurveyProductName, SurveyProductDesc, SurveyProductSort, SurveyProductIsOpen)
SELECT ''Assessment'', ''SAP MM38'', ''Evaluation of knowledge and performance in SAP MM38 for Assessment'', (SELECT MAX(SurveyProductSort) + 1 FROM [dbo].[SurveyGroup]), 0
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[SurveyGroup] WHERE SurveyProductName = ''SAP MM38'' AND SurveyProductCategory = ''Assessment'');
SELECT SCOPE_IDENTITY();', NULL, 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL');
