-- Generated by dbmigration. Data for Sandbox.CloudOMax -> livebit_sandbox.cloudomax.
INSERT INTO "livebit_sandbox"."cloudomax" ("id", "name", "created_at") VALUES
(101, 'Sandeep', '2025-11-12 00:00:59.310000'),
(102, 'Vishal', '2025-11-12 00:00:59.310000'),
(103, 'Sonal', '2025-11-12 00:00:59.310000'),
(101, 'Sandeep', '2025-11-12 00:43:26.553000'),
(102, 'Vishal', '2025-11-12 00:43:26.553000'),
(103, 'Sonal', '2025-11-12 00:43:26.553000'),
(101, 'Sandeep', '2025-11-12 00:45:05.947000'),
(102, 'Vishal', '2025-11-12 00:45:05.947000'),
(103, 'Sonal', '2025-11-12 00:45:05.947000');
