-- Generated by dbmigration. Data for divaconfig.PortalTabsConfig -> livebit_divaconfig.portaltabsconfig.
INSERT INTO "livebit_divaconfig"."portaltabsconfig" ("tabid", "basetabname", "tabname", "iseditable", "isvisible", "logo", "primarythemecolor", "secondarythemecolor", "createdby", "createddate", "updatedby", "updateddate", "tabsq") VALUES
(1, 'Dashboard', 'Dashboard', TRUE, TRUE, NULL, NULL, NULL, 'Admin', '2024-12-22 02:37:43.527000', NULL, NULL, NULL),
(2, 'ConfigHub', 'Config Hub', TRUE, TRUE, NULL, NULL, NULL, 'Admin', '2024-12-22 02:37:43.527000', NULL, NULL, NULL),
(3, 'EnvManager', 'Env Manager', TRUE, TRUE, NULL, NULL, NULL, 'Admin', '2024-12-22 02:37:43.527000', NULL, NULL, NULL),
(4, 'DataEditor', 'Data Editor', TRUE, TRUE, NULL, NULL, NULL, 'Admin', '2024-12-22 02:37:43.527000', NULL, NULL, NULL),
(5, 'RawHub', 'Raw Hub', TRUE, TRUE, NULL, NULL, NULL, 'Admin', '2024-12-22 02:37:43.527000', NULL, NULL, NULL),
(6, 'EnrichmentHub', 'Enrichment Hub', TRUE, TRUE, NULL, NULL, NULL, 'Admin', '2024-12-22 02:37:43.527000', NULL, NULL, NULL),
(7, 'GoldHub', 'Gold Hub', TRUE, TRUE, NULL, NULL, NULL, 'Admin', '2024-12-22 02:37:43.527000', NULL, NULL, NULL),
(8, 'AnalyticsHub', 'Analytics Hub', TRUE, TRUE, NULL, NULL, NULL, 'Admin', '2024-12-22 02:37:43.527000', NULL, NULL, NULL),
(9, 'QAFramework', 'QA Framework', TRUE, TRUE, NULL, NULL, NULL, 'Admin', '2024-12-22 02:37:43.527000', NULL, NULL, NULL),
(10, 'SyncMonitor', 'Sync Monitor', TRUE, TRUE, NULL, NULL, NULL, 'Admin', '2024-12-22 02:37:43.527000', NULL, NULL, NULL),
(11, 'AuditLogger', 'Audit Logger', TRUE, TRUE, NULL, NULL, NULL, 'Admin', '2024-12-22 02:37:43.527000', NULL, NULL, NULL),
(12, 'UserManager', 'User Manager', TRUE, TRUE, NULL, NULL, NULL, 'Admin', '2024-12-22 02:37:43.527000', NULL, NULL, NULL),
(13, 'Admin', 'Admin 0828', TRUE, TRUE, NULL, NULL, NULL, 'Admin', '2024-12-22 02:37:43', NULL, '2025-08-19 13:54:10', NULL),
(14, 'MasterData', 'Master Data', TRUE, TRUE, NULL, NULL, NULL, 'Admin', '2024-12-22 02:37:43.527000', NULL, NULL, NULL),
(15, 'DIVA Hub', 'DIVA Hub', TRUE, TRUE, NULL, NULL, NULL, 'Admin', '2025-02-07 06:06:08.280000', NULL, NULL, NULL);
