-- Generated by dbmigration. Data for divaconfig.UserRoles -> livebit_divaconfig.userroles.
INSERT INTO "livebit_divaconfig"."userroles" ("userroleid", "userid", "roleid", "assigneddate", "isactive") VALUES
(1, 1, 1, '2025-01-10 04:49:45.013000', TRUE),
(2, 2, 1, '2025-01-10 04:49:45.013000', TRUE),
(3, 3, 1, '2025-01-10 04:49:45.013000', TRUE),
(4, 4, 1, '2025-01-10 04:49:45.013000', TRUE),
(5, 5, 1, '2025-01-10 04:49:45', TRUE);
