-- Generated by dbmigration. Data for zora.shortUrl -> livebit_zora.shorturl.
INSERT INTO "livebit_zora"."shorturl" ("url_id", "company_id", "user_id", "domain_id", "link_id", "alias", "expires_at", "password_hash", "category_suggestions", "fraud_detection", "suggested_aliases", "tags", "is_bookmark", "bookmark_title", "bookmark_description", "created_at", "updated_at") VALUES
(82, NULL, 23, 1, 83, 'diva', '2026-05-02 09:49:40.177000', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-05-02 09:49:40.177000', '2025-05-02 09:49:40.177000'),
(93, NULL, 13, 1, 94, 'ProductID', '2026-05-02 17:07:33.723000', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-05-02 17:07:33.727000', '2025-05-02 17:07:33.727000'),
(94, NULL, 13, 4, 95, 'jhvjvj', '2026-05-02 17:16:07.430000', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-05-02 17:16:07.430000', '2025-05-02 17:16:07.430000'),
(95, NULL, 13, 1, 96, 'IsActive', '2026-05-02 17:19:45.593000', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-05-02 17:19:45.593000', '2025-05-02 17:19:45.593000'),
(96, NULL, 23, 1, 97, 'cira', '2026-05-02 16:48:08.620000', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-05-02 16:48:08.697000', '2025-05-02 16:48:08.697000'),
(104, NULL, 23, 1, 105, 'n8n', '2026-08-04 05:15:48.353000', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-04 05:15:48.413000', '2025-08-04 05:15:48.413000'),
(105, NULL, 23, 1, 106, 'Yfb4vp', '2026-08-06 17:23:37.410000', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-06 17:23:37.467000', '2025-08-06 17:23:37.467000'),
(121, NULL, 1, 1, 122, 'cloudomax-my.sharepoint', '2027-06-22 09:27:38.217000', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-06-22 09:27:38.250000', '2026-06-22 09:27:38.250000');
