-- Generated by dbmigration. Data for dbo.DMS_FactAttributeStatsBRIM -> livebit_dbo.dms_factattributestatsbrim.
INSERT INTO "livebit_dbo"."dms_factattributestatsbrim" ("configid", "fields", "syncdatatype", "configcategory", "generalcolumnname", "configidcount", "totoalattributevalue", "attributevaluematched", "attributevaluenotmatched", "percentagematched", "percentagenotmatched", "lastrundatetime") VALUES
(1, 'MedicineID', 'MedicineConfig', 'ShP+FTP+SAP+SQL', 'Medicine ID should Match in SharePoint, FTP, SAP, SQL', 1, 20, 20, 0, 100.0, 0.0, '2024-06-03 12:56:24.430000'),
(2, 'MedicineName', 'MedicineConfig', 'ShP+FTP+SAP+SQL', 'Medicine Name should Match in SharePoint, FTP, SAP, SQL', 1, 12, 10, 2, 83.33, 16.67, '2024-06-03 12:56:24.520000'),
(3, 'MedicineCategory', 'MedicineConfig', 'ShP+FTP+SAP+SQL', 'Medicine Category should Match in SharePoint, FTP, SAP, SQL', 1, 42, 20, 22, 47.62, 52.38, '2024-06-03 12:56:24.580000'),
(4, 'PatientID', 'PatientConfig', 'ShP+FTP+SAP+SQL', 'Patient Id should Match in FTP, SAP, SharePoint,SQL', 1, 20, 20, 0, 100.0, 0.0, '2024-06-03 12:56:24.870000'),
(5, 'PatientName', 'PatientConfig', 'FTP+SAP+SQL', 'Patient Name should Match in FTP, SAP, SQL', 1, 34, 10, 24, 29.41, 70.59, '2024-06-03 12:56:24.960000'),
(6, 'InsuranceProvider', 'PatientConfig', 'FTP+SAP+SQL', 'Insurance Provider should Match in FTP, SAP, SQL', 1, 34, 10, 24, 29.41, 70.59, '2024-06-03 12:56:25.047000'),
(7, 'Allergies', 'PatientConfig', 'SAP+SQL', 'Allergies should Match in SAP, SQL', 1, 20, 20, 0, 100.0, 0.0, '2024-06-03 12:56:25.140000'),
(8, 'MedicalHistory', 'PatientConfig', 'ShP+SAP', 'Medical History should Match in ShP, SAP', 1, 20, 20, 0, 100.0, 0.0, '2024-06-03 12:56:25.223000'),
(9, 'InsuranceNumber', 'PatientConfig', 'FTP+SAP+SQL', 'Insurance Number should Match in FTP, SAP, SQL', 1, 34, 10, 24, 29.41, 70.59, '2024-06-03 12:56:25.310000'),
(10, 'PurchaseType', 'MedicinePurchaseType', 'SAP+SQL', 'Purchase Type should Match in SAP, SQL', 1, 20, 20, 0, 100.0, 0.0, '2024-06-03 12:56:26.143000'),
(11, 'PaymentMethod', 'MedicinePurchaseType', 'SAP+SQL', 'Payment Method should Match in SAP, SQL', 1, 20, 20, 0, 100.0, 0.0, '2024-06-03 12:56:26.310000'),
(12, 'InsuranceCovered', 'MedicinePurchaseType', 'ShP+SAP', 'Insurance Covered should Match in ShP, SAP', 1, 20, 20, 0, 100.0, 0.0, '2024-06-03 12:56:26.467000');
