-- Generated by dbmigration. Data for zora.plans -> livebit_zora.plans.
INSERT INTO "livebit_zora"."plans" ("plan_id", "plan_name", "description", "is_free_plan", "created_at", "last_updated_at", "max_short_links", "max_redirects", "max_custom_aliases", "max_bulk_shorten", "max_qr_codes", "max_campaigns", "max_dashboard_count", "data_retention_days", "api_limit_per_month", "custom_domain_allowed") VALUES
('3B7E92FA', 'Starter Plan', 'For growing projects and small businesses', FALSE, '2025-03-31 20:55:02.760000', '2025-03-31 20:55:02.760000', 100, 50, 100, 50, 20, 5, 10, 90, 10000, TRUE),
('7F2A4D9C', 'Basic Plan', 'Perfect for personal use and getting started', TRUE, '2025-03-31 20:54:54.090000', '2025-03-31 20:54:54.090000', 10, 5, 10, 0, 5, 0, 5, 30, 1000, FALSE),
('A89F12C3', 'Pro Plan', 'For professionals and serious creators', FALSE, '2025-03-31 20:55:14.980000', '2025-03-31 20:55:14.980000', 1000, 200, 500, 200, 50, 20, 25, 180, 50000, TRUE),
('C5D8A7E4', 'Enterprise Plan', 'Custom solutions for large organizations', FALSE, '2025-03-31 20:55:52.730000', '2025-03-31 20:55:52.730000', 100000, 5000, 10000, 5000, 500, 500, 100, 730, 1000000, TRUE),
('F8D6E5A1', 'Business Plan', 'For established businesses and teams', FALSE, '2025-03-31 20:55:35.340000', '2025-03-31 20:55:35.340000', 10000, 1000, 2500, 1000, 200, 100, 50, 365, 250000, TRUE);
