-- Generated by dbmigration. Data for dbo.Tracker -> livebit_dbo.tracker.
INSERT INTO "livebit_dbo"."tracker" ("trackerid", "userid", "surveyid", "lastanswerquestionid", "iscompleted", "completiondate", "lastupdateddate") VALUES
(107, 67, 30, NULL, TRUE, '2024-12-13 04:03:16.723000', '2024-12-13 04:03:16.723000'),
(114, 219, 709, NULL, TRUE, '2025-06-30 13:44:25.640000', '2025-06-30 13:44:25.640000');
