-- Generated by dbmigration. Data for dbo.Roles -> livebit_dbo.roles.
INSERT INTO "livebit_dbo"."roles" ("roleid", "rolename", "description") VALUES
(1, 'AppAdmin', 'Has full access to all features and settings.'),
(2, 'User', 'Basic access to perform tasks and view information.'),
(3, 'CompanyAdmin', 'Has All Access at company Level'),
(4, 'ConsultingAdmin', 'Has All Access at Consulting Level'),
(5, 'SurveyAssigner', 'Can Assign Specific Survey to user under company');
