-- Generated by dbmigration. Data for zora.domain -> livebit_zora.domain.
INSERT INTO "livebit_zora"."domain" ("domain_id", "company_id", "user_id", "domain_name", "is_domain_verified", "is_domain_primary", "domain_verification_token", "created_at", "updated_at") VALUES
(1, NULL, NULL, 'go.livebit.link', FALSE, FALSE, '9620a199-5ec1-425d-9d82-d2312c90862e', '2025-04-07 16:28:42.073000', '2025-04-07 17:27:26.907000'),
(2, 0, 13, 'app.evaomax.com', TRUE, TRUE, NULL, '2025-05-02 11:41:18.020000', '2025-05-02 11:41:18.020000'),
(3, 0, 13, 'app.divaomax.com', TRUE, FALSE, NULL, '2025-05-02 11:41:18.020000', '2025-05-02 11:41:18.020000'),
(4, 0, 13, 'mybadge.ciraomax.com', TRUE, FALSE, NULL, '2025-05-02 11:41:18.020000', '2025-05-02 11:41:18.020000');
