-- Generated by dbmigration. Data for divaconfig.DatabaseConfig -> livebit_divaconfig.databaseconfig.
INSERT INTO "livebit_divaconfig"."databaseconfig" ("databaseid", "databasename", "databasetype", "databaseusedfor", "databaseowner", "collationname", "compatibilitylevel", "recoverymodel", "keyname", "lastsyncmetadatadatetime", "statedesc", "createdat", "updatedat") VALUES
(1, 'LiveBit', 'SQL Test', 'Development', 'Vishal Pawar', 'SQL_Latin1_General_CP1_CI_AS', 140, 'FULL', 'azureKey', '2024-12-22 02:51:37.390000', 'Open', '2024-12-22 02:51:37.390000', '2024-12-22 02:51:37.390000');
