-- Generated by dbmigration. Data for dbo.DMS_FactFunctionaStatsBRIM -> livebit_dbo.dms_factfunctionastatsbrim.
INSERT INTO "livebit_dbo"."dms_factfunctionastatsbrim" ("syncdatatype", "configidcount", "totoalattributevalue", "attributevaluematched", "attributevaluenotmatched", "percentagematched", "percentagenotmatched") VALUES
('MedicineConfig', 3, 74, 50, 24, 67.57, 32.43),
('PatientConfig', 6, 162, 90, 72, 55.56, 44.44),
('MedicinePurchaseType', 3, 60, 60, 0, 100.0, 0.0);
