-- Generated by dbmigration. Data for aidd.tenants -> livebit_aidd.tenants.
INSERT INTO "livebit_aidd"."tenants" ("id", "name", "slug", "status", "created_at", "updated_at") VALUES
('1c09bc27-1da3-4dc9-b90c-103913e2679f', 'John''s AI Workspace', 'john-ce03de3e', 'active', '2025-09-29 06:42:52.233000+00:00', '2025-09-29 06:42:52.233000+00:00'),
('54264618-b224-4886-9bf2-113a7c5c4746', 'bhargavkonathala313''s Workspace', 'bhargavkonathala313-34ddee00', 'active', '2025-10-08 13:49:46.555000+00:00', '2025-10-08 13:49:46.555000+00:00'),
('7e49e25b-2650-4e50-bd79-19810d48b7b2', 'saranyapampana9''s Workspace', 'saranyapampana9-55a4719f', 'active', '2025-10-15 06:05:33.699000+00:00', '2025-10-15 06:05:33.699000+00:00'),
('db68f944-081e-4693-8dbe-28f703c8e0ed', 'vishal''s Workspace', 'vishal-23eafdf1', 'active', '2025-10-13 01:59:32.046000+00:00', '2025-10-13 01:59:32.046000+00:00'),
('4a1915bf-97f1-4476-accf-2a9a2bd02e37', 'bhargav82970''s Workspace', 'bhargav82970-e3e872e0', 'active', '2025-10-08 10:31:55.532000+00:00', '2025-10-08 10:31:55.532000+00:00'),
('833ba4cb-c8f4-4dcf-acbd-2e9c023a4ab4', 'pampanasaranya''s Workspace', 'pampanasaranya-23ebf6b0', 'active', '2025-10-15 06:08:17.420000+00:00', '2025-10-15 06:08:17.420000+00:00'),
('08291fc4-d44d-4c68-a827-3b79b47b1bc2', 'sonal''s Workspace', 'sonal-660d2940', 'active', '2025-10-13 02:21:53.511000+00:00', '2025-10-13 02:21:53.511000+00:00'),
('337b5ff4-4c32-4243-b428-7db5d094ebc2', 'praveen.katipamu''s Workspace', 'praveen-katipamu-7e219b75', 'active', '2025-10-08 11:06:02.130000+00:00', '2025-10-08 11:06:02.130000+00:00'),
('79e5b2bd-6ce3-4cb8-9b44-9f72c4c0a3be', 'AJ.Attavar''s Workspace', 'aj-attavar-1e7a0162', 'active', '2025-10-13 12:57:54.897000+00:00', '2025-10-13 12:57:54.897000+00:00'),
('366c8e29-d8cd-4414-bbbc-aa5e6aed75db', 'Bhargav''s Workspace', 'bhargav-8b37fc1a', 'active', '2025-10-08 06:43:31.352000+00:00', '2025-10-08 06:43:31.352000+00:00'),
('8a00e3a2-a456-4596-8edc-c1696610c9f3', 'Bhargav''s Workspace', 'bhargav-fb889468', 'active', '2025-10-08 06:11:16.634000+00:00', '2025-10-08 06:11:16.634000+00:00'),
('1b2d9a27-e263-4f12-a6d0-f1b547e1c070', 'Bhargav''s Workspace', 'bhargav-8b584d55', 'active', '2025-10-08 06:14:03.030000+00:00', '2025-10-08 06:14:03.030000+00:00'),
('e48a7374-0fcd-4544-ac75-f3c21caa2226', 'Bhargav''s Workspace', 'bhargav-e3028d92', 'active', '2025-10-08 06:31:19.183000+00:00', '2025-10-08 06:31:19.183000+00:00');
