-- Generated by dbmigration. Data for divaconfig.sampleData_sample -> livebit_divaconfig.sampledata_sample.
INSERT INTO "livebit_divaconfig"."sampledata_sample" ("masterdataid", "mastername", "mastervalue", "masterdisplaytext", "masterdescription", "isactive", "createddate", "createdtime", "createddatetime", "masterint", "masterfloat", "sortorder", "createdat", "updatedat") VALUES
(1, 'Country', 'CA', 'Canada', 'Country in North America', TRUE, '2024-12-01', '10:30:00', '2024-12-01 10:30:00', NULL, NULL, 1, '2024-12-22 06:26:25.893000', '2024-12-22 06:26:25.893000'),
(2, 'Country', 'US', 'United States', 'Country in North America', TRUE, '2024-12-01', '10:35:00', '2024-12-01 10:35:00', NULL, NULL, 2, '2024-12-22 06:26:25.893000', '2024-12-22 06:26:25.893000'),
(3, 'Status', 'Active', 'Active', 'Active user status', TRUE, '2024-12-01', '10:40:00', '2024-12-01 10:40:00', 1, NULL, 1, '2024-12-22 06:26:25.893000', '2024-12-22 06:26:25.893000'),
(4, 'Status', 'Inactive', 'Inactive', 'Inactive user status', TRUE, '2024-12-01', '10:45:00', '2024-12-01 10:45:00', 0, NULL, 2, '2024-12-22 06:26:25.893000', '2024-12-22 06:26:25.893000'),
(5, 'TaxRate', '5%', '5 Percent', 'Standard tax rate', TRUE, '2024-12-01', '10:50:00', '2024-12-01 10:50:00', NULL, 0.05, 1, '2024-12-22 06:26:25.893000', '2024-12-22 06:26:25.893000'),
(6, 'TaxRate', '10%', '10 Percent', 'High tax rate', TRUE, '2024-12-01', '10:55:00', '2024-12-01 10:55:00', NULL, 0.1, 2, '2024-12-22 06:26:25.893000', '2024-12-22 06:26:25.893000');
