-- Generated by dbmigration.
-- Table divadim.DimDate -> livebit_divadim.dimdate

CREATE TABLE IF NOT EXISTS "livebit_divadim"."dimdate" (
  "datekey" integer NOT NULL,
  "fulldate" date,
  "dayname" varchar(20),
  PRIMARY KEY ("datekey")
);
