-- Generated by dbmigration.
-- Table dbo.Customers -> livebit_dbo.customers
-- NOTE: column UpdatedAt: datetimeoffset -> timestamptz: instant kept, original UTC offset not kept; fractional seconds rounded to microseconds
-- NOTE: column Photo: binary length not preserved (bytea is variable length)

CREATE TABLE IF NOT EXISTS "livebit_dbo"."customers" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(100) NOT NULL,
  "notes" text,
  "isactive" boolean DEFAULT true NOT NULL,
  "balance" numeric(18,2),
  "externalid" uuid,
  "updatedat" timestamptz,
  "photo" bytea,
  "profile" xml,
  "signupdatekey" integer,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "customers_ix_customers_name" ON "livebit_dbo"."customers" ("name");
