-- Generated by dbmigration.
-- Table Sandbox.AuditLog -> livebit_sandbox.auditlog

CREATE TABLE IF NOT EXISTS "livebit_sandbox"."auditlog" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "message" text,
  "loggedat" timestamp,
  PRIMARY KEY ("id")
);
