"""Generate Postgres DDL for a source table, targeting a specific schema."""

from __future__ import annotations

from ..model import SourceKind, Table
from ..naming import quote_ident, sanitize_identifier
from .types import map_column_type, map_default


def create_schema_ddl(schema: str) -> str:
    return f"CREATE SCHEMA IF NOT EXISTS {quote_ident(schema)};"


def create_table_ddl(table: Table, target_schema: str, source_kind: SourceKind) -> str:
    """Return a CREATE TABLE statement for *table* inside *target_schema*."""
    source_is_pg = source_kind == SourceKind.AZURE_POSTGRES
    target_table = sanitize_identifier(table.name)
    lines: list[str] = []

    for col in sorted(table.columns, key=lambda c: c.ordinal):
        col_name = sanitize_identifier(col.name)
        mapped = map_column_type(col, source_is_pg)
        pieces = [f"  {quote_ident(col_name)} {mapped.postgres_type}"]

        if col.is_identity:
            # Preserve auto-increment semantics via an identity column.
            pieces.append("GENERATED BY DEFAULT AS IDENTITY")

        default = map_default(col.default, source_is_pg)
        if default and not col.is_identity:
            pieces.append(f"DEFAULT {default}")

        if not col.nullable:
            pieces.append("NOT NULL")

        lines.append(" ".join(pieces))

    if table.primary_key and table.primary_key.columns:
        pk_cols = ", ".join(quote_ident(sanitize_identifier(c)) for c in table.primary_key.columns)
        lines.append(f"  PRIMARY KEY ({pk_cols})")

    body = ",\n".join(lines)
    qualified = f"{quote_ident(target_schema)}.{quote_ident(target_table)}"
    return f"CREATE TABLE IF NOT EXISTS {qualified} (\n{body}\n);"


def create_index_ddls(table: Table, target_schema: str) -> list[str]:
    """Return CREATE INDEX statements for non-primary indexes."""
    ddls: list[str] = []
    target_table = sanitize_identifier(table.name)
    qualified = f"{quote_ident(target_schema)}.{quote_ident(target_table)}"
    for idx in table.indexes:
        if idx.is_primary:
            continue
        cols = ", ".join(quote_ident(sanitize_identifier(c)) for c in idx.columns)
        unique = "UNIQUE " if idx.unique else ""
        idx_name = sanitize_identifier(f"{table.name}_{idx.name}")
        ddls.append(
            f"CREATE {unique}INDEX IF NOT EXISTS {quote_ident(idx_name)} "
            f"ON {qualified} ({cols});"
        )
    return ddls


def foreign_key_ddls(table: Table, target_schema: str) -> list[str]:
    """Return ALTER TABLE ... ADD FOREIGN KEY statements.

    Foreign keys are applied in a second pass, after all tables in the schema
    exist, so referenced tables are already present. Cross-database references
    are not supported in the single-schema model and are skipped + flagged by
    the pipeline.
    """
    ddls: list[str] = []
    target_table = sanitize_identifier(table.name)
    qualified = f"{quote_ident(target_schema)}.{quote_ident(target_table)}"
    for fk in table.foreign_keys:
        cols = ", ".join(quote_ident(sanitize_identifier(c)) for c in fk.columns)
        ref_table = f"{quote_ident(target_schema)}.{quote_ident(sanitize_identifier(fk.ref_table))}"
        ref_cols = ", ".join(quote_ident(sanitize_identifier(c)) for c in fk.ref_columns)
        fk_name = sanitize_identifier(f"{table.name}_{fk.name}")
        clause = (
            f"ALTER TABLE {qualified} ADD CONSTRAINT {quote_ident(fk_name)} "
            f"FOREIGN KEY ({cols}) REFERENCES {ref_table} ({ref_cols})"
        )
        if fk.on_delete:
            clause += f" ON DELETE {fk.on_delete}"
        ddls.append(clause + ";")
    return ddls
