import pytest

from dbmigration.config import (
    DiscoveryConfig,
    MigrationConfig,
    NamingConfig,
    Plan,
    RoutinesConfig,
    TargetConfig,
)
from dbmigration.model import Column, Database, Index, Routine, SourceKind, Table
from dbmigration.pipeline import (
    SourceTarget,
    build_schema_statements,
    migrate_database_plan,
    plan_schema_names,
)


def make_plan(template="{db}_{schema}", disambiguate=False):
    return Plan(
        target=TargetConfig(supabase_project_ref="mmbxootqppuvriodzetb"),
        naming=NamingConfig(schema_template=template, auto_disambiguate=disambiguate),
        discovery=DiscoveryConfig(),
        migration=MigrationConfig(),
        routines=RoutinesConfig(),
    )


def sample_db():
    t = Table(
        schema="dbo",
        name="Customer",
        columns=[
            Column(name="Id", source_type="int", nullable=False, is_identity=True, ordinal=1),
            Column(name="Name", source_type="varchar", char_length=100, ordinal=2),
            Column(name="CreatedAt", source_type="datetime", default="(getdate())", ordinal=3),
        ],
        primary_key=Index(name="pk", columns=["Id"], unique=True, is_primary=True),
        approx_row_count=42,
    )
    r = Routine(
        schema="dbo", name="usp_Get", kind="procedure", language="tsql",
        definition="CREATE PROC dbo.usp_Get AS BEGIN SELECT GETDATE(); END",
    )
    return Database(
        subscription="Sub1", server="srv1", kind=SourceKind.AZURE_SQL,
        name="Sales", tables=[t], routines=[r],
    )


def test_schema_statements_target_one_schema():
    plan = make_plan()
    db = sample_db()
    create, _fks, table_schema = build_schema_statements(plan, db)
    assert table_schema["dbo.Customer"] == "sales_dbo"
    joined = "\n".join(create)
    assert 'CREATE SCHEMA IF NOT EXISTS "sales_dbo"' in joined
    assert 'CREATE TABLE IF NOT EXISTS "sales_dbo"."customer"' in joined
    assert "GENERATED BY DEFAULT AS IDENTITY" in joined
    assert "now()" in joined  # getdate() default rewritten


def test_migrate_plan_records_outcomes():
    plan = make_plan()
    outcome = migrate_database_plan(plan, sample_db())
    assert outcome.target_schema == "sales_dbo"
    assert len(outcome.tables) == 1
    assert outcome.tables[0].approx_source_rows == 42
    assert len(outcome.routines) == 1


def test_collision_detection_raises():
    plan = make_plan()
    sources = [
        SourceTarget("A", "s1", "s1", SourceKind.AZURE_SQL, "Sales"),
        SourceTarget("B", "s2", "s2", SourceKind.AZURE_SQL, "Sales"),
    ]
    with pytest.raises(ValueError):
        plan_schema_names(plan, sources)


def test_collision_allowed_when_disambiguate():
    plan = make_plan(disambiguate=True)
    sources = [
        SourceTarget("A", "s1", "s1", SourceKind.AZURE_SQL, "Sales"),
        SourceTarget("B", "s2", "s2", SourceKind.AZURE_SQL, "Sales"),
    ]
    # Should not raise.
    plan_schema_names(plan, sources)


def test_report_markdown_renders():
    plan = make_plan()
    from dbmigration.report.record import MigrationRecord

    record = MigrationRecord(target=plan.target.safe_summary(), dry_run=True)
    record.add_database(migrate_database_plan(plan, sample_db()))
    record.finish()
    md = record.render_markdown()
    assert "# Database Migration Report" in md
    assert "sales_dbo" in md
    assert "usp_get" in md.lower()
