-- Generated by dbmigration.
-- Procedure dbo.sp_renamediagram -> livebit_dbo.sp_renamediagram
-- Original source: source/routines/livebit_dbo__sp_renamediagram.sql

CREATE OR REPLACE FUNCTION "livebit_dbo"."sp_renamediagram"(diagramname text, owner_id integer DEFAULT null, new_diagramname text)
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
    -- ---- converted from T-SQL procedure dbo.sp_renamediagram ----
    'dbo'
    	AS
    	BEGIN
    		set nocount on
    		declare theid 			int
    		declare isdbo 			int
		
    		declare uidfound 		int
    		declare diagid			int
    		declare diagidtarg		int
    		declare u_name			sysname
    		if((diagramname is null) or (new_diagramname is null))
    		begin
    			RAISERROR ('Invalid value', 16, 1);
    			return -1
    		end
	
    		EXECUTE AS CALLER;
    		select theid = DATABASE_PRINCIPAL_ID();
    		select isdbo = IS_MEMBER(N'db_owner'); 
    		if(owner_id is null)
    			select owner_id = theid;
    		REVERT;
	
    		select u_name = USER_NAME(owner_id)
	
    		select diagid = diagram_id, uidfound = principal_id from dbo.sysdiagrams where principal_id = owner_id and name = diagramname 
    		if(diagid IS NULL or (isdbo = 0 and uidfound <> theid))
    		begin
    			RAISERROR ('Diagram does not exist or you do not have permission.', 16, 1)
    			return -3
    		end
	
    		-- if((u_name is not null) and (new_diagramname = diagramname))	-- nothing will change
    		--	return 0;
	
    		if(u_name is null)
    			select diagidtarg = diagram_id from dbo.sysdiagrams where principal_id = theid and name = new_diagramname
    		else
    			select diagidtarg = diagram_id from dbo.sysdiagrams where principal_id = owner_id and name = new_diagramname
	
    		if((diagidtarg is not null) and  diagid <> diagidtarg)
    		begin
    			RAISERROR ('The name is already used.', 16, 1);
    			return -2
    		end		
	
    		if(u_name is null)
    			update dbo.sysdiagrams set [name] = new_diagramname, principal_id = theid where diagram_id = diagid
    		else
    			update dbo.sysdiagrams set [name] = new_diagramname where diagram_id = diagid
    		return 0
    	END
END;
$function$;
