-- Generated by dbmigration.
-- Procedure divaconfig.LoadTableInfo -> livebit_divaconfig.loadtableinfo
-- Original source: source/routines/livebit_divaconfig__loadtableinfo.sql

CREATE OR REPLACE FUNCTION "livebit_divaconfig"."loadtableinfo"()
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
    -- REVIEW (manual): sp_executesql — port to EXECUTE ... USING  [sp_executesql]
    -- REVIEW (manual): TRY/CATCH — port to BEGIN ... EXCEPTION WHEN OTHERS  [TRY]
    -- REVIEW (manual): TRY/CATCH — port to BEGIN ... EXCEPTION WHEN OTHERS  [TRY]
    -- REVIEW (manual): TRY/CATCH — port to BEGIN ... EXCEPTION WHEN OTHERS  [CATCH]
    -- REVIEW (manual): TRY/CATCH — port to BEGIN ... EXCEPTION WHEN OTHERS  [CATCH]
    -- REVIEW (manual): IDENTITY(...) in a query — verify sequence semantics  [IDENTITY(]
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- ---- converted from T-SQL procedure divaconfig.LoadTableInfo ----
    BEGIN
        SET NOCOUNT ON;

        -- Declare a table variable to hold the latest metadata
        DECLARE latestmetadata TABLE (
            ID INT IDENTITY(1,1),
            TableDatabaseName NVARCHAR(255),
            TableSchemaName NVARCHAR(255),
            TableName NVARCHAR(255),
            TableDescription NVARCHAR(MAX),
            TableRowCount BIGINT NULL,
            TableColumnCount INT,
            TableIdentityColumnName NVARCHAR(255),
            TablePrimaryColumnCSV NVARCHAR(MAX),
            TableUniqueColumnCSV NVARCHAR(MAX),
            IsTableEditable BIT,
            TableMetadataSyncDateTime DATETIME
        );

        -- Insert latest metadata into the table variable
        INSERT INTO latestmetadata
        SELECT 
            DB_NAME() AS TableDatabaseName,              -- Current database name
            t.TABLE_SCHEMA AS TableSchemaName,          -- Schema of the table
            t.TABLE_NAME AS TableName,                  -- Name of the table
            'Table name is ' + t.TABLE_NAME AS TableDescription, -- Table description
            NULL AS TableRowCount,                      -- Placeholder for row count
            COUNT(c.COLUMN_NAME) AS TableColumnCount,   -- Total column count
            NULL AS TableIdentityColumnName,            -- Identity column (not available in INFORMATION_SCHEMA)
            STRING_AGG(pk.COLUMN_NAME, ',') AS TablePrimaryColumnCSV, -- Primary key columns (comma-separated)
            STRING_AGG(u.COLUMN_NAME, ',') AS TableUniqueColumnCSV,   -- Unique key columns (comma-separated)
            CASE 
                WHEN t.TABLE_TYPE = 'BASE TABLE' THEN 1 -- Editable for base tables
                ELSE 0
            END AS IsTableEditable, 
            now() AS TableMetadataSyncDateTime      -- Current date for metadata sync
        FROM 
            INFORMATION_SCHEMA.TABLES t
        LEFT JOIN 
            INFORMATION_SCHEMA.COLUMNS c 
            ON t.TABLE_SCHEMA = c.TABLE_SCHEMA AND t.TABLE_NAME = c.TABLE_NAME
        LEFT JOIN 
            (SELECT 
                 ku.TABLE_SCHEMA, 
                 ku.TABLE_NAME, 
                 ku.COLUMN_NAME
             FROM 
                 INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
             JOIN 
                 INFORMATION_SCHEMA.KEY_COLUMN_USAGE ku
                 ON tc.CONSTRAINT_NAME = ku.CONSTRAINT_NAME
             WHERE 
                 tc.CONSTRAINT_TYPE = 'PRIMARY KEY') pk
            ON t.TABLE_SCHEMA = pk.TABLE_SCHEMA AND t.TABLE_NAME = pk.TABLE_NAME
        LEFT JOIN 
            (SELECT 
                 ku.TABLE_SCHEMA, 
                 ku.TABLE_NAME, 
                 ku.COLUMN_NAME
             FROM 
                 INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
             JOIN 
                 INFORMATION_SCHEMA.KEY_COLUMN_USAGE ku
                 ON tc.CONSTRAINT_NAME = ku.CONSTRAINT_NAME
             WHERE 
                 tc.CONSTRAINT_TYPE = 'UNIQUE') u
            ON t.TABLE_SCHEMA = u.TABLE_SCHEMA AND t.TABLE_NAME = u.TABLE_NAME
        WHERE 
            t.TABLE_TYPE IN ('BASE TABLE') -- Include only base tables
        GROUP BY 
            t.TABLE_SCHEMA, t.TABLE_NAME, t.TABLE_TYPE;

        -- Variables for row count updates
        DECLARE id INT, maxid INT, schemaname NVARCHAR(255), tablename NVARCHAR(255), sql NVARCHAR(MAX), rowcount BIGINT;

        -- Get the range of IDs in the table
        SELECT id = MIN(ID), maxid = MAX(ID) FROM latestmetadata;

        -- WHILE loop to process each table
        WHILE id IS NOT NULL AND id <= maxid
        BEGIN
            -- Get the schema and table name for the current record
            SELECT schemaname = TableSchemaName, tablename = TableName
            FROM latestmetadata WHERE ID = id;

            -- Build dynamic SQL to get the row count
            SET sql = N'SELECT rowcount = COUNT(*) FROM [' + schemaname + '].[' + tablename + ']';

            BEGIN TRY
                -- Execute the SQL and get the row count
                EXEC sp_executesql sql, N'rowcount BIGINT OUTPUT', rowcount OUTPUT;

                -- Update the row count in latestmetadata
                UPDATE latestmetadata
                SET TableRowCount = rowcount
                WHERE ID = id;
            END TRY
            BEGIN CATCH
                -- Log errors if any during row count execution
                PRINT 'Error calculating row count for [' + schemaname + '].[' + tablename + ']: ' 
                    + ERROR_MESSAGE();
            END CATCH;

            -- Increment to the next record
            SET id = id + 1;
        END;

        -- Insert new records
        INSERT INTO [divaconfig].[TableInfo] (
            TableDatabaseName,
            TableSchemaName,
            TableName,
            TableDescription,
            TableRowCount,
            TableColumnCount,
            TableIdentityColumnName,
            TablePrimaryColumnCSV,
            TableUniqueColumnCSV,
            IsTableEditable,
            TableMetadataSyncDateTime,
            IsDeleted
        )
        SELECT 
            lm.TableDatabaseName,
            lm.TableSchemaName,
            lm.TableName,
            lm.TableDescription,
            lm.TableRowCount,
            lm.TableColumnCount,
            lm.TableIdentityColumnName,
            lm.TablePrimaryColumnCSV,
            lm.TableUniqueColumnCSV,
            lm.IsTableEditable,
            lm.TableMetadataSyncDateTime,
            0 -- IsDeleted = 0 for new records
        FROM 
            latestmetadata lm
        WHERE 
            NOT EXISTS (
                SELECT 1 
                FROM [divaconfig].[TableInfo] ti
                WHERE ti.TableDatabaseName = lm.TableDatabaseName
                  AND ti.TableSchemaName = lm.TableSchemaName
                  AND ti.TableName = lm.TableName
            );

        -- Update existing records
        UPDATE ti
        SET 
            ti.TableDescription = lm.TableDescription,
            ti.TableRowCount = lm.TableRowCount,
            ti.TableColumnCount = lm.TableColumnCount,
            ti.TableIdentityColumnName = lm.TableIdentityColumnName,
            ti.TablePrimaryColumnCSV = lm.TablePrimaryColumnCSV,
            ti.TableUniqueColumnCSV = lm.TableUniqueColumnCSV,
            ti.IsTableEditable = lm.IsTableEditable,
            ti.TableMetadataSyncDateTime = lm.TableMetadataSyncDateTime,
            ti.IsDeleted = 0, -- Reset IsDeleted flag if it was previously set
            ti.UpdatedAt = now()
        FROM 
            [divaconfig].[TableInfo] ti
        INNER JOIN 
            latestmetadata lm
        ON 
            ti.TableDatabaseName = lm.TableDatabaseName
            AND ti.TableSchemaName = lm.TableSchemaName
            AND ti.TableName = lm.TableName;

        -- Soft delete records not in the latest metadata
        UPDATE ti
        SET 
            ti.IsDeleted = 1,
            ti.UpdatedAt = now()
        FROM 
            [divaconfig].[TableInfo] ti
        WHERE 
            NOT EXISTS (
                SELECT 1 
                FROM latestmetadata lm
                WHERE ti.TableDatabaseName = lm.TableDatabaseName
                  AND ti.TableSchemaName = lm.TableSchemaName
                  AND ti.TableName = lm.TableName
            );

        SET NOCOUNT OFF;
    END;
END;
$function$;
