-- Generated by dbmigration.
-- Procedure divaconfig.loadSpecialTableCardChart -> livebit_divaconfig.loadspecialtablecardchart
-- Original source: source/routines/livebit_divaconfig__loadspecialtablecardchart.sql

CREATE OR REPLACE FUNCTION "livebit_divaconfig"."loadspecialtablecardchart"()
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
    -- REVIEW (manual): MERGE statement — rewrite as INSERT ... ON CONFLICT  [MERGE]
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- ---- converted from T-SQL procedure divaconfig.loadSpecialTableCardChart ----
    MERGE INTO [divaconfig].[CardDisplayPerSubtab] AS target
    USING (
        SELECT 
            84 AS SubTabID,
            DimTableName AS ChartDisplayName,
            CAST(now() AT TIME ZONE 'UTC' AT TIME ZONE 'Eastern Standard Time' AS DATE) AS ChartDisplayValue,
            'Build on ' AS ChartDisplayValuePrefix,
           ' Time ' + CONVERT(VARCHAR(8), now() AT TIME ZONE 'UTC' AT TIME ZONE 'Eastern Standard Time', 108) AS ChartDisplayValueSuffix,
            'Value Generated for ' + DimTableName + ' ' + DimTableDescription AS ChartDisplayDescription
        FROM divadim.DimMaster
    ) AS source
    ON target.ChartDisplayName = source.ChartDisplayName  -- Matching based on ChartDisplayName

    WHEN MATCHED THEN
        UPDATE SET 
            ChartDisplayValue = source.ChartDisplayValue,
            ChartDisplayValuePrefix = source.ChartDisplayValuePrefix,
            ChartDisplayValueSuffix = source.ChartDisplayValueSuffix,
            ChartDisplayDescription = source.ChartDisplayDescription

    WHEN NOT MATCHED THEN
        INSERT (SubTabID, ChartDisplayName, ChartDisplayValue, ChartDisplayValuePrefix, ChartDisplayValueSuffix, ChartDisplayDescription)
        VALUES (source.SubTabID, source.ChartDisplayName, source.ChartDisplayValue, source.ChartDisplayValuePrefix, source.ChartDisplayValueSuffix, source.ChartDisplayDescription);
END;
$function$;
