-- Generated by dbmigration.
-- Procedure dbo.sp_helpdiagramdefinition -> livebit_dbo.sp_helpdiagramdefinition
-- Original source: source/routines/livebit_dbo__sp_helpdiagramdefinition.sql

CREATE OR REPLACE FUNCTION "livebit_dbo"."sp_helpdiagramdefinition"(diagramname text, owner_id integer DEFAULT null)
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
    -- ---- converted from T-SQL procedure dbo.sp_helpdiagramdefinition ----
    N'dbo'
    	AS
    	BEGIN
    		set nocount on

    		declare theid 		int
    		declare isdbo 		int
    		declare diagid		int
    		declare uidfound	int
	
    		if(diagramname is null)
    		begin
    			RAISERROR (N'E_INVALIDARG', 16, 1);
    			return -1
    		end
	
    		execute as caller;
    		select theid = DATABASE_PRINCIPAL_ID();
    		select isdbo = IS_MEMBER(N'db_owner');
    		if(owner_id is null)
    			select owner_id = theid;
    		revert; 
	
    		select diagid = diagram_id, uidfound = principal_id from dbo.sysdiagrams where principal_id = owner_id and name = diagramname;
    		if(diagid IS NULL or (isdbo = 0 and uidfound <> theid ))
    		begin
    			RAISERROR ('Diagram does not exist or you do not have permission.', 16, 1);
    			return -3
    		end

    		select version, definition FROM dbo.sysdiagrams where diagram_id = diagid ; 
    		return 0
    	END
END;
$function$;
