-- Generated by dbmigration.
-- Procedure divaconfig.sp_GetTables -> livebit_divaconfig.sp_gettables
-- Original source: source/routines/livebit_divaconfig__sp_gettables.sql

CREATE OR REPLACE FUNCTION "livebit_divaconfig"."sp_gettables"(schemaname text DEFAULT NULL, tablename text DEFAULT NULL, schematablecsv text DEFAULT NULL  -- Optional: Comma-separated schema.table combinations)
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- ---- converted from T-SQL procedure divaconfig.sp_GetTables ----
    BEGIN
        /*
        Usage Examples:
        1. Fetch all editable tables:
           EXEC [divaconfig].[sp_GetTables];

        2. Fetch editable tables for specific schemas:
           EXEC [divaconfig].[sp_GetTables] schemaname = 'dbo,divaconfig';
    	   	   EXEC [divaconfig].[sp_GetTables] schemaname = 'dbo';
    	   EXEC [divaconfig].[sp_GetTables] schemaname = 'divaconfig';

        3. Fetch specific tables:
           EXEC [divaconfig].[sp_GetTables] tablename = 'DMS_ConfigIDBusinessPartnerPercetage,YourTable';

        4. Fetch specific schema.table combinations:
           EXEC [divaconfig].[sp_GetTables] schematablecsv = 'dbo.MyTable,divaconfig.YourTable';
    	    EXEC [divaconfig].[sp_GetTables] schematablecsv = 'dbo.DMS_ConfigIDBusinessPartnerPercetage,divaconfig.SampleData'

    		   EXEC [divaconfig].[sp_GetTables] schematablecsv = 'dbo.DMS_ConfigIDBusinessPartnerPercetage,'

        5. Fetch specific tables within specific schemas:
           EXEC [divaconfig].[sp_GetTables] schemaname = 'dbo', tablename = 'MyTable';
        */

        -- Temporary table for splitting SchemaTableCSV into schema.table pairs
        DECLARE schematablecombo TABLE (FullName NVARCHAR(512));

        -- Split schematablecsv into schema.table pairs
        IF schematablecsv IS NOT NULL
        BEGIN
            INSERT INTO schematablecombo (FullName)
            SELECT TRIM(value)
            FROM STRING_SPLIT(schematablecsv, ',')
            WHERE CHARINDEX('.', value) > 0; -- Ensure valid schema.table format
        END

        -- Query with strict filters
        SELECT * 
        FROM [divaconfig].[TableInfo]
        WHERE [IsDeleted] = 0
          AND [IsTableEditable] = 1
          AND (
              -- Apply SchemaTableCSV filter strictly when provided
              (schematablecsv IS NOT NULL AND EXISTS (
                  SELECT 1 
                  FROM schematablecombo 
                  WHERE FullName = [TableSchemaName] + '.' + [TableName]
              ))
              OR
              -- Apply SchemaName or TableName filters when SchemaTableCSV is NULL
              (schematablecsv IS NULL AND (
                  (schemaname IS NULL OR [TableSchemaName] IN (SELECT TRIM(value) FROM STRING_SPLIT(schemaname, ',')))
                  AND (tablename IS NULL OR [TableName] IN (SELECT TRIM(value) FROM STRING_SPLIT(tablename, ',')))
              ))
          );
    END
END;
$function$;
