-- Generated by dbmigration.
-- Procedure dbo.sp_creatediagram -> livebit_dbo.sp_creatediagram
-- Original source: source/routines/livebit_dbo__sp_creatediagram.sql

CREATE OR REPLACE FUNCTION "livebit_dbo"."sp_creatediagram"(diagramname text, owner_id integer DEFAULT null, version integer, definition bytea)
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
    -- ---- converted from T-SQL procedure dbo.sp_creatediagram ----
    'dbo'
    	AS
    	BEGIN
    		set nocount on
	
    		declare theid int
    		declare retval int
    		declare isdbo	int
    		declare username sysname
    		if(version is null or diagramname is null)
    		begin
    			RAISERROR (N'E_INVALIDARG', 16, 1);
    			return -1
    		end
	
    		execute as caller;
    		select theid = DATABASE_PRINCIPAL_ID(); 
    		select isdbo = IS_MEMBER(N'db_owner');
    		revert; 
		
    		if owner_id is null
    		begin
    			select owner_id = theid;
    		end
    		else
    		begin
    			if theid <> owner_id
    			begin
    				if isdbo = 0
    				begin
    					RAISERROR (N'E_INVALIDARG', 16, 1);
    					return -1
    				end
    				select theid = owner_id
    			end
    		end
    		-- next 2 line only for test, will be removed after define name unique
    		if EXISTS(select diagram_id from dbo.sysdiagrams where principal_id = theid and name = diagramname)
    		begin
    			RAISERROR ('The name is already used.', 16, 1);
    			return -2
    		end
	
    		insert into dbo.sysdiagrams(name, principal_id , version, definition)
    				VALUES(diagramname, theid, version, definition) ;
		
    		select retval = @identity 
    		return retval
    	END
END;
$function$;
