-- Generated by dbmigration.
-- Procedure divaconfig.Load1TableColumnValue -> livebit_divaconfig.load1tablecolumnvalue
-- Original source: source/routines/livebit_divaconfig__load1tablecolumnvalue.sql

CREATE OR REPLACE FUNCTION "livebit_divaconfig"."load1tablecolumnvalue"(inputfulltablename text)
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
    -- REVIEW (manual): MERGE statement — rewrite as INSERT ... ON CONFLICT  [MERGE]
    -- REVIEW (manual): MERGE statement — rewrite as INSERT ... ON CONFLICT  [MERGE]
    -- REVIEW (manual): MERGE statement — rewrite as INSERT ... ON CONFLICT  [MERGE]
    -- REVIEW (manual): sp_executesql — port to EXECUTE ... USING  [sp_executesql]
    -- REVIEW (manual): IDENTITY(...) in a query — verify sequence semantics  [IDENTITY(]
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- ---- converted from T-SQL procedure divaconfig.Load1TableColumnValue ----
    -- Ensure parameter is not NULL
        IF inputfulltablename IS NULL
        BEGIN
            RAISERROR ('The input parameter inputfulltablename cannot be NULL.', 16, 1);
            RETURN;
        END
    DECLARE dynamicsql NVARCHAR(MAX);
    DECLARE fulltablename NVARCHAR(256) = NULL; -- Specify the schema.table (e.g., 'schema.table'), or leave NULL to process all tables
    SET fulltablename=inputfulltablename
    --SET fulltablename  = 'divaconfig.SampleData'; -- Specify the schema and table in this format
      PRINT 'Processing table: ' + fulltablename;
    DECLARE schemaname NVARCHAR(128), tablename NVARCHAR(128);
    DECLARE columnname NVARCHAR(128);
    DECLARE currentindex INT = 1;
    DECLARE totaltables INT;
    DECLARE totalcolumns INT;

    -- Temporary table to store the list of tables
    IF OBJECT_ID('livebit..DivaTempTableList', 'U') IS NOT NULL
        DROP TABLE livebit..DivaTempTableList;

    CREATE TABLE livebit..DivaTempTableList (
        RowNum INT,
        SchemaName NVARCHAR(128),
        TableName NVARCHAR(128)
    );

    -- Populate the table list based on the input
    IF fulltablename IS NULL
    BEGIN
        -- No table specified: Process all tables
        INSERT INTO livebit..DivaTempTableList (RowNum, SchemaName, TableName)
        SELECT 
            ROW_NUMBER() OVER (ORDER BY s.name, t.name) AS RowNum,
            s.name AS SchemaName,
            t.name AS TableName
        FROM sys.tables t
        INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
        WHERE t.is_ms_shipped = 0; -- Exclude system tables
    END
    ELSE
    BEGIN
        -- Specific table specified: Parse schema and table name
        SET schemaname = LEFT(fulltablename, CHARINDEX('.', fulltablename) - 1);
        SET tablename = RIGHT(fulltablename, length(fulltablename) - CHARINDEX('.', fulltablename));

        -- Validate inputs
        IF schemaname IS NULL OR tablename IS NULL
        BEGIN
            PRINT 'Invalid schema.table format. Please provide input as schema.table';
            RETURN;
        END

        INSERT INTO livebit..DivaTempTableList (RowNum, SchemaName, TableName)
        VALUES (1, schemaname, tablename);
    END

    -- Get the total number of tables to process
    SELECT totaltables = COUNT(*) FROM livebit..DivaTempTableList;

    PRINT 'Total Tables to Process: ' + CAST(totaltables AS NVARCHAR);

    -- Check if there are tables to process
    IF totaltables = 0
    BEGIN
        PRINT 'No tables to process.';
        RETURN;
    END

    -- Temporary table to store the column list
    IF OBJECT_ID('livebit..DivaTempColumnList', 'U') IS NOT NULL
        DROP TABLE livebit..DivaTempColumnList;

    CREATE TABLE livebit..DivaTempColumnList (
        RowNum INT,
        SchemaName NVARCHAR(128),
        TableName NVARCHAR(128),
        ColumnName NVARCHAR(128)
    );

    -- Process each table
    WHILE currentindex <= totaltables
    BEGIN
        -- Fetch details of the current table
        SELECT schemaname = SchemaName, tablename = TableName
        FROM livebit..DivaTempTableList
        WHERE RowNum = currentindex;

        PRINT 'Processing Table: ' + schemaname + '.' + tablename;

        -- Populate the column list for the current table
        DELETE FROM livebit..DivaTempColumnList;
        INSERT INTO livebit..DivaTempColumnList (RowNum, SchemaName, TableName, ColumnName)
        SELECT 
            ROW_NUMBER() OVER (ORDER BY c.name) AS RowNum,
            schemaname AS SchemaName,
            tablename AS TableName,
            c.name AS ColumnName
        FROM sys.columns c
        INNER JOIN sys.tables t ON c.object_id = t.object_id
        INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
        WHERE s.name = schemaname
          AND t.name = tablename
          AND c.is_computed = 0; -- Exclude computed columns

        -- Get the total number of columns for the current table
        SELECT totalcolumns = COUNT(*) FROM livebit..DivaTempColumnList;

        PRINT 'Total Columns to Process for ' + schemaname + '.' + tablename + ': ' + CAST(totalcolumns AS NVARCHAR);
    			-- Drop and create the DivaTempColumnValues table
    			IF OBJECT_ID('livebit..DivaTempColumnValues', 'U') IS NOT NULL
    				DROP TABLE livebit..DivaTempColumnValues;

    			CREATE TABLE livebit..DivaTempColumnValues (
    				ColumnValueID INT IDENTITY(1,1),
    				DatabaseName NVARCHAR(128),
    				SchemaName NVARCHAR(128),
    				TableName NVARCHAR(128),
    				ColumnName NVARCHAR(128),
    				Value NVARCHAR(MAX),
    				DisplayText NVARCHAR(MAX),
    				Description NVARCHAR(MAX),
    				ValueCount NVARCHAR(MAX),
    				IsActive BIT,
    				SortOrder INT,
    				CreatedAt DATETIME DEFAULT now(),
    				UpdatedAt DATETIME DEFAULT now()
    			);
        -- Process each column
        DECLARE columnindex INT = 1;
        WHILE columnindex <= totalcolumns
        BEGIN

            -- Fetch details of the current column
            SELECT columnname = ColumnName
            FROM livebit..DivaTempColumnList
            WHERE RowNum = columnindex;

            PRINT 'Processing Table: ' + schemaname + '.' + tablename+' for Column: ' + columnname;

            -- Dynamic SQL for processing the current column
            SET dynamicsql = '
                ;WITH DistinctValues AS (
                    SELECT DISTINCT
                        COALESCE(CAST([' + columnname + '] AS NVARCHAR(MAX)), ''NULL'') AS Value, -- Replace NULL with string NULL
                        CAST(COUNT(*) OVER (PARTITION BY [' + columnname + ']) AS NVARCHAR(MAX)) AS ValueCount -- Count occurrences
                    FROM [' + schemaname + '].[' + tablename + ']
                )
                INSERT INTO livebit..DivaTempColumnValues (DatabaseName, SchemaName, TableName, ColumnName, Value, DisplayText, Description, ValueCount, IsActive, SortOrder)
                SELECT 
                    DB_NAME() AS DatabaseName,
                    ''' + schemaname + ''' AS SchemaName,
                    ''' + tablename + ''' AS TableName,
                    ''' + columnname + ''' AS ColumnName,
                    Value,
                    Value AS DisplayText,
                    ''Distinct value from table [' + schemaname + '].[' + tablename + '] column [' + columnname + ']'' AS Description,
                    ValueCount,
                    1 AS IsActive,
                    ROW_NUMBER() OVER (ORDER BY Value) AS SortOrder -- Incremental sort order for distinct rows
                FROM DistinctValues';

            PRINT 'Generated Dynamic SQL for Column: ' + columnname;

            EXEC sp_executesql dynamicsql;

            -- Move to the next column
            SET columnindex = columnindex + 1;
        END

        -- Move to the next table
        SET currentindex = currentindex + 1;
    END

    -- Final MERGE and cleanup
    PRINT 'Performing final MERGE and cleanup operations...';

    MERGE INTO [divaconfig].[ColumnValue] AS Target
    USING livebit..DivaTempColumnValues AS Source
    ON Target.DatabaseName = Source.DatabaseName
       AND Target.SchemaName = Source.SchemaName
       AND Target.TableName = Source.TableName
       AND Target.ColumnName = Source.ColumnName
       AND Target.Value = Source.Value
    WHEN MATCHED THEN
        UPDATE SET 
            Target.DisplayText = Source.DisplayText,
            Target.Description = Source.Description,
            Target.ValueCount = Source.ValueCount,
            Target.IsActive = Source.IsActive,
            Target.SortOrder = Source.SortOrder,
            Target.UpdatedAt = now(),
            Target.IsDeleted = 0
    WHEN NOT MATCHED THEN
        INSERT (DatabaseName, SchemaName, TableName, ColumnName, Value, DisplayText, Description, ValueCount, IsActive, SortOrder, CreatedAt, UpdatedAt, IsDeleted)
        VALUES (Source.DatabaseName, Source.SchemaName, Source.TableName, Source.ColumnName, Source.Value, Source.DisplayText, Source.Description, Source.ValueCount, Source.IsActive, Source.SortOrder, now(), now(), 0);

    -- Soft delete any records missing in the final source
    UPDATE Target
    SET Target.IsDeleted = 1,
        Target.UpdatedAt = now()
    FROM [divaconfig].[ColumnValue] AS Target
    LEFT JOIN livebit..DivaTempColumnValues AS Source
    ON Target.DatabaseName = Source.DatabaseName
       AND Target.SchemaName = Source.SchemaName
       AND Target.TableName = Source.TableName
       AND Target.ColumnName = Source.ColumnName
       AND Target.Value = Source.Value
    WHERE Source.ColumnValueID IS NULL;

    -- Cleanup physical tables
    DROP TABLE livebit..DivaTempTableList;
    DROP TABLE livebit..DivaTempColumnList;
    DROP TABLE livebit..DivaTempColumnValues;

    PRINT 'Processing Completed.';
END;
$function$;
