-- Generated by dbmigration.
-- Function dbo.fn_diagramobjects -> livebit_dbo.fn_diagramobjects
-- Original source: source/routines/livebit_dbo__fn_diagramobjects.sql

CREATE OR REPLACE FUNCTION "livebit_dbo"."fn_diagramobjects"()
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
    -- ---- converted from T-SQL procedure dbo.fn_diagramobjects ----
    N'dbo'
    	AS
    	BEGIN
    		declare id_upgraddiagrams		int
    		declare id_sysdiagrams			int
    		declare id_helpdiagrams		int
    		declare id_helpdiagramdefinition	int
    		declare id_creatediagram	int
    		declare id_renamediagram	int
    		declare id_alterdiagram 	int 
    		declare id_dropdiagram		int
    		declare installedobjects	int

    		select installedobjects = 0

    		select 	id_upgraddiagrams = object_id(N'dbo.sp_upgraddiagrams'),
    			id_sysdiagrams = object_id(N'dbo.sysdiagrams'),
    			id_helpdiagrams = object_id(N'dbo.sp_helpdiagrams'),
    			id_helpdiagramdefinition = object_id(N'dbo.sp_helpdiagramdefinition'),
    			id_creatediagram = object_id(N'dbo.sp_creatediagram'),
    			id_renamediagram = object_id(N'dbo.sp_renamediagram'),
    			id_alterdiagram = object_id(N'dbo.sp_alterdiagram'), 
    			id_dropdiagram = object_id(N'dbo.sp_dropdiagram')

    		if id_upgraddiagrams is not null
    			select installedobjects = installedobjects + 1
    		if id_sysdiagrams is not null
    			select installedobjects = installedobjects + 2
    		if id_helpdiagrams is not null
    			select installedobjects = installedobjects + 4
    		if id_helpdiagramdefinition is not null
    			select installedobjects = installedobjects + 8
    		if id_creatediagram is not null
    			select installedobjects = installedobjects + 16
    		if id_renamediagram is not null
    			select installedobjects = installedobjects + 32
    		if id_alterdiagram  is not null
    			select installedobjects = installedobjects + 64
    		if id_dropdiagram is not null
    			select installedobjects = installedobjects + 128
		
    		return installedobjects 
    	END
END;
$function$;
