-- Generated by dbmigration.
-- Procedure divaconfig.sp_GetStoredProcedureLog -> livebit_divaconfig.sp_getstoredprocedurelog
-- Original source: source/routines/livebit_divaconfig__sp_getstoredprocedurelog.sql

CREATE OR REPLACE FUNCTION "livebit_divaconfig"."sp_getstoredprocedurelog"(proceduretabid integer, procedureid integer)
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
    -- ---- converted from T-SQL procedure divaconfig.sp_GetStoredProcedureLog ----
    SELECT   
            [ProcedureExecutionStatus] AS 'Status',
            [ProcedureExecutionStart] AS 'StartedAt',
            [ProcedureExecutionEnd] AS 'EndedAt',
            [ProcedureErrorMessage] AS 'ErrorMessage'
        FROM [divaconfig].[StoredProcedureExecutionLog] l
        LEFT JOIN [divaconfig].[StoredProcedures] p
            ON l.[ProcedureID] = p.[ProcedureID]
        WHERE l.[ProcedureTabID] = proceduretabid
          AND l.[ProcedureID] = procedureid
        ORDER BY ProcedureExecutionEnd DESC;

    --SELECT   
    --	  [ProcedureExecutionStatus] As 'Status'
    --      ,[ProcedureExecutionStart] As 'StartedAt'
    --      ,[ProcedureExecutionEnd] As 'EndedAt'
    --,[ProcedureErrorMessage] As 'ErrorMessage'
    --  FROM [divaconfig].[StoredProcedureExecutionLog] l
    --  left join [divaconfig].[StoredProcedures] p
    --  on l.[ProcedureID]=p.[ProcedureID]
    --  Where ProcedureTabID=1--Subtab ID
    --  and l.[ProcedureID]=18--Procedure ID
    --   order by ProcedureExecutionEnd desc
END;
$function$;
