-- Generated by dbmigration.
-- Procedure divaconfig.MasterExecuteProcedure -> livebit_divaconfig.masterexecuteprocedure
-- Original source: source/routines/livebit_divaconfig__masterexecuteprocedure.sql

CREATE OR REPLACE FUNCTION "livebit_divaconfig"."masterexecuteprocedure"(userid integer, subtabid integer, procedurename text, parameters text DEFAULT NULL, debug boolean DEFAULT 0 -- Set this to 1 for debugging)
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
    -- REVIEW (manual): sp_executesql — port to EXECUTE ... USING  [sp_executesql]
    -- REVIEW (manual): temp table (#tmp) — use a real or TEMP table / CTE  [#Read]
    -- REVIEW (manual): temp table (#tmp) — use a real or TEMP table / CTE  [#divaconfig]
    -- REVIEW (manual): temp table (#tmp) — use a real or TEMP table / CTE  [#Read]
    -- REVIEW (manual): temp table (#tmp) — use a real or TEMP table / CTE  [#divaconfig]
    -- REVIEW (manual): TRY/CATCH — port to BEGIN ... EXCEPTION WHEN OTHERS  [TRY]
    -- REVIEW (manual): TRY/CATCH — port to BEGIN ... EXCEPTION WHEN OTHERS  [TRY]
    -- REVIEW (manual): TRY/CATCH — port to BEGIN ... EXCEPTION WHEN OTHERS  [CATCH]
    -- REVIEW (manual): TRY/CATCH — port to BEGIN ... EXCEPTION WHEN OTHERS  [CATCH]
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- ---- converted from T-SQL procedure divaconfig.MasterExecuteProcedure ----
    --exec divaconfig.MasterExecuteProcedure 1,1,'divaconfig.sp_DynamicCRUD','null!@#Read!@#divaconfig.SampleData',0
    --TBD parameter dot 
    -- --Debugging Block: Uncomment to test the procedure
    --DECLARE
    --    userid INT = 1,
    --    subtabid INT = 1, -- SubTab ID for tracking execution source
    --    procedurename NVARCHAR(255) = 'divaconfig.sp_DynamicCRUD', -- Stored procedure to execute
    --    parameters NVARCHAR(MAX) = 'null!@#Read!@#divaconfig.SampleData', -- Delimited parameters for testing
    --	debug BIT = 0 -- Set this to 1 for debugging, 0 to suppress debugging

    DECLARE sql NVARCHAR(MAX);
    DECLARE paramlist NVARCHAR(MAX) = '';
    DECLARE delimiter NVARCHAR(10) = '!@#'; -- Delimiter for splitting parameters
    DECLARE procedureid INT;
    DECLARE executionstart DATETIME = now();

    -- Step 1: Validate ProcedureID
    SELECT procedureid = ProcedureID
    FROM divaconfig.StoredProcedures
    WHERE ProcedureName = procedurename;

    IF debug = 1
        PRINT 'ProcedureID: ' + COALESCE(CAST(procedureid AS NVARCHAR), 'NULL');

    IF procedureid IS NULL
    BEGIN
        PRINT 'Procedure ID not found.';
        RETURN;
    END

    -- Step 2: Validate User Permissions
    IF NOT EXISTS (
        SELECT 1
        FROM divaconfig.StoredProcedureAccess
        WHERE UserID = userid AND ProcedureID = procedureid AND HasExecuteAccess = 1 AND Type2Active = 1
    )
    BEGIN
        PRINT 'Permission Denied: User does not have access.';
        RETURN;
    END

    IF debug = 1
        PRINT 'User permissions validated.';

    -- Step 3: Fetch Stored Procedure Parameters
    DECLARE procedureparameters TABLE (
        ParameterName NVARCHAR(255),
        ParameterDataType NVARCHAR(50),
        ParameterIsOptional BIT,
        ParameterDefaultValue NVARCHAR(MAX)
    );

    INSERT INTO procedureparameters
    SELECT ParameterName, ParameterDataType, ParameterIsOptional, ParameterDefaultValue
    FROM divaconfig.StoredProcedureParameters
    WHERE ProcedureID = procedureid;

    IF debug = 1
    BEGIN
        PRINT 'Fetched Procedure Parameters:';
        SELECT * FROM procedureparameters;
    END

    -- Parse Input Parameters
    DECLARE inputparameters TABLE (
        ParameterIndex INT,
        ParameterValue NVARCHAR(MAX)
    );

    DECLARE index INT = 1;

    -- Ensure parameters is not NULL or empty before parsing
    IF parameters IS NOT NULL AND length(parameters) > 0
    BEGIN
        WHILE CHARINDEX(delimiter, parameters) > 0
        BEGIN
            -- Safeguard LEFT and SUBSTRING functions with valid indices
            IF CHARINDEX(delimiter, parameters) - 1 > 0
            BEGIN
                INSERT INTO inputparameters
                VALUES (index, LEFT(parameters, CHARINDEX(delimiter, parameters) - 1));
            END

            SET parameters = SUBSTRING(parameters, CHARINDEX(delimiter, parameters) + length(delimiter), length(parameters));
            SET index = index + 1;
        END

        -- Add the last parameter if it exists
        IF length(parameters) > 0
            INSERT INTO inputparameters
            VALUES (index, parameters);
    END

    IF debug = 1
    BEGIN
        PRINT 'Parsed Input Parameters:';
        SELECT * FROM inputparameters;
    END

    -- Step 4: Build Parameter List Dynamically
    DECLARE currentparam NVARCHAR(255);
    DECLARE currentvalue NVARCHAR(MAX);
    DECLARE currentisoptional BIT;
    DECLARE currentdefaultvalue NVARCHAR(MAX);

    DECLARE paramindex INT = 1;

    WHILE EXISTS (
        SELECT 1
        FROM procedureparameters
        WHERE ParameterName = (SELECT ParameterName FROM (
            SELECT ROW_NUMBER() OVER (ORDER BY ParameterName) AS RowNum, ParameterName
            FROM procedureparameters
        ) Ranked WHERE RowNum = paramindex)
    )
    BEGIN
        SELECT 
            currentparam = ParameterName,
            currentisoptional = ParameterIsOptional,
            currentdefaultvalue = ParameterDefaultValue
        FROM procedureparameters
        WHERE ParameterName = (SELECT ParameterName FROM (
            SELECT ROW_NUMBER() OVER (ORDER BY ParameterName) AS RowNum, ParameterName
            FROM procedureparameters
        ) Ranked WHERE RowNum = paramindex);

        SELECT currentvalue = ParameterValue
        FROM inputparameters
        WHERE ParameterIndex = paramindex;

        IF debug = 1
            PRINT 'Processing Parameter: ' + currentparam + ', Value: ' + COALESCE(currentvalue, 'NULL');

        IF currentvalue IS NULL AND currentisoptional = 1
        BEGIN
            SET currentvalue = currentdefaultvalue;
        END

        IF currentvalue IS NULL AND currentisoptional = 0
        BEGIN
            PRINT 'Missing required parameter: ' + currentparam;
            RETURN;
        END

        IF currentvalue IS NOT NULL
    BEGIN
        IF LOWER(currentvalue) = 'null'
    		BEGIN
    			SET paramlist = paramlist + currentparam + ' = NULL, '
    			Print 'IF paramlist='+paramlist
    		END
        ELSE
    	BEGIN
    		SET paramlist = paramlist + currentparam + ' = ''' + REPLACE(currentvalue, '''', '''''') + ''', ';
    		Print 'ELSE paramlist='+paramlist
    	End
    END

        SET paramindex = paramindex + 1;
    END

    -- Remove trailing comma
    IF RIGHT(paramlist, 2) = ', '
        SET paramlist = LEFT(paramlist, length(paramlist) - 1);

    IF debug = 1
        PRINT 'Generated Parameter List: ' + paramlist;

    -- Step 5: Build and Execute SQL
    SET sql = 'EXEC ' + procedurename;
    IF length(paramlist) > 0
        SET sql = sql + ' ' + paramlist;

    IF debug = 1
        PRINT 'Generated SQL: ' + sql;

    BEGIN TRY
        EXEC sp_executesql sql;
        PRINT 'SQL Execution Successful.';

        INSERT INTO divaconfig.StoredProcedureExecutionLog (
            ProcedureID,
            ProcedureTabID,
            ProcedureExecutedBy,
            ProcedureExecutionStart,
            ProcedureExecutionEnd,
            ProcedureParametersUsed,
            ProcedureExecutionStatus,
            ProcedureErrorMessage
        )
        VALUES (
            procedureid,
            subtabid,
            userid,
            executionstart,
            now(),
            parameters,
            'Success',
            NULL
        );
    END TRY
    BEGIN CATCH
        IF debug = 1 
            PRINT 'Error Occurred: ' + ERROR_MESSAGE();
        ELSE
            SELECT 'Error Occurred: ' + ERROR_MESSAGE() AS ErrorMessage;

        INSERT INTO divaconfig.StoredProcedureExecutionLog (
            ProcedureID,
            ProcedureTabID,
            ProcedureExecutedBy,
            ProcedureExecutionStart,
            ProcedureExecutionEnd,
            ProcedureParametersUsed,
            ProcedureExecutionStatus,
            ProcedureErrorMessage
        )
        VALUES (
            procedureid,
            subtabid,
            userid,
            executionstart,
            now(),
            parameters,
            'Failed',
            ERROR_MESSAGE()
        );
    END CATCH;
END;
$function$;
