-- Generated by dbmigration.
-- Procedure divaconfig.uspLogCustomSP -> livebit_divaconfig.usplogcustomsp
-- Original source: source/routines/livebit_divaconfig__usplogcustomsp.sql

CREATE OR REPLACE FUNCTION "livebit_divaconfig"."usplogcustomsp"(inputstoredprocedureexecutionid text, inputstoredprocedurename text, inputtransactiontype text, inputbatchid bigint, inputstoredprocedureparameterall text, executioncontext text DEFAULT NULL, executionsqcontext integer DEFAULT NULL, executionpipelinecontext text DEFAULT NULL, azurecorrelationid text DEFAULT NULL, errormessage text DEFAULT NULL, errorseverity integer DEFAULT NULL, errorline integer DEFAULT NULL)
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
    -- REVIEW (manual): TRY/CATCH — port to BEGIN ... EXCEPTION WHEN OTHERS  [TRY]
    -- REVIEW (manual): TRY/CATCH — port to BEGIN ... EXCEPTION WHEN OTHERS  [CATCH]
    -- REVIEW (manual): TRY/CATCH — port to BEGIN ... EXCEPTION WHEN OTHERS  [TRY]
    -- REVIEW (manual): TRY/CATCH — port to BEGIN ... EXCEPTION WHEN OTHERS  [TRY]
    -- REVIEW (manual): TRY/CATCH — port to BEGIN ... EXCEPTION WHEN OTHERS  [CATCH]
    -- REVIEW (manual): TRY/CATCH — port to BEGIN ... EXCEPTION WHEN OTHERS  [CATCH]
    -- REVIEW (manual): TOP n — rewrite as LIMIT n  [TOP 1]
    -- REVIEW (manual): TOP n — rewrite as LIMIT n  [TOP 1]
    -- ---- converted from T-SQL procedure divaconfig.uspLogCustomSP ----
    BEGIN
        DECLARE starttime          DATETIME2 = (now() at time zone 'utc');
        DECLARE executiontime      INT;
        DECLARE cputime            BIGINT;
        DECLARE elapsedtime        BIGINT;
        DECLARE logicalreads       BIGINT;
        DECLARE physicalreads      BIGINT;
        DECLARE logicalwrites      BIGINT;
        DECLARE executioncount     INT;
        DECLARE maxgrantkb         BIGINT;
        DECLARE maxusedgrantkb     BIGINT;
        DECLARE sessionid          NVARCHAR(50);
        DECLARE loginnamesession   NVARCHAR(128);
        DECLARE programname        NVARCHAR(128);
        DECLARE client_net_address NVARCHAR(128);

        -- Use TRY-CATCH to log execution and errors
        BEGIN TRY
            -- Capture resource usage (CPU time, reads, writes, physical reads, execution count, memory grants, elapsed time)
            SELECT TOP 1 
                cputime        = total_worker_time,
                elapsedtime    = total_elapsed_time,
                logicalreads   = total_logical_reads,
                physicalreads  = total_physical_reads,
                logicalwrites  = total_logical_writes,
                executioncount = execution_count,
                maxgrantkb     = max_grant_kb,
                maxusedgrantkb = max_used_grant_kb
            FROM sys.dm_exec_query_stats AS qs
            CROSS APPLY sys.dm_exec_sql_text(qs.sql_handle)
            WHERE qs.sql_handle IS NOT NULL;

            -- Capture session details
            SELECT TOP 1
                sessionid         = CAST(s.session_id AS NVARCHAR(50)), 
                loginnamesession  = s.login_name,
                programname       = s.program_name,
                client_net_address = c.client_net_address
            FROM sys.dm_exec_sessions s
            JOIN sys.dm_exec_connections c ON s.session_id = c.session_id
            WHERE s.session_id = @spid;

            -- Calculate execution time in milliseconds
            SET executiontime = DATEDIFF(MILLISECOND, starttime, (now() at time zone 'utc'));

        END TRY
        BEGIN CATCH
            -- Capture error details in case of failure
            SET errormessage  = ERROR_MESSAGE();
            SET errorseverity = ERROR_SEVERITY();
            SET errorline     = ERROR_LINE();
        END CATCH;

        -- Insert log into the [LogCustomeSp] table, logging every execution and error details
        INSERT INTO [divaconfig].[LogCustomeSp] (
            [ID],
            [StoredProcedureExecutionID],
            [BatchId],
            [StoredProcedureName],
            [StoredProcedureParameterAll],
            [LoginName],
            [ClientId],
            [AppName],
            [TransactionStartDateTime],
            [TransactionEndDateTime],
            [TransactionType],
            [Spid],
            [ErrorMessage],
            [ErrorSeverity],        -- Log error severity
            [ErrorLine],            -- Log the line number where the error occurred
            [ExecutionTime],
            [CpuTime],               
            [ElapsedTime],            
            [LogicalReads],          
            [PhysicalReads],        
            [LogicalWrites],         
            [ExecutionCount],        
            [MaxGrantKb],            
            [MaxUsedGrantKb],       
            [AzureCorrelationId],    
            [sessionId],             
            [loginNameSession],      
            [programName],           
            [client_net_address],    
            [ExecutionContext],      
            [ExecutionSqContext],    
            [ExecutionPipelineContext]
        )
        VALUES (
            gen_random_uuid(),
            inputstoredprocedureexecutionid,
            inputbatchid,
            inputstoredprocedurename,
            inputstoredprocedureparameterall,
            loginnamesession,
            client_net_address,
            programname,
            starttime,
            (now() at time zone 'utc'),
            inputtransactiontype,
            @spid,
            errormessage,           -- Logging actual error message
            errorseverity,          -- Logging error severity
            errorline,              -- Logging error line number
            executiontime,   
            cputime,         
            elapsedtime,     
            logicalreads,    
            physicalreads,   
            logicalwrites,   
            executioncount,  
            maxgrantkb,      
            maxusedgrantkb,  
            azurecorrelationid,
            sessionid,
            loginnamesession,
            programname,
            client_net_address,
            executioncontext,
            executionsqcontext,
            executionpipelinecontext
        );
    END;
END;
$function$;
