-- Generated by dbmigration.
-- Procedure dbo.sp_alterdiagram -> livebit_dbo.sp_alterdiagram
-- Original source: source/routines/livebit_dbo__sp_alterdiagram.sql

CREATE OR REPLACE FUNCTION "livebit_dbo"."sp_alterdiagram"(diagramname text, owner_id integer DEFAULT null, version integer, definition bytea)
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
    -- ---- converted from T-SQL procedure dbo.sp_alterdiagram ----
    'dbo'
    	AS
    	BEGIN
    		set nocount on
	
    		declare theid 			int
    		declare retval 		int
    		declare isdbo 			int
		
    		declare uidfound 		int
    		declare diagid			int
    		declare shouldchangeuid	int
	
    		if(diagramname is null)
    		begin
    			RAISERROR ('Invalid ARG', 16, 1)
    			return -1
    		end
	
    		execute as caller;
    		select theid = DATABASE_PRINCIPAL_ID();	 
    		select isdbo = IS_MEMBER(N'db_owner'); 
    		if(owner_id is null)
    			select owner_id = theid;
    		revert;
	
    		select shouldchangeuid = 0
    		select diagid = diagram_id, uidfound = principal_id from dbo.sysdiagrams where principal_id = owner_id and name = diagramname 
		
    		if(diagid IS NULL or (isdbo = 0 and theid <> uidfound))
    		begin
    			RAISERROR ('Diagram does not exist or you do not have permission.', 16, 1);
    			return -3
    		end
	
    		if(isdbo <> 0)
    		begin
    			if(uidfound is null or USER_NAME(uidfound) is null) -- invalid principal_id
    			begin
    				select shouldchangeuid = 1 ;
    			end
    		end

    		-- update dds data			
    		update dbo.sysdiagrams set definition = definition where diagram_id = diagid ;

    		-- change owner
    		if(shouldchangeuid = 1)
    			update dbo.sysdiagrams set principal_id = theid where diagram_id = diagid ;

    		-- update dds version
    		if(version is not null)
    			update dbo.sysdiagrams set version = version where diagram_id = diagid ;

    		return 0
    	END
END;
$function$;
