-- Generated by dbmigration.
-- Procedure divadim.LoadDateDimension -> livebit_divadim.loaddatedimension
-- Original source: source/routines/livebit_divadim__loaddatedimension.sql

CREATE OR REPLACE FUNCTION "livebit_divadim"."loaddatedimension"(startdate date DEFAULT '20250101', numberofyears integer DEFAULT 1)
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
    -- ---- converted from T-SQL procedure divadim.LoadDateDimension ----
    --exec divadim.LoadDateDimension '20200101',10
     --Declare   startdate DATE = '20250101',
     --   numberofyears INT = 1
        -- Set consistent settings
        SET DATEFIRST 7;
        SET DATEFORMAT mdy;
        SET LANGUAGE us_english;

    	DELETE FROM divadim.DateDimension
    	WHERE  [Year] = YEAR(startdate);


        -- Calculate the cutoff date
        DECLARE cutoffdate DATE = DATEADD(YEAR, numberofyears, startdate);

        -- Drop and recreate the DateDimension table
        IF OBJECT_ID('divadim.DateDimension', 'U') IS NOT NULL
            DROP TABLE divadim.DateDimension;

        CREATE TABLE divadim.DateDimension
        (
            DateKey             INT         NOT NULL PRIMARY KEY,
            [Date]              DATE        NOT NULL,
            [Day]               TINYINT     NOT NULL,
            DaySuffix           CHAR(2)     NOT NULL,
            [Weekday]           TINYINT     NOT NULL,
            WeekDayName         VARCHAR(10) NOT NULL,
            WeekdayAbbreviation CHAR(3)     NOT NULL,
            IsWeekend           BIT         NOT NULL,
            IsHoliday           BIT         DEFAULT 0 NOT NULL,
            HolidayText         VARCHAR(64) SPARSE,
            FiscalYear          INT         NOT NULL,
            FiscalQuarter       TINYINT     NOT NULL,
            HalfYear            TINYINT     NOT NULL,
            Season              VARCHAR(10) NOT NULL,
            WeekOfYear          TINYINT     NOT NULL,
            [Month]             TINYINT     NOT NULL,
            [MonthName]         VARCHAR(10) NOT NULL,
            [Quarter]           TINYINT     NOT NULL,
            [Year]              INT         NOT NULL,
            FirstDayOfMonth     DATE        NOT NULL,
            LastDayOfMonth      DATE        NOT NULL
        );

        -- Populate the DateDimension table using a WHILE loop
        DECLARE currentdate DATE = startdate;

        WHILE currentdate < cutoffdate
        BEGIN
            INSERT INTO divadim.DateDimension
            (
                DateKey,
                [Date],
                [Day],
                DaySuffix,
                [Weekday],
                WeekDayName,
                WeekdayAbbreviation,
                IsWeekend,
                FiscalYear,
                FiscalQuarter,
                HalfYear,
                Season,
                WeekOfYear,
                [Month],
                [MonthName],
                [Quarter],
                [Year],
                FirstDayOfMonth,
                LastDayOfMonth
            )
            SELECT
                DateKey       = CONVERT(INT, CONVERT(CHAR(8), currentdate, 112)),
                [Date]        = currentdate,
                [Day]         = DAY(currentdate),
                DaySuffix     = CASE 
                                  WHEN DAY(currentdate) IN (1, 21, 31) THEN 'st'
                                  WHEN DAY(currentdate) IN (2, 22) THEN 'nd'
                                  WHEN DAY(currentdate) IN (3, 23) THEN 'rd'
                                  ELSE 'th' END,
                [Weekday]     = DATEPART(WEEKDAY, currentdate),
                WeekDayName   = DATENAME(WEEKDAY, currentdate),
                WeekdayAbbreviation = LEFT(DATENAME(WEEKDAY, currentdate), 3),
                IsWeekend     = CASE WHEN DATEPART(WEEKDAY, currentdate) IN (1, 7) THEN 1 ELSE 0 END,
                FiscalYear    = YEAR(currentdate), -- Adjust if fiscal year differs
                FiscalQuarter = DATEPART(QUARTER, currentdate),
                HalfYear      = CASE WHEN MONTH(currentdate) <= 6 THEN 1 ELSE 2 END,
                Season        = CASE 
                                  WHEN MONTH(currentdate) IN (12, 1, 2) THEN 'Winter'
                                  WHEN MONTH(currentdate) IN (3, 4, 5) THEN 'Spring'
                                  WHEN MONTH(currentdate) IN (6, 7, 8) THEN 'Summer'
                                  WHEN MONTH(currentdate) IN (9, 10, 11) THEN 'Autumn' END,
                WeekOfYear    = DATEPART(WEEK, currentdate),
                [Month]       = MONTH(currentdate),
                [MonthName]   = DATENAME(MONTH, currentdate),
                [Quarter]     = DATEPART(QUARTER, currentdate),
                [Year]        = YEAR(currentdate),
                FirstDayOfMonth = DATEADD(MONTH, DATEDIFF(MONTH, 0, currentdate), 0),
                LastDayOfMonth  = EOMONTH(currentdate);

            SET currentdate = DATEADD(DAY, 1, currentdate);
        END;

        -- Populate IsHoliday and HolidayText
        UPDATE divadim.DateDimension
        SET IsHoliday = 1, HolidayText = 'New Year''s Day'
        WHERE MONTH([Date]) = 1 AND DAY([Date]) = 1;



    	--Select * from divadim.DateDimension
END;
$function$;
