-- Generated by dbmigration.
-- Procedure divaconfig.uspSampleErrorProcessData -> livebit_divaconfig.uspsampleerrorprocessdata
-- Original source: source/routines/livebit_divaconfig__uspsampleerrorprocessdata.sql

CREATE OR REPLACE FUNCTION "livebit_divaconfig"."uspsampleerrorprocessdata"()
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
    -- REVIEW (manual): TRY/CATCH — port to BEGIN ... EXCEPTION WHEN OTHERS  [TRY]
    -- REVIEW (manual): TRY/CATCH — port to BEGIN ... EXCEPTION WHEN OTHERS  [TRY]
    -- REVIEW (manual): TRY/CATCH — port to BEGIN ... EXCEPTION WHEN OTHERS  [CATCH]
    -- REVIEW (manual): TRY/CATCH — port to BEGIN ... EXCEPTION WHEN OTHERS  [CATCH]
    -- ---- converted from T-SQL procedure divaconfig.uspSampleErrorProcessData ----
    BEGIN
        -- Generate a new Execution ID for logging
        DECLARE executionid UNIQUEIDENTIFIER = gen_random_uuid();
        DECLARE errormessage NVARCHAR(MAX);
        DECLARE errorseverity INT;
        DECLARE errorline INT;

        -- Start logging the execution details (before the process starts)
        EXEC [divaconfig].[uspLogCustomSP]
            inputstoredprocedureexecutionid = executionid,
            inputstoredprocedurename = 'uspSampleProcessData',
            inputtransactiontype = 'Start-INSERT',
            inputbatchid = 2002,
            inputstoredprocedureparameterall = 'ProcessType=DataLoad;RecordID=2024',
            executioncontext = 'Starting data load operation for records',
            executionsqcontext = 101,
            executionpipelinecontext = 'ETL Pipeline Execution',
            azurecorrelationid = executionid;

        -- Actual processing logic of the stored procedure (for example, data load)
        BEGIN TRY
            -- Simulate a data processing step (e.g., data load or manipulation)
            -- In reality, replace this with your business logic
            WAITFOR DELAY '00:00:05'; -- Simulates 5 seconds of processing
        
            -- FORCED ERROR: This will simulate a critical error during the process
            RAISERROR('Simulated critical error during data load operation.', 16, 1);

            -- If no error, log success at the end of the operation (this will be skipped due to the error)
            EXEC [divaconfig].[uspLogCustomSP]
                inputstoredprocedureexecutionid = executionid,
                inputstoredprocedurename = 'uspSampleProcessData',
                inputtransactiontype = 'End-SUCCESS',
                inputbatchid = 2002,
                inputstoredprocedureparameterall = 'ProcessType=DataLoad;RecordID=2024',
                executioncontext = 'Data load operation for records completed successfully',
                executionsqcontext = 101,
                executionpipelinecontext = 'ETL Pipeline Execution',
                azurecorrelationid = executionid;
        END TRY
        BEGIN CATCH
            -- Capture the error details
            SET errormessage = ERROR_MESSAGE();
            SET errorseverity = ERROR_SEVERITY();
            SET errorline = ERROR_LINE();
        
            -- Log the error details
            EXEC [divaconfig].[uspLogCustomSP]
                inputstoredprocedureexecutionid = executionid,
                inputstoredprocedurename = 'uspSampleProcessData',
                inputtransactiontype = 'End-ERROR',
                inputbatchid = 2002,
                inputstoredprocedureparameterall = 'ProcessType=DataLoad;RecordID=2024',
                executioncontext = 'Data load operation failed due to error',
                executionsqcontext = 101,
                executionpipelinecontext = 'ETL Pipeline Execution',
                azurecorrelationid = executionid,
                errormessage = errormessage, -- Log captured error message
                errorseverity =errorseverity,             -- Log error severity (0 as default)
                errorline = errorline;                    -- Log error line number (-1 as default)

            -- Optionally, re-throw the error to propagate it
            THROW;
        END CATCH;
    END;
END;
$function$;
