-- Generated by dbmigration.
-- Procedure divaconfig.uspSampleMainProcess -> livebit_divaconfig.uspsamplemainprocess
-- Original source: source/routines/livebit_divaconfig__uspsamplemainprocess.sql

CREATE OR REPLACE FUNCTION "livebit_divaconfig"."uspsamplemainprocess"()
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
    -- REVIEW (manual): TRY/CATCH — port to BEGIN ... EXCEPTION WHEN OTHERS  [TRY]
    -- REVIEW (manual): TRY/CATCH — port to BEGIN ... EXCEPTION WHEN OTHERS  [TRY]
    -- REVIEW (manual): TRY/CATCH — port to BEGIN ... EXCEPTION WHEN OTHERS  [CATCH]
    -- REVIEW (manual): TRY/CATCH — port to BEGIN ... EXCEPTION WHEN OTHERS  [CATCH]
    -- ---- converted from T-SQL procedure divaconfig.uspSampleMainProcess ----
    BEGIN
        -- Generate a new Execution ID for logging
        DECLARE executionid UNIQUEIDENTIFIER = gen_random_uuid();

        -- Start logging for the parent procedure
        EXEC [divaconfig].[uspLogCustomSP]
            inputstoredprocedureexecutionid = executionid,
            inputstoredprocedurename = 'uspMainProcess',
            inputtransactiontype = 'Start-PROCESS',
            inputbatchid = 3003,
            inputstoredprocedureparameterall = 'ProcessID=3003',
            executioncontext = 'Main process initiation',
            executionsqcontext = 303,
            executionpipelinecontext = 'Main Process',
            azurecorrelationid = executionid;

        -- Call the child procedure that internally logs its own process
        BEGIN TRY
            -- Call the child process (e.g., uspProcessData)
            EXEC [divaconfig].[uspSampleProcessData];

            -- Log success after the child procedure finishes successfully
            EXEC [divaconfig].[uspLogCustomSP]
                inputstoredprocedureexecutionid = executionid,
                inputstoredprocedurename = 'uspMainProcess',
                inputtransactiontype = 'End-SUCCESS',
                inputbatchid = 3003,
                inputstoredprocedureparameterall = 'ProcessID=3003',
                executioncontext = 'Main process completed successfully',
                executionsqcontext = 303,
                executionpipelinecontext = 'Main Process',
                azurecorrelationid = executionid;
        END TRY
        BEGIN CATCH
            -- Log error if something goes wrong
            EXEC [divaconfig].[uspLogCustomSP]
                inputstoredprocedureexecutionid = executionid,
                inputstoredprocedurename = 'uspMainProcess',
                inputtransactiontype = 'End-ERROR',
                inputbatchid = 3003,
                inputstoredprocedureparameterall = 'ProcessID=3003',
                executioncontext = 'Main process failed',
                executionsqcontext = 303,
                executionpipelinecontext = 'Main Process',
                azurecorrelationid = executionid;

            -- Optionally, re-throw the error to propagate it
            THROW;
        END CATCH;
    END;
END;
$function$;
