-- Generated by dbmigration.
-- Procedure divaconfig.LoadAllTableColumnValue -> livebit_divaconfig.loadalltablecolumnvalue
-- Original source: source/routines/livebit_divaconfig__loadalltablecolumnvalue.sql

CREATE OR REPLACE FUNCTION "livebit_divaconfig"."loadalltablecolumnvalue"()
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
    -- REVIEW (manual): IDENTITY(...) in a query — verify sequence semantics  [IDENTITY(]
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- ---- converted from T-SQL procedure divaconfig.LoadAllTableColumnValue ----
    -- Step 1: Create a physical table to store schema.table names
        IF OBJECT_ID('[divaconfig].[TableList]', 'U') IS NOT NULL
            DROP TABLE [divaconfig].[TableList]; -- Drop the table if it exists
    
        CREATE TABLE [divaconfig].[TableList] (
            ID INT IDENTITY(1, 1) PRIMARY KEY, -- Unique identifier for iteration
            FullTableName NVARCHAR(256) NOT NULL -- Schema and table name
        );

        -- Step 2: Dynamically populate the table with schema.table names
        INSERT INTO [divaconfig].[TableList] (FullTableName)
        SELECT TABLE_SCHEMA + '.' + TABLE_NAME
        FROM INFORMATION_SCHEMA.TABLES
        WHERE TABLE_TYPE = 'BASE TABLE'; -- Adjust this filter if needed (e.g., to exclude system tables)

    	Select * from [divaconfig].[TableList]

        -- Step 3: Declare variables for the loop
        DECLARE currentid INT = 1; -- Start with the first ID
        DECLARE maxid INT; -- Store the maximum ID for the loop
        DECLARE tablename NVARCHAR(256); -- Store the current table name

        -- Get the maximum ID from the TableList
        SELECT maxid = MAX(ID) FROM [divaconfig].[TableList];

        -- Step 4: Process each table in a WHILE loop
        WHILE currentid <= maxid
        BEGIN
            -- Get the table name for the current ID
            SELECT tablename = FullTableName
            FROM [divaconfig].[TableList]
            WHERE ID = currentid;

            -- Check if a valid table name was found (to handle gaps in IDs)
            IF tablename IS NOT NULL
            BEGIN
                -- Call the procedure for processing one table
                EXEC [divaconfig].[Load1TableColumnValue] tablename;
            END

            -- Increment the ID
            SET currentid = currentid + 1;
        END;
END;
$function$;
