-- Generated by dbmigration.
-- Procedure divadim.LoadDateDimension_Combined -> livebit_divadim.loaddatedimension_combined
-- Original source: source/routines/livebit_divadim__loaddatedimension_combined.sql

CREATE OR REPLACE FUNCTION "livebit_divadim"."loaddatedimension_combined"()
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- ---- converted from T-SQL procedure divadim.LoadDateDimension_Combined ----
    --select * from divadim.DateDimension_Combined
    DECLARE startdate DATE = '2025-01-01';
    DECLARE enddate DATE = '2030-12-31';

    IF OBJECT_ID('divadim.DateDimension_Combined', 'U') IS NOT NULL
        DROP TABLE divadim.DateDimension_Combined;

    CREATE TABLE divadim.DateDimension_Combined (
        DateKey INT NOT NULL PRIMARY KEY,
        [Date] DATE NOT NULL,
        [Day] TINYINT NOT NULL,
        DaySuffix CHAR(2) NOT NULL,
        [Weekday] TINYINT NOT NULL,
        WeekDayName VARCHAR(10) NOT NULL,
        WeekdayAbbreviation CHAR(3) NOT NULL,
        WeekDayName_FirstLetter CHAR(1) NOT NULL,
        IsWeekend BIT NOT NULL,
        IsHoliday BIT NOT NULL DEFAULT 0,
        HolidayText VARCHAR(64) SPARSE NULL,
        SpecialDays VARCHAR(20) NULL,
        FiscalYear INT NOT NULL,
        FiscalQuarter TINYINT NOT NULL,
        FinancialMonth INT NULL,
        HalfYear TINYINT NOT NULL,
        Season VARCHAR(10) NOT NULL,
        WeekOfYear TINYINT NOT NULL,
        WeekOfMonth TINYINT NOT NULL,
        [Month] TINYINT NOT NULL,
        [MonthName] VARCHAR(10) NOT NULL,
        [MonthName_Short] CHAR(3) NOT NULL,
        [MonthName_FirstLetter] CHAR(1) NOT NULL,
        [Quarter] TINYINT NOT NULL,
        [QuarterName] VARCHAR(10) NOT NULL,
        [Year] INT NOT NULL,
        MMYYYY CHAR(6) NOT NULL,
        MonthYear CHAR(7) NOT NULL,
        FirstDayOfMonth DATE NOT NULL,
        LastDayOfMonth DATE NOT NULL,
        FirstDateofWeek DATE NOT NULL,
        LastDateofWeek DATE NOT NULL,
        FirstDateofQuater DATE NULL,
        LastDateofQuater DATE NULL,
        FirstDateofYear DATE NULL,
        LastDateofYear DATE NULL,
        DOWInMonth TINYINT NULL,
        DayOfYear SMALLINT NULL,
        CurrentYear SMALLINT NULL,
        CurrentQuater SMALLINT NULL,
        CurrentMonth SMALLINT NULL,
        CurrentWeek SMALLINT NULL,
        CurrentDay SMALLINT NULL
    );

    DECLARE currentdate DATE = startdate;

    WHILE currentdate <= enddate
    BEGIN
        INSERT INTO divadim.DateDimension_Combined
        SELECT
            DateKey = CONVERT(INT, CONVERT(CHAR(8), currentdate, 112)),
            [Date] = currentdate,
            [Day] = DAY(currentdate),
            DaySuffix = CASE 
                WHEN DAY(currentdate) IN (1, 21, 31) THEN 'st'
                WHEN DAY(currentdate) IN (2, 22) THEN 'nd'
                WHEN DAY(currentdate) IN (3, 23) THEN 'rd'
                ELSE 'th' END,
            [Weekday] = DATEPART(WEEKDAY, currentdate),
            WeekDayName = DATENAME(WEEKDAY, currentdate),
            WeekdayAbbreviation = LEFT(DATENAME(WEEKDAY, currentdate), 3),
            WeekDayName_FirstLetter = LEFT(DATENAME(WEEKDAY, currentdate), 1),
            IsWeekend = CASE WHEN DATEPART(WEEKDAY, currentdate) IN (1, 7) THEN 1 ELSE 0 END,
            IsHoliday = 0,
            HolidayText = NULL,
            SpecialDays = NULL,
            FiscalYear = YEAR(currentdate),
            FiscalQuarter = DATEPART(QUARTER, currentdate),
            FinancialMonth = MONTH(currentdate),
            HalfYear = CASE WHEN MONTH(currentdate) <= 6 THEN 1 ELSE 2 END,
            Season = CASE 
                WHEN MONTH(currentdate) IN (12, 1, 2) THEN 'Winter'
                WHEN MONTH(currentdate) IN (3, 4, 5) THEN 'Spring'
                WHEN MONTH(currentdate) IN (6, 7, 8) THEN 'Summer'
                ELSE 'Autumn' END,
            WeekOfYear = DATEPART(WEEK, currentdate),
            WeekOfMonth = DATEPART(WEEK, currentdate) - DATEPART(WEEK, DATEADD(MONTH, DATEDIFF(MONTH, 0, currentdate), 0)) + 1,
            [Month] = MONTH(currentdate),
            [MonthName] = DATENAME(MONTH, currentdate),
            [MonthName_Short] = UPPER(LEFT(DATENAME(MONTH, currentdate), 3)),
            [MonthName_FirstLetter] = LEFT(DATENAME(MONTH, currentdate), 1),
            [Quarter] = DATEPART(QUARTER, currentdate),
            [QuarterName] = CASE DATEPART(QUARTER, currentdate)
                                WHEN 1 THEN 'First'
                                WHEN 2 THEN 'Second'
                                WHEN 3 THEN 'Third'
                                ELSE 'Fourth' END,
            [Year] = YEAR(currentdate),
            MMYYYY = RIGHT('0' + CAST(MONTH(currentdate) AS VARCHAR(2)), 2) + CAST(YEAR(currentdate) AS VARCHAR(4)),
            MonthYear = CAST(YEAR(currentdate) AS VARCHAR(4)) + UPPER(LEFT(DATENAME(MONTH, currentdate), 3)),
            FirstDayOfMonth = DATEADD(MONTH, DATEDIFF(MONTH, 0, currentdate), 0),
            LastDayOfMonth = EOMONTH(currentdate),
            FirstDateofWeek = DATEADD(DAY, 1 - DATEPART(WEEKDAY, currentdate), currentdate),
            LastDateofWeek = DATEADD(DAY, 7 - DATEPART(WEEKDAY, currentdate), currentdate),
            FirstDateofQuater = DATEADD(QUARTER, DATEDIFF(QUARTER, 0, currentdate), 0),
            LastDateofQuater = DATEADD(DAY, -1, DATEADD(QUARTER, DATEDIFF(QUARTER, 0, currentdate) + 1, 0)),
            FirstDateofYear = CAST(CAST(YEAR(currentdate) AS VARCHAR(4)) + '-01-01' AS DATE),
            LastDateofYear = CAST(CAST(YEAR(currentdate) AS VARCHAR(4)) + '-12-31' AS DATE),
            DOWInMonth = DAY(currentdate),
            DayOfYear = DATEPART(DAYOFYEAR, currentdate),
            CurrentYear = DATEDIFF(YEAR, now(), currentdate),
            CurrentQuater = DATEDIFF(QUARTER, now(), currentdate),
            CurrentMonth = DATEDIFF(MONTH, now(), currentdate),
            CurrentWeek = DATEDIFF(WEEK, now(), currentdate),
            CurrentDay = DATEDIFF(DAY, now(), currentdate);

        SET currentdate = DATEADD(DAY, 1, currentdate);
    END;

    -- Optional: Populate fixed holidays
    UPDATE divadim.DateDimension_Combined SET IsHoliday = 1, HolidayText = 'New Year''s Day'
    WHERE MONTH([Date]) = 1 AND DAY([Date]) = 1;

    UPDATE divadim.DateDimension_Combined SET IsHoliday = 1, HolidayText = 'Christmas'
    WHERE MONTH([Date]) = 12 AND DAY([Date]) = 25;

    UPDATE divadim.DateDimension_Combined SET SpecialDays = 'Valentine''s Day'
    WHERE MONTH([Date]) = 2 AND DAY([Date]) = 14;
END;
$function$;
