-- Generated by dbmigration.
-- Procedure divaconfig.LoadDIVAMetadata -> livebit_divaconfig.loaddivametadata
-- Original source: source/routines/livebit_divaconfig__loaddivametadata.sql

CREATE OR REPLACE FUNCTION "livebit_divaconfig"."loaddivametadata"()
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
    -- ---- converted from T-SQL procedure divaconfig.LoadDIVAMetadata ----
    exec [divaconfig].[LoadTableInfo]
    --Select * from [divaconfig].[TableInfo]Where TableName like '%SampleEmployees%'
    exec [divaconfig].[LoadColumnInfo]
    --Select * from [divaconfig].[ColumnInfo] Where TableName like '%SampleEmployees%'

    --Update [divaconfig].[ColumnInfo]
    --SET IsLookupValue = 1
    --Where ColumnID=5280

    exec [divaconfig].[Load1TableColumnValue] 'dbo.SampleEmployees'
    --Select * from [divaconfig].[ColumnValue]Where TableName like '%SampleEmployees%'
END;
$function$;
