-- Generated by dbmigration.
-- Procedure dbo.sp_helpdiagrams -> livebit_dbo.sp_helpdiagrams
-- Original source: source/routines/livebit_dbo__sp_helpdiagrams.sql

CREATE OR REPLACE FUNCTION "livebit_dbo"."sp_helpdiagrams"(diagramname text DEFAULT NULL, owner_id integer DEFAULT NULL)
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
    -- ---- converted from T-SQL procedure dbo.sp_helpdiagrams ----
    N'dbo'
    	AS
    	BEGIN
    		DECLARE user sysname
    		DECLARE dbologin bit
    		EXECUTE AS CALLER;
    			SET user = USER_NAME();
    			SET dbologin = CONVERT(bit,IS_MEMBER('db_owner'));
    		REVERT;
    		SELECT
    			[Database] = DB_NAME(),
    			[Name] = name,
    			[ID] = diagram_id,
    			[Owner] = USER_NAME(principal_id),
    			[OwnerID] = principal_id
    		FROM
    			sysdiagrams
    		WHERE
    			(dbologin = 1 OR USER_NAME(principal_id) = user) AND
    			(diagramname IS NULL OR name = diagramname) AND
    			(owner_id IS NULL OR principal_id = owner_id)
    		ORDER BY
    			4, 5, 1
    	END
END;
$function$;
