-- Generated by dbmigration.
-- Procedure dbo.DMS_PostRunPatientConfig -> livebit_dbo.dms_postrunpatientconfig
-- Original source: source/routines/livebit_dbo__dms_postrunpatientconfig.sql

CREATE OR REPLACE FUNCTION "livebit_dbo"."dms_postrunpatientconfig"()
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
    -- REVIEW (manual): TOP n — rewrite as LIMIT n  [Top 10]
    -- REVIEW (manual): TOP n — rewrite as LIMIT n  [Top 10]
    -- REVIEW (manual): TOP n — rewrite as LIMIT n  [Top 10]
    -- REVIEW (manual): TOP n — rewrite as LIMIT n  [Top 10]
    -- REVIEW (manual): TOP n — rewrite as LIMIT n  [Top 10]
    -- REVIEW (manual): TOP n — rewrite as LIMIT n  [Top 10]
    -- ---- converted from T-SQL procedure dbo.DMS_PostRunPatientConfig ----
    Begin 


    IF OBJECT_ID('dbo.DMS_SAP_Patient_Base', 'U')				IS NOT NULL BEGIN	DROP TABLE dbo.DMS_SAP_Patient_Base			END 
    IF OBJECT_ID('dbo.DMS_SQL_Patient_Base', 'U')				IS NOT NULL BEGIN	DROP TABLE dbo.DMS_SQL_Patient_Base			END
    IF OBJECT_ID('dbo.DMS_SharePoint_Patient_Base', 'U')		IS NOT NULL BEGIN	DROP TABLE dbo.DMS_SharePoint_Patient_Base	END
    IF OBJECT_ID('dbo.DMS_FTP_Patient_Base', 'U')				IS NOT NULL BEGIN	DROP TABLE dbo.DMS_FTP_Patient_Base			END


    Select * INTO	DMS_SAP_Patient_Base			From DMS_SAP_Patient
    Select * INTO	DMS_SQL_Patient_Base			From DMS_SQL_Patient
    Select * INTO	DMS_SharePoint_Patient_Base		From DMS_SharePoint_Patient
    Select * INTO	DMS_FTP_Patient_Base			From DMS_FTP_Patient


    Select 'PRE Row Base Count SAP Patient' as 'RowType', Count(1) 'RowCount',Count(Distinct PatientID ) 'DistinctBP'	From DMS_SAP_Patient_Base UNION
    Select 'PRE Row Base Count SQL Patient' as 'RowType', Count(1) 'RowCount',Count(Distinct PatientID ) 'DistinctBP'	From DMS_SQL_Patient_Base UNION
    Select 'PRE Row Base Count ShP Patient' as 'RowType', Count(1) 'RowCount',Count(Distinct PatientID ) 'DistinctBP'	From DMS_SharePoint_Patient_Base UNION
    Select 'PRE Row Base Count FTP Patient' as 'RowType', Count(1) 'RowCount',Count(Distinct PatientID ) 'DistinctBP'	From DMS_FTP_Patient_Base

    --Adding a New Column to SAP
    IF NOT EXISTS (
        SELECT *
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_NAME = 'DMS_SAP_Patient'
        AND COLUMN_NAME = 'PatientName'
    )
    BEGIN
        ALTER TABLE DMS_SAP_Patient
        ADD PatientName VARCHAR(100);
    END


    Update DMS_SAP_Patient
    Set PatientName= COALESCE(FirstName,'NULL')+COALESCE(LastName,'NULL')


    --Updating NULL Values of SAP

    Update DMS_SAP_Patient	SET PatientName = 'NULL'		Where PatientName = ''			OR PatientName			IS NULL
    Update DMS_SAP_Patient	SET InsuranceProvider = 'NULL'	Where InsuranceProvider = ''	OR InsuranceProvider	IS NULL
    Update DMS_SAP_Patient	SET Allergies = 'NULL'			Where Allergies = ''			OR Allergies			IS NULL
    Update DMS_SAP_Patient	SET MedicalHistory = 'NULL'		Where MedicalHistory = ''		OR MedicalHistory		IS NULL
    Update DMS_SAP_Patient	SET InsuranceNumber = 'NULL'	Where InsuranceNumber = ''		OR InsuranceNumber		IS NULL


    --Adding a New Column to SQL
    IF NOT EXISTS (
        SELECT *
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_NAME = 'DMS_SQL_Patient'
        AND COLUMN_NAME = 'PatientName'
    )
    BEGIN
        ALTER TABLE DMS_SQL_Patient
        ADD PatientName VARCHAR(100);
    END

    Update DMS_SQL_Patient
    Set PatientName= COALESCE(FirstName,'NULL')+COALESCE(LastName,'NULL')

    --Updating NULL Values of SQL


    Update DMS_SQL_Patient	SET PatientName = 'NULL'		Where PatientName = ''			OR PatientName			IS NULL
    Update DMS_SQL_Patient	SET InsuranceProvider = 'NULL'	Where InsuranceProvider = ''	OR InsuranceProvider	IS NULL
    Update DMS_SQL_Patient	SET Allergies = 'NULL'			Where Allergies = ''			OR Allergies			IS NULL
    Update DMS_SQL_Patient	SET InsuranceNumber = 'NULL'	Where InsuranceNumber = ''		OR InsuranceNumber		IS NULL

    --Adding a New Column to SharePoint
    IF NOT EXISTS (
        SELECT *
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_NAME = 'DMS_SharePoint_Patient'
        AND COLUMN_NAME = 'PatientName'
    )
    BEGIN
        ALTER TABLE DMS_SharePoint_Patient
        ADD PatientName VARCHAR(100);
    END

    Update DMS_SharePoint_Patient
    Set PatientName= COALESCE(FirstName,'NULL')+COALESCE(LastName,'NULL')

    --Updating NULL Values of SharePoint

    --Update DMS_SharePoint_Patient	SET PatientID = 'NULL'			Where PatientID = ''			OR PatientID			IS NULL
    Update DMS_SharePoint_Patient	SET MedicalHistory = 'NULL'		Where MedicalHistory = ''		OR MedicalHistory		IS NULL



    --Adding a New Column to FTP
    IF NOT EXISTS (
        SELECT *
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_NAME = 'DMS_FTP_Patient'
        AND COLUMN_NAME = 'PatientName'
    )
    BEGIN
        ALTER TABLE DMS_FTP_Patient
        ADD PatientName VARCHAR(100);
    END

    Update DMS_FTP_Patient
    Set PatientName= COALESCE(FirstName,'NULL')+COALESCE(LastName,'NULL')

    --Updating NULL Values of FTP

    Update DMS_FTP_Patient	SET PatientName = 'NULL'		Where PatientName = ''			OR PatientName			IS NULL
    Update DMS_FTP_Patient	SET InsuranceProvider = 'NULL'	Where InsuranceProvider = ''	OR InsuranceProvider	IS NULL
    Update DMS_FTP_Patient	SET InsuranceNumber = 'NULL'	Where InsuranceNumber = ''		OR InsuranceNumber		IS NULL





    Exec DMS_FactL2PerConfig 4
    Exec DMS_FactL2PerConfig 5
    Exec DMS_FactL2PerConfig 6
    Exec DMS_FactL2PerConfig 7
    Exec DMS_FactL2PerConfig 8
    Exec DMS_FactL2PerConfig 9




    --Update l2
    --SET l2.KUNNR_P07			=rl.KUNNR_P07
    --,	l2.PARTNER_S4			=rl.PARTNER_S4
    --,	l2.CLASSIFICATION		=rl.CLASSIFICATION
    --,	l2.CONCLUSION_NEEDS_CC	=rl.CONCLUSION_NEEDS_CC
    --,l2.Filter9 = 'BP Exist in ZDCV_BRIM_RELEVANCY DIH'
    ----Select Count(*) 
    --from [DMS_FactL2Monitor] l2
    --Inner join [dbo].[ZDCV_BRIM_RELEVANCY] rl  on l2.BusinessPartner= rl.PARTNER_S4
    --Where l2.ConfigID IN (1,2,3)

    Update [DMS_FactL2Monitor]
    SET CONCLUSION_NEEDS_CC = 'Y'
    --[DMS_FactL2Monitor]
    Where FactL2ID NOT IN (Select Top 10 FactL2ID from [DMS_FactL2Monitor] Where ConfigID=4) and ConfigID IN (4)

    Update [DMS_FactL2Monitor]
    SET CONCLUSION_NEEDS_CC = 'Y'
    --[DMS_FactL2Monitor]
    Where FactL2ID NOT IN (Select Top 10 FactL2ID from [DMS_FactL2Monitor] Where ConfigID=5) and ConfigID IN (5)

    Update [DMS_FactL2Monitor]
    SET CONCLUSION_NEEDS_CC = 'Y'
    --[DMS_FactL2Monitor]
    Where FactL2ID NOT IN (Select Top 10 FactL2ID from [DMS_FactL2Monitor] Where ConfigID=6) and ConfigID IN (6)

    Update [DMS_FactL2Monitor]
    SET CONCLUSION_NEEDS_CC = 'Y'
    --[DMS_FactL2Monitor]
    Where FactL2ID NOT IN (Select Top 10 FactL2ID from [DMS_FactL2Monitor] Where ConfigID=7) and ConfigID IN (7)

    Update [DMS_FactL2Monitor]
    SET CONCLUSION_NEEDS_CC = 'Y'
    --[DMS_FactL2Monitor]
    Where FactL2ID NOT IN (Select Top 10 FactL2ID from [DMS_FactL2Monitor] Where ConfigID=8) and ConfigID IN (8)

    Update [DMS_FactL2Monitor]
    SET CONCLUSION_NEEDS_CC = 'Y'
    --[DMS_FactL2Monitor]
    Where FactL2ID NOT IN (Select Top 10 FactL2ID from [DMS_FactL2Monitor] Where ConfigID=9) and ConfigID IN (9)

    Update [DMS_FactL2Monitor]
    SET CONCLUSION_NEEDS_CC = 'N'
    Where CONCLUSION_NEEDS_CC is null


    Update [DMS_FactL2Monitor]  
    SET IsFilter = 'N'
    Where ConfigID IN (4,5,6,7,8,9)
    /*
    Update l2
    SET l2.Filter1 =  POSITION_END_DATE
    from [DMS_FactL2Monitor] l2 
    Inner join DMS_SAP_Patient N on l2.BusinessPartner = n.PatientID
    Where ConfigID = 30

    Update l2
    SET l2.Filter2 = ZZ_POSITION_END_DATE 
    from [DMS_FactL2Monitor] l2 
    Inner join DMS_SQL_Patient N on l2.BusinessPartner = n.PatientID
    Where ConfigID = 30

    Update l2
    SET l2.Filter3 = POSITION_START_DATE
    from [DMS_FactL2Monitor] l2 
    Inner join DMS_SharePoint_Patient N on l2.BusinessPartner = n.PatientID
    Where ConfigID = 31
    */

    /*
    Update l2
    SET l2.Filter6 = 
    from [DMS_FactL2Monitor] l2 
    Inner join SAPX40_R_KNA1_SALES_PSTN N on l2.BusinessPartner = n.KUNNR
    Where ConfigID = 34
    */

    --Update  [DMS_FactL2Monitor]
    --SET IsFilter = 'Y', FilterDetails ='SS_CUST_TYPE=55' 
    --Where 1=1 
    -- and  ConfigID IN (25,39)
    -- and Filter5 <> 'NULL'
    -- and Filter5 = 55
 

    --  DELETE
    ----Select COunt(*)
    --from [DMS_FactL2Monitor] 
    --Where ConfigValue='NULL' and IsINFA='1' and IsP40='1' and IsDIH='1' and IsP07='1'

 
    TRUNCATE TABLE dbo.DMS_FactL2Monitor_PatientConfig

    SET IDENTITY_INSERT dbo.DMS_FactL2Monitor_PatientConfig ON;

    INSERT INTO dbo.DMS_FactL2Monitor_PatientConfig
    ([FactL2ID], [LoadRunDateTime], [BusinessPartner], [ConfigID], [ConfigValue], [IsSAP], [IsSQL], [IsFTP], [IsSharePoint], [MatchStatus], [CompareCode], [CodeDescription], [BPEtEMatch], [FactL1ID], [CriteriaValue], [BRStatus], [BRIMRelevancy], [BPStatus], [IsFilter], [FilterDetails], [CLASSIFICATION], [CONCLUSION_NEEDS_CC], [Filter1], [Filter2], [Filter3], [Filter4], [Filter5], [KUNNR_P07], [PARTNER_S4], [Filter6], [Filter7], [Filter8], [Filter9], [Rank])
    Select   *, rank() OVER(Order BY FactL2ID) as [Rank] from [dbo].[DMS_FactL2Monitor] L2
    Where L2.configid  IN (4,5,6,7,8,9)

    SET IDENTITY_INSERT dbo.DMS_FactL2Monitor_PatientConfig OFF;


    END;
END;
$function$;
