-- Generated by dbmigration.
-- Procedure aidd.LoadViewInfo -> livebit_aidd.loadviewinfo
-- Original source: source/routines/livebit_aidd__loadviewinfo.sql

CREATE OR REPLACE FUNCTION "livebit_aidd"."loadviewinfo"(viewname text, viewschemaname text DEFAULT NULL)
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
    -- REVIEW (manual): sp_executesql — port to EXECUTE ... USING  [sp_executesql]
    -- REVIEW (manual): TRY/CATCH — port to BEGIN ... EXCEPTION WHEN OTHERS  [TRY]
    -- REVIEW (manual): TRY/CATCH — port to BEGIN ... EXCEPTION WHEN OTHERS  [TRY]
    -- REVIEW (manual): TRY/CATCH — port to BEGIN ... EXCEPTION WHEN OTHERS  [CATCH]
    -- REVIEW (manual): TRY/CATCH — port to BEGIN ... EXCEPTION WHEN OTHERS  [CATCH]
    -- REVIEW (manual): TOP n — rewrite as LIMIT n  [TOP 1]
    -- REVIEW (manual): TOP n — rewrite as LIMIT n  [TOP 1]
    -- REVIEW (manual): TOP n — rewrite as LIMIT n  [TOP 1]
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- ---- converted from T-SQL procedure aidd.LoadViewInfo ----
    BEGIN
        SET NOCOUNT ON;

        -------------------------------------------------------------------------
        -- Resolve schema & name
        -------------------------------------------------------------------------
        DECLARE schemaname NVARCHAR(128);
        DECLARE name NVARCHAR(128);

        IF CHARINDEX('.', viewname) > 0
        BEGIN
            SET schemaname = PARSENAME(viewname, 2);
            SET name       = PARSENAME(viewname, 1);
        END
        ELSE
        BEGIN
            SET schemaname = COALESCE(viewschemaname, 'dbo');
            SET name = viewname;
        END

        -------------------------------------------------------------------------
        -- Validate object exists
        -------------------------------------------------------------------------
        IF OBJECT_ID(QUOTENAME(schemaname) + '.' + QUOTENAME(name)) IS NULL
        BEGIN
            RAISERROR('Object %s.%s not found.', 16, 1, schemaname, name);
            RETURN;
        END

        -------------------------------------------------------------------------
        -- Get ObjectID and basic metadata
        -------------------------------------------------------------------------
        DECLARE objectid INT = OBJECT_ID(QUOTENAME(schemaname) + '.' + QUOTENAME(name));
        DECLARE tabledatabasename NVARCHAR(255) = DB_NAME();
        DECLARE tabledescription NVARCHAR(MAX) = CONCAT('Metadata for object ', schemaname, '.', name);
        DECLARE tablerowcount BIGINT = NULL;
        DECLARE tablecolumncount INT = NULL;
        DECLARE tablecolumnlist NVARCHAR(MAX) = NULL;
        DECLARE tableidentitycolumn NVARCHAR(255) = NULL;
        DECLARE tableprimarycolumncsv NVARCHAR(MAX) = NULL;
        DECLARE now DATETIME = now();

        -------------------------------------------------------------------------
        -- Column list & count
        -------------------------------------------------------------------------
        SELECT tablecolumncount = COUNT(*)
        FROM sys.columns
        WHERE object_id = objectid;

        SELECT tablecolumnlist =
            STUFF((
                SELECT ',' + QUOTENAME(c.name)
                FROM sys.columns c
                WHERE c.object_id = objectid
                ORDER BY c.column_id
                FOR XML PATH(''), TYPE
            ).value('.', 'nvarchar(max)'), 1, 1, '');

        -------------------------------------------------------------------------
        -- Row count (table: fast, view: fallback to COUNT(*))
        -------------------------------------------------------------------------
        SELECT tablerowcount = SUM(ps.row_count)
        FROM sys.dm_db_partition_stats ps
        WHERE ps.object_id = objectid
          AND ps.index_id IN (0,1);

        -- If NULL (e.g., for views), calculate using COUNT(*)
        IF tablerowcount IS NULL
        BEGIN
            DECLARE sql NVARCHAR(MAX) = N'SELECT rc = COUNT(*) FROM ' 
                                       + QUOTENAME(schemaname) + '.' + QUOTENAME(name) + ';';
            BEGIN TRY
                EXEC sp_executesql sql, N'rc BIGINT OUTPUT', rc = tablerowcount OUTPUT;
            END TRY
            BEGIN CATCH
                PRINT 'Error counting rows for object ' + QUOTENAME(schemaname) + '.' + QUOTENAME(name) + ': ' + ERROR_MESSAGE();
                SET tablerowcount = 0;
            END CATCH
        END

        -------------------------------------------------------------------------
        -- Identity & Primary Key
        -------------------------------------------------------------------------
        IF OBJECTPROPERTY(objectid, 'IsTable') = 1
        BEGIN
            SELECT TOP 1 tableidentitycolumn = c.name
            FROM sys.columns c
            WHERE c.object_id = objectid AND c.is_identity = 1;

            SELECT tableprimarycolumncsv = STRING_AGG(QUOTENAME(c.name), ',')
            FROM sys.indexes i
            JOIN sys.index_columns ic ON i.object_id = ic.object_id AND i.index_id = ic.index_id
            JOIN sys.columns c ON c.object_id = ic.object_id AND c.column_id = ic.column_id
            WHERE i.object_id = objectid AND i.is_primary_key = 1;
        END
        ELSE IF OBJECTPROPERTY(objectid, 'IsView') = 1
        BEGIN
            -- Attempt to get first underlying table for Identity/PK
            DECLARE baseobjectid INT;
            SELECT TOP 1 baseobjectid = referenced_id
            FROM sys.sql_expression_dependencies
            WHERE referencing_id = objectid
              AND referenced_class = 1;  -- OBJECT

            IF baseobjectid IS NOT NULL
            BEGIN
                SELECT TOP 1 tableidentitycolumn = c.name
                FROM sys.columns c
                WHERE c.object_id = baseobjectid AND c.is_identity = 1;

                SELECT tableprimarycolumncsv = STRING_AGG(QUOTENAME(c.name), ',')
                FROM sys.indexes i
                JOIN sys.index_columns ic ON i.object_id = ic.object_id AND i.index_id = ic.index_id
                JOIN sys.columns c ON c.object_id = ic.object_id AND c.column_id = ic.column_id
                WHERE i.object_id = baseobjectid AND i.is_primary_key = 1;
            END
        END

        -------------------------------------------------------------------------
        -- Upsert TableInfo
        -------------------------------------------------------------------------
        IF NOT EXISTS (
            SELECT 1 FROM [divaconfig].[TableInfo] ti
            WHERE ti.TableDatabaseName = tabledatabasename
              AND ti.TableSchemaName   = schemaname
              AND ti.TableName         = name
        )
        BEGIN
            INSERT INTO [divaconfig].[TableInfo] (
                TableDatabaseName,
                TableSchemaName,
                TableName,
                TableDescription,
                TableRowCount,
                TableColumnCount,
                TableIdentityColumnName,
                TablePrimaryColumnCSV,
                TableUniqueColumnCSV,
                IsTableEditable,
                TableMetadataSyncDateTime,
                IsDeleted
            )
            VALUES (
                tabledatabasename,
                schemaname,
                name,
                tabledescription,
                tablerowcount,
                tablecolumncount,
                tableidentitycolumn,
                tableprimarycolumncsv,
                tablecolumnlist,
                CASE WHEN OBJECTPROPERTY(objectid, 'IsView') = 1 THEN 0 ELSE 1 END,
                now,
                0
            );
        END
        ELSE
        BEGIN
            UPDATE ti
            SET ti.TableDescription          = tabledescription,
                ti.TableRowCount             = tablerowcount,
                ti.TableColumnCount          = tablecolumncount,
                ti.TableIdentityColumnName   = tableidentitycolumn,
                ti.TablePrimaryColumnCSV     = tableprimarycolumncsv,
                ti.TableUniqueColumnCSV      = tablecolumnlist,
                ti.IsTableEditable           = CASE WHEN OBJECTPROPERTY(objectid, 'IsView') = 1 THEN 0 ELSE 1 END,
                ti.TableMetadataSyncDateTime = now,
                ti.IsDeleted                 = 0,
                ti.UpdatedAt                 = now()
            FROM [divaconfig].[TableInfo] ti
            WHERE ti.TableDatabaseName = tabledatabasename
              AND ti.TableSchemaName   = schemaname
              AND ti.TableName         = name;
        END

        SET NOCOUNT OFF;
    END
END;
$function$;
