-- Generated by dbmigration.
-- Function dbo.ResponseIsAverageChoice -> livebit_dbo.responseisaveragechoice
-- Original source: source/routines/livebit_dbo__responseisaveragechoice.sql

CREATE OR REPLACE FUNCTION "livebit_dbo"."responseisaveragechoice"(surveyid integer)
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
    -- ---- converted from T-SQL procedure dbo.ResponseIsAverageChoice ----
    BEGIN
        Declare responseistopboxchoice varchar(50), responseisbottomboxchoice varchar(50), responseisaveragechoice varchar(50), responseweightage varchar(50)

        SELECT responseistopboxchoice = Case when [ResponseIsTopBoxChoice]=1 then 'Yes' else 'No' End 
    	,responseisbottomboxchoice=Case when [ResponseIsBottomBoxChoice]=1 THEN 'Yes' else 'No' end 
        ,responseisaveragechoice=Case when [ResponseIsAverageChoice]  =1 THEN 'Yes' else 'No' end 
        ,responseweightage=CAST( [ResponseWeightage] AS varchar(10)) 
	
    	from [dbo].[Survey] s 
    Inner join [dbo].[Question] q on q.QuestionSurveyID = s.SurveyID
    inner join [dbo].[Response] r on r.[ResponseQuestionID]=q.QuestionID
        where SurveyID = surveyid

        RETURN   responseisaveragechoice --,responseisbottomboxchoice , responseisaveragechoice , responseweightage 

    END
END;
$function$;
