-- Generated by dbmigration.
-- Procedure aidd.LoadAllTableColumnValues -> livebit_aidd.loadalltablecolumnvalues
-- Original source: source/routines/livebit_aidd__loadalltablecolumnvalues.sql

CREATE OR REPLACE FUNCTION "livebit_aidd"."loadalltablecolumnvalues"()
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
    -- REVIEW (manual): sp_executesql — port to EXECUTE ... USING  [sp_executesql]
    -- REVIEW (manual): cursor — port to a PL/pgSQL FOR loop or cursor  [OPEN cur]
    -- REVIEW (manual): cursor — port to a PL/pgSQL FOR loop or cursor  [FETCH NEXT]
    -- REVIEW (manual): cursor — port to a PL/pgSQL FOR loop or cursor  [FETCH NEXT]
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- ---- converted from T-SQL procedure aidd.LoadAllTableColumnValues ----
    BEGIN
        SET NOCOUNT ON;

        DECLARE schemaname NVARCHAR(255),
                tablename NVARCHAR(255),
                columnname NVARCHAR(255),
                sql NVARCHAR(MAX);

        -- Clean existing data (soft delete old values instead of hard delete)
        UPDATE [aidd].[ColumnValue]
        SET IsDeleted = 1, UpdatedAt = now();

        -- Cursor over active column metadata from ColumnInfo
        DECLARE cur CURSOR FAST_FORWARD FOR
        SELECT SchemaName, TableName, ColumnName
        FROM [aidd].[ColumnInfo]
        WHERE IsDeleted = 0
          AND IsEditable = 1;  -- optional filter

        OPEN cur;
        FETCH NEXT FROM cur INTO schemaname, tablename, columnname;

        WHILE @fetch_status = 0
        BEGIN
            -- Dynamic SQL to insert distinct column values
            SET sql = '
                INSERT INTO [aidd].[ColumnValue] (
                    DatabaseName, SchemaName, TableName, ColumnName,
                    Value, ValueCount, DisplayText, Description, IsActive, SortOrder, CreatedAt, UpdatedAt, IsDeleted
                )
                SELECT 
                    DB_NAME(),
                    ''' + schemaname + ''',
                    ''' + tablename + ''',
                    ''' + columnname + ''',
                    CAST([' + columnname + '] AS NVARCHAR(MAX)) AS Value,
                    COUNT(*) AS ValueCount,
                    CAST([' + columnname + '] AS NVARCHAR(MAX)) AS DisplayText,
                    NULL AS Description,
                    1 AS IsActive,
                    ROW_NUMBER() OVER (ORDER BY COUNT(*) DESC) AS SortOrder,
                    now() AS CreatedAt,
                    now() AS UpdatedAt,
                    0 AS IsDeleted
                FROM [' + schemaname + '].[' + tablename + ']
                WHERE [' + columnname + '] IS NOT NULL
                GROUP BY [' + columnname + ']';

            EXEC sp_executesql sql;

            FETCH NEXT FROM cur INTO schemaname, tablename, columnname;
        END;

        CLOSE cur;
        DEALLOCATE cur;
    END;
END;
$function$;
