-- Generated by dbmigration.
-- Procedure divaconfig.sp_GetColumnMetadata -> livebit_divaconfig.sp_getcolumnmetadata
-- Original source: source/routines/livebit_divaconfig__sp_getcolumnmetadata.sql

CREATE OR REPLACE FUNCTION "livebit_divaconfig"."sp_getcolumnmetadata"(schematable text)
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+ ']
    -- ---- converted from T-SQL procedure divaconfig.sp_GetColumnMetadata ----
    BEGIN
        /*
        Description:
        - Fetches metadata for a specific table's columns.
        - Ensures the table exists, is editable, and is not deleted.
        - Returns distinct error messages for non-existing, non-editable, or deleted tables.

        Example Usage:
        EXEC [divaconfig].[sp_GetColumnMetadata] schematable = 'dbo.MyTable';
    	 EXEC [divaconfig].[sp_GetColumnMetadata] schematable = 'divaconfig.SampleData';
        */

        -- Variables to store schema and table name
        DECLARE schemaname NVARCHAR(255);
        DECLARE tablename NVARCHAR(255);

        -- Parse Schema and Table from schematable
        SET schemaname = LEFT(schematable, CHARINDEX('.', schematable) - 1);
        SET tablename = SUBSTRING(schematable, CHARINDEX('.', schematable) + 1, length(schematable));

        -- Check if the table exists
        IF NOT EXISTS (
            SELECT 1
            FROM [divaconfig].[TableInfo]
            WHERE [TableSchemaName] = schemaname
              AND [TableName] = tablename
        )
        BEGIN
            SELECT 'The specified table [' + schematable + '] does not exist.' AS ErrorMessage;
            RETURN;
        END

        -- Check if the table is editable
        IF NOT EXISTS (
            SELECT 1
            FROM [divaconfig].[TableInfo]
            WHERE [TableSchemaName] = schemaname
              AND [TableName] = tablename
            --  AND [IsTableEditable] = 1
        )
        BEGIN
            SELECT 'The specified table [' + schematable + '] is not editable.' AS ErrorMessage;
            RETURN;
        END

        -- Check if the table is deleted
        IF EXISTS (
            SELECT 1
            FROM [divaconfig].[TableInfo]
            WHERE [TableSchemaName] = schemaname
              AND [TableName] = tablename
              AND [IsDeleted] = 1
        )
        BEGIN
            SELECT 'The specified table [' + schematable + '] is marked as deleted.' AS ErrorMessage;
            RETURN;
        END

        -- Fetch column metadata for the specified table
        SELECT *
        FROM [divaconfig].[ColumnInfo]
        WHERE [SchemaName] = schemaname
          AND [TableName] = tablename
          AND [IsDeleted] = 0;
    END
END;
$function$;
