-- Generated by dbmigration.
-- Procedure dbo.sp_ui_evalsubmit -> livebit_dbo.sp_ui_evalsubmit
-- Original source: source/routines/livebit_dbo__sp_ui_evalsubmit.sql

CREATE OR REPLACE FUNCTION "livebit_dbo"."sp_ui_evalsubmit"(surveyid integer, questionid integer, responseid integer, userid integer, questionstartdisplaydatatime timestamp, questionresponcesubmiteddatetime timestamp)
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
    -- REVIEW (manual): TOP n — rewrite as LIMIT n  [top 1]
    -- ---- converted from T-SQL procedure dbo.sp_ui_evalsubmit ----
    BEGIN
        SET NOCOUNT ON;

    	-- Check if record exists and FirstTimeRespoceOpenFor30DayResponceWindow is more than 30 days old
        IF EXISTS (SELECT top 1 1 FROM [LiveBit].[dbo].[FactEval]
                   WHERE SurveyID = surveyid 
                   AND QuestionID = questionid 
                   AND UserID = userid)
        BEGIN
            -- Update existing record
            UPDATE [LiveBit].[dbo].[FactEval]
            SET ResponseID = responseid,
                QuestionStartDisplayDataTime = questionstartdisplaydatatime,
                QuestionResponceSubmitedDateTime = questionresponcesubmiteddatetime,
    			RecordResponceType = 'Update',
    			BackendRecordDataTime=now()
            WHERE SurveyID = surveyid 
            AND QuestionID = questionid 
            AND UserID = userid;
        END
        ELSE
        BEGIN
            -- Insert new record
            INSERT INTO [LiveBit].[dbo].[FactEval] 
                (SurveyID, QuestionID, ResponseID, UserID, 
                 QuestionStartDisplayDataTime, QuestionResponceSubmitedDateTime,
                 RecordResponceType,BackendRecordDataTime)
            VALUES 
                (surveyid, questionid, responseid, userid, 
                 questionstartdisplaydatatime, questionresponcesubmiteddatetime, 
                 'Insert', now());
        END
    END
END;
$function$;
