-- Generated by dbmigration.
-- Procedure dbo.Test -> livebit_dbo.test
-- Original source: source/routines/livebit_dbo__test.sql

CREATE OR REPLACE FUNCTION "livebit_dbo"."test"(surveyid integer)
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
    -- ---- converted from T-SQL procedure dbo.Test ----
    begin

    select dbo.ResponseIsTopBoxChoice(surveyid) as ResponseIsTopBoxChoice ,dbo.ResponseIsBottomBoxChoice(surveyid) as  ResponseIsBottomBoxChoice,dbo.ResponseIsAverageChoice(surveyid) as  ResponseIsAverageChoice,
    dbo.ResponseWeightage(surveyid) as  ResponseWeightage
    --,Case when [ResponseIsTopBoxChoice]=1 then 'Yes' else 'No' End    [ResponseIsTopBoxChoice]
    --,Case when [ResponseIsBottomBoxChoice]=1 THEN 'Yes' else 'No' end [ResponseIsBottomBoxChoice]
    --,Case when [ResponseIsAverageChoice]  =1 THEN 'Yes' else 'No' end [ResponseIsAverageChoice]
    --,CAST( [ResponseWeightage] AS varchar(10)) AS [ResponseWeightage]
    end
END;
$function$;
