-- Generated by dbmigration.
-- Procedure dbo.LogExecutionDetails -> livebit_dbo.logexecutiondetails
-- Original source: source/routines/livebit_dbo__logexecutiondetails.sql

CREATE OR REPLACE FUNCTION "livebit_dbo"."logexecutiondetails"(procedurename text DEFAULT NULL, parameterdetails text DEFAULT NULL, openaistepname text DEFAULT NULL, openaiparameterdetails text DEFAULT NULL, openaiprompt text DEFAULT NULL, additionalloggingdetails text DEFAULT NULL, status text, errormessage text DEFAULT NULL, logid integer DEFAULT NULL OUTPUT, executionguid text DEFAULT NULL  -- Optional input for Execution GUID)
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
    -- ---- converted from T-SQL procedure dbo.LogExecutionDetails ----
    BEGIN
        -- If no LogID is provided and status is 'Started', insert a new log entry
        IF logid IS NULL AND status = 'Started'
        BEGIN
            -- If ExecutionGUID is not provided or blank, generate a new GUID and convert to NVARCHAR
            IF executionguid IS NULL OR executionguid = ''
            BEGIN
                SET executionguid = CAST(gen_random_uuid() AS NVARCHAR(MAX));
            END

            -- Insert log with start time and ExecutionGUID
            INSERT INTO ExecutionLog 
            (ProcedureName, StartTime, ParameterDetails, Status, OpenAIStepName, OpenAIParameterDetails, OpenAIPrompt, AdditionalLoggingDetails, ExecutionGUID)
            VALUES 
            (procedurename, now(), parameterdetails, 'Started', openaistepname, openaiparameterdetails, openaiprompt, additionalloggingdetails, executionguid);

            -- Capture the identity value of the inserted row (LogID)
            SET logid = lastval();
        END

        -- If LogID is provided and status is 'Completed', update the existing log with end time
        ELSE IF logid IS NOT NULL AND status = 'Completed'
        BEGIN
            UPDATE ExecutionLog
            SET EndTime = now(),
                Status = 'Completed',
                AdditionalLoggingDetails = additionalloggingdetails
            WHERE LogID = logid;
        END

        -- If LogID is provided and the status is not 'Completed' or 'Started', treat it as an error
        ELSE IF logid IS NOT NULL AND status != 'Started' AND status != 'Completed'
        BEGIN
            UPDATE ExecutionLog
            SET EndTime = now(),
                Status = 'Error',
                ErrorMessage = errormessage,
                AdditionalLoggingDetails = additionalloggingdetails
            WHERE LogID = logid;
        END
        ELSE
        BEGIN
            -- Handle invalid cases where neither a valid logid nor a valid status is provided
            RAISERROR('Invalid input: LogID or Status is missing.', 16, 1);
        END
    END;
END;
$function$;
