-- Generated by dbmigration.
-- Procedure dbo.DMS_PostRunSalesPosition -> livebit_dbo.dms_postrunsalesposition
-- Original source: source/routines/livebit_dbo__dms_postrunsalesposition.sql

CREATE OR REPLACE FUNCTION "livebit_dbo"."dms_postrunsalesposition"()
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
    -- ---- converted from T-SQL procedure dbo.DMS_PostRunSalesPosition ----
    Begin 


    IF OBJECT_ID('dbo.INFA_C_BO_CUST_EXT_XREF_base', 'U')				IS NOT NULL BEGIN	DROP TABLE dbo.INFA_C_BO_CUST_EXT_XREF_base		END 
    IF OBJECT_ID('dbo.SAPX40_R_KNA1_SALES_PSTN_base', 'U')				IS NOT NULL BEGIN	DROP TABLE dbo.SAPX40_R_KNA1_SALES_PSTN_base	END


    Select * INTO	 INFA_C_BO_CUST_EXT_XREF_base						From INFA_C_BO_CUST_EXT_XREF
    Select * INTO	 SAPX40_R_KNA1_SALES_PSTN_base						From SAPX40_R_KNA1_SALES_PSTN


    Select 'PRE Row Base Count INFA Sales Area' as 'RowType', Count(1) 'RowCount',Count(Distinct CUST_NBR ) 'DistinctBP'  From INFA_C_BO_CUST_EXT_XREF_base UNION
    Select 'PRE Row Base Count P04 Sales Area' as 'RowType', Count(1) 'RowCount',Count(Distinct KUNNR ) 'DistinctBP'	  From SAPX40_R_KNA1_SALES_PSTN_base



    --INFA

    --Alterting INFA COLUMNS
    Alter Table INFA_C_BO_CUST_EXT_XREF
    Add POSITION_START_DATE_INFA varchar(200) null,POSITION_END_DATE_INFA varchar(200) null

    Update INFA_C_BO_CUST_EXT_XREF
    SET POSITION_START_DATE_INFA = REPLACE(CONVERT (CHAR(10), POSITION_START_DATE, 101),'/','')
       ,POSITION_END_DATE_INFA = REPLACE(CONVERT (CHAR(10), POSITION_END_DATE, 101),'/','')

    Update INFA_C_BO_CUST_EXT_XREF
    Set POSITION_END_DATE_INFA = 'No Date'
    Where 1=1 and (POSITION_END_DATE_INFA is null or  POSITION_END_DATE_INFA = 'NULL')

    Update INFA_C_BO_CUST_EXT_XREF
    Set POSITION_START_DATE_INFA = 'No Date'
    Where 1=1 and (POSITION_START_DATE_INFA is null or POSITION_START_DATE_INFA = 'NULL')

    Update INFA_C_BO_CUST_EXT_XREF
    Set POSITION_END_DATE_INFA = '12-31-9999'
    Where 1=1 and Cast(POSITION_END_DATE_INFA  As Varchar(200)) in( '12319999','12319998')


    Update INFA_C_BO_CUST_EXT_XREF	SET REV_CENTER_ID = 'NULL'			Where REV_CENTER_ID = ''				OR REV_CENTER_ID			IS NULL
    Update INFA_C_BO_CUST_EXT_XREF	SET SALES_PERSON_ID = 'NULL'		Where SALES_PERSON_ID = ''				OR SALES_PERSON_ID			IS NULL
    Update INFA_C_BO_CUST_EXT_XREF	SET SALES_PSTN_ID = 'NULL'			Where SALES_PSTN_ID = ''				OR SALES_PSTN_ID			IS NULL
    Update INFA_C_BO_CUST_EXT_XREF	SET REV_CENTER_NAME = 'NULL'		Where REV_CENTER_NAME = ''				OR REV_CENTER_NAME			IS NULL
    Update INFA_C_BO_CUST_EXT_XREF	SET POSITION_NAME = 'NULL'			Where POSITION_NAME = ''				OR POSITION_NAME			IS NULL


    --SAP40

    Alter Table SAPX40_R_KNA1_SALES_PSTN
    Add POSITION_START_DATE_P40 varchar(200) null,POSITION_END_DATE_P40 varchar(200) null

    Update SAPX40_R_KNA1_SALES_PSTN
    SET POSITION_START_DATE_P40 = REPLACE(CONVERT (CHAR(10), ZZ_POSITION_START_DATE, 101),'/','')
       ,POSITION_END_DATE_P40 = REPLACE(CONVERT (CHAR(10), ZZ_POSITION_END_DATE, 101),'/','')

    Update SAPX40_R_KNA1_SALES_PSTN
    Set POSITION_END_DATE_P40 = 'No Date'
    Where 1=1 and POSITION_END_DATE_P40 in ('00000000  ','          ','NULL')

    Update SAPX40_R_KNA1_SALES_PSTN
    Set POSITION_START_DATE_P40 = 'No Date'
    Where 1=1 and POSITION_START_DATE_P40 in ('00000000  ','          ','NULL')

    Update SAPX40_R_KNA1_SALES_PSTN
    Set POSITION_END_DATE_P40 = '12-31-9999'
    Where 1=1 and POSITION_END_DATE_P40 in ('99981231  ','99991231  ')

    Update SAPX40_R_KNA1_SALES_PSTN
    Set POSITION_START_DATE_P40 = '01012020'
    Where 1=1 and POSITION_START_DATE_P40 in ('20200101  ')

    Update SAPX40_R_KNA1_SALES_PSTN
    Set POSITION_START_DATE_P40 = '09012022'
    Where 1=1 and POSITION_START_DATE_P40 in ('20220901  ')

    Update SAPX40_R_KNA1_SALES_PSTN
    Set POSITION_START_DATE_P40 = '10102022'
    Where 1=1 and POSITION_START_DATE_P40 in ('20221010  ')


    Update SAPX40_R_KNA1_SALES_PSTN	SET ZZ_REV_CENTER = 'NULL'			Where ZZ_REV_CENTER = ''			OR ZZ_REV_CENTER			IS NULL
    Update SAPX40_R_KNA1_SALES_PSTN	SET ZZ_SALES_PERSON_KOID = 'NULL'	Where ZZ_SALES_PERSON_KOID = ''		OR ZZ_SALES_PERSON_KOID		IS NULL
    Update SAPX40_R_KNA1_SALES_PSTN	SET ZZ_SALES_POSITION_ID = 'NULL'	Where ZZ_SALES_POSITION_ID = ''		OR ZZ_SALES_POSITION_ID		IS NULL
    Update SAPX40_R_KNA1_SALES_PSTN	SET ZZ_REV_CENTER_NAME = 'NULL'		Where ZZ_REV_CENTER_NAME = ''		OR ZZ_REV_CENTER_NAME		IS NULL
    Update SAPX40_R_KNA1_SALES_PSTN	SET ZZ_SALES_POSITION_NAME = 'NULL'	Where ZZ_SALES_POSITION_NAME = ''	OR ZZ_SALES_POSITION_NAME	IS NULL





    Exec FactL2PerConfig 30
    Exec FactL2PerConfig 31
    Exec FactL2PerConfig 32
    Exec FactL2PerConfig 33
    Exec FactL2PerConfig 34
    Exec FactL2PerConfig 57
    Exec FactL2PerConfig 58



    Update l2
    SET l2.KUNNR_P07			=rl.KUNNR_P07
    ,	l2.PARTNER_S4			=rl.PARTNER_S4
    ,	l2.CLASSIFICATION		=rl.CLASSIFICATION
    ,	l2.CONCLUSION_NEEDS_CC	=rl.CONCLUSION_NEEDS_CC
    ,l2.Filter9 = 'BP Exist in ZDCV_BRIM_RELEVANCY DIH'
    --Select Count(*) 
    from [FactL2Monitor] l2
    Inner join [dbo].[ZDCV_BRIM_RELEVANCY] rl  on l2.BusinessPartner= rl.PARTNER_S4
    Where l2.ConfigID IN (30,31,32,33,34,57,58)

    Update [FactL2Monitor]  
    SET IsFilter = 'N'
    Where ConfigID IN (30,31,32,33,34,57,58)

    Update l2
    SET l2.Filter1 =  POSITION_END_DATE
    from [FactL2Monitor] l2 
    Inner join INFA_C_BO_CUST_EXT_XREF N on l2.BusinessPartner = n.CUST_NBR
    Where ConfigID = 30

    Update l2
    SET l2.Filter2 = ZZ_POSITION_END_DATE 
    from [FactL2Monitor] l2 
    Inner join SAPX40_R_KNA1_SALES_PSTN N on l2.BusinessPartner = n.KUNNR
    Where ConfigID = 30

    Update l2
    SET l2.Filter3 = POSITION_START_DATE
    from [FactL2Monitor] l2 
    Inner join INFA_C_BO_CUST_EXT_XREF N on l2.BusinessPartner = n.CUST_NBR
    Where ConfigID = 31

    Update l2
    SET l2.Filter4 = ZZ_POSITION_START_DATE
    from [FactL2Monitor] l2 
    Inner join SAPX40_R_KNA1_SALES_PSTN N on l2.BusinessPartner = n.KUNNR
    Where ConfigID = 31

    Update l2
    SET l2.Filter5 = SS_CUST_TYPE
    from [FactL2Monitor] l2 
    Inner join INFA_C_BO_CUST_EXT_XREF N on l2.BusinessPartner = n.CUST_NBR
    Where ConfigID = 34

    /*
    Update l2
    SET l2.Filter6 = 
    from [FactL2Monitor] l2 
    Inner join SAPX40_R_KNA1_SALES_PSTN N on l2.BusinessPartner = n.KUNNR
    Where ConfigID = 34
    */

    Update  [FactL2Monitor]
    SET IsFilter = 'Y', FilterDetails ='SS_CUST_TYPE=55' 
    Where 1=1 
     and  ConfigID IN (25,39)
     and Filter5 <> 'NULL'
     and Filter5 = 55
 

      DELETE
    --Select COunt(*)
    from [FactL2Monitor] 
    Where ConfigValue='NULL' and IsINFA='1' and IsP40='1' and IsDIH='1' and IsP07='1'

 
    TRUNCATE TABLE dbo.FactL2Monitor_SalesPosition

    SET IDENTITY_INSERT dbo.FactL2Monitor_SalesPosition ON;

    INSERT INTO dbo.FactL2Monitor_SalesPosition
    ([FactL2ID], [LoadRunDateTime], [BusinessPartner], [ConfigID], [ConfigValue], [IsINFA], [IsP40], [IsDIH], [IsP07], [MatchStatus], [CompareCode], [CodeDescription], [BPEtEMatch], [FactL1ID], [CriteriaValue], [BRStatus], [BRIMRelevancy], [BPStatus], [IsFilter], [FilterDetails], [CLASSIFICATION], [CONCLUSION_NEEDS_CC], [Filter1], [Filter2], [Filter3], [Filter4], [Filter5], [KUNNR_P07], [PARTNER_S4], [Filter6], [Filter7], [Filter8], [Filter9], [Rank])
    Select   *, rank() OVER(Order BY FactL2ID) as [Rank] from [dbo].[FactL2Monitor] L2
    Where L2.configid  IN (30,31,32,33,34,57,58)

    SET IDENTITY_INSERT dbo.FactL2Monitor_SalesPosition OFF;


    END;
END;
$function$;
