-- Generated by dbmigration.
-- View dbo.vwEvaluation -> livebit_dbo.vwevaluation
-- Original T-SQL: source/views/livebit_dbo__vwevaluation.sql

-- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+']
-- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+']
CREATE OR REPLACE VIEW "livebit_dbo"."vwevaluation" AS
SELECT evalid
,Cast(surveyid as varchar(99))+'-'+Cast(questionid as varchar(99))+'-'+Cast(responseid as varchar(99)) as 'AssessmentID'
      ,surveyid
      ,questionid
      ,responseid
      ,userid
      ,questionstartdisplaydatatime
      ,questionresponcesubmiteddatetime
      ,recordresponcetype
      ,backendrecorddatatime
      ,trackerid
  FROM "livebit_dbo".facteval;
