-- Generated by dbmigration.
-- View dbo.vwUser -> livebit_dbo.vwuser
-- Original T-SQL: source/views/livebit_dbo__vwuser.sql

CREATE OR REPLACE VIEW "livebit_dbo"."vwuser" AS
SELECT  userid
      ,userfirstname
      ,userlastname
      ,useremail
      ,userphonenumber
      ,userage
      ,usergender
      ,usereducationlevel
      ,useroccupation
      ,userincomerange
      ,usercountry
      ,userstate
      ,usercity
      ,userlinkedinprofilelink
      ,userfacebookprofilelink
      ,userinstagramprofilelink
      ,usertwitterprofilelink
      ,usercurrentcompanylink
      ,userpastcompanieslink
      ,usercompanyid
      ,authid
      ,usercommunicationemail
      ,userphone
      ,userstreet1
      ,userstreet2
      ,userzip
      ,userjobtitle
      ,usercompanyemail
      ,usercompanyname
      ,userjobindustry
      ,userprofessionalexpertise
      ,userprofessionalskills
      ,usercommunityinvolvement
      ,useruniversityattended
      ,usergraduationyear
      ,userleadershipprogramgraduatedfrom
      ,useristoberegistered
      ,userisalumni
      ,userisincurrentclass
      ,userischambermember
      ,userleadershipbatchyear
      ,userinterestedinleadershiptopics
      ,userseekingmentor
      ,userwillingtobementor
      ,usermentorshipinvolvementlist
      ,userwillingtobeguestspeaker
      ,userguestspeakertopicpreference
      ,userisactive
      ,usermembersincedate
      ,userlastupdated
,companyname, companytype, companyindustry, companyheadquarters, companyfoundedyear, companyrevenue, companynumberofemployees, companymarketsegment, companyparentcompanyid, companyglobalpresence, companywebsiteurl, companycontactinfo, companydescription, companyisconsultingcompany, consultingcompanyid
  FROM "livebit_dbo".user u 
  left join "livebit_dbo".company  c on u.usercompanyid=c.companyid;
