-- Generated by dbmigration.
-- View dbo.vwAssessment -> livebit_dbo.vwassessment
-- Original T-SQL: source/views/livebit_dbo__vwassessment.sql

-- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+']
-- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+']
-- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+']
-- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+']
-- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+']
-- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+']
-- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+']
-- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+']
-- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+']
-- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+']
-- REVIEW (manual): string concatenation with '+' — use '||' in Postgres  [+']
CREATE OR REPLACE VIEW "livebit_dbo"."vwassessment" AS
Select distinct  
--ID to Match with Evaluation
Cast(s.surveyid as varchar(99))+'-'+Cast(q.questionid as varchar(99))+'-'+Cast(r.responseid as varchar(99)) as 'AssessmentID'
--Assessment Group Details
,sg.surveyproductid, sg.surveyproductcategory, sg.surveyproductname, sg.surveyproductdesc, sg.surveyproductsort, sg.surveyproductisopen
,sg.surveyproductcategory+'-'+SurveyProductName as SurveyProductCategoryNName
,sg.surveyproductcategory+'-'+SurveyProductName +'-'+surveyproductdesc SurveyProductCategoryNDesc
--Assessment details 
,s.surveyid, s.surveycategory, s.surveyname, s.surveydesc, s.surveylastupdated, s.surveystartdate, s.surveyenddate,  s.surveynextresetrunningwindowindays, s.surveyislockedforseason, s.surveygroup1, s.surveygroup2, s.surveygroup3, s.surveygenratedbyai, s.surveyaiverifiedbyhuman, s.surveyapprovedbyuserid, s.surveyrequestbyuserid
,s.surveycategory+'-'+s.surveyname as SurveyCategoryNName
,s.surveycategory+'-'+s.surveyname+'-'+s.surveydesc as SurveyCategoryNNameNDesc
--Assessment Question
,q.questionid, questiontext, questionshorttext, questiongrouptext, questionshortabbrev,
q.questionsort, questionismultimark, questionisscale, questionistopbox, questionisskipquestion,
questionskiptoquestionid, questiongroup1text, questiongroup2text, questiongroup3text, questiongroup4text,
questiongroup5text, questionchoiceaigenrated, questionscale
,questionshortabbrev+COALESCE('('+questionshorttext+')','') as questionshortabbrevtext
--Assessment Response
,r.responseid, r.responsetext, r.responseweightage, r.responsesort, r.responseisdefaultchoice, r.responseiscompulsorychoice,
r.responseistopboxchoice, r.responseisbottomboxchoice, r.responseisaveragechoice, r.responseisskipchoice,
r.responsegroup1, r.responsegroup2, r.responsegroup3, r.responsegroup4, r.responsegroup5, r.responcedescriptiontoachivethislarge,
r.responcedescriptiontoachivethisshort, r.responceaveragedaystoachive
,Cast(responsesort as Varchar(20))+'-'+responsetext As ResponseTextWithSort
,Cast(responsesort as Varchar(20))+'-'+responsetext
+ Case When ResponseIsTopBoxChoice= 1 then ' | Top' Else '' End 
+ Case When ResponseIsBottomBoxChoice= 1 then ' | Bottom' Else '' End 
+ Case When ResponseIsAverageChoice= 1 then ' | Avg' Else '' End 
As ResponseTextWithSortWithAllBox
from "livebit_dbo".survey s 
left join "livebit_dbo".question q on q.QuestionSurveyID = s.SurveyID
left join "livebit_dbo".response r on r.responsequestionid=q.QuestionID
left join "livebit_dbo".surveygroup sg on sg.SurveyProductID = s.surveyproductid
Where q.questionid is not null or r.responseid is not null
--order by q.QuestionID,ResponseSort;
