-- Generated by dbmigration. Do not edit by hand.
-- Procedures & functions

CREATE OR REPLACE FUNCTION "livebit_dbo"."usp_getcustomer"(id integer)
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
    -- ---- converted from T-SQL procedure dbo.usp_GetCustomer ----
    BEGIN SELECT * FROM Customers WHERE Id=id; END
END;
$function$;
