-- Generated by dbmigration.
-- Foreign keys: run after all data is loaded.
-- One statement per line.

ALTER TABLE "livebit_dbo"."customers" ADD CONSTRAINT "customers_fk_customers_dimdate" FOREIGN KEY ("signupdatekey") REFERENCES "livebit_divadim"."dimdate" ("datekey");
