-- Generated by dbmigration.
-- Identity sequence resets: run after all data is loaded.
-- One statement per line.

SELECT setval(pg_get_serial_sequence('"livebit_dbo"."customers"', 'id'), COALESCE(MAX("id"), 1), MAX("id") IS NOT NULL) FROM "livebit_dbo"."customers";
SELECT setval(pg_get_serial_sequence('"livebit_sandbox"."auditlog"', 'id'), COALESCE(MAX("id"), 1), MAX("id") IS NOT NULL) FROM "livebit_sandbox"."auditlog";
