-- Generated by dbmigration. Data for dbo.Customers -> livebit_dbo.customers.
INSERT INTO "livebit_dbo"."customers" ("id", "name", "notes", "isactive", "balance", "externalid", "updatedat", "photo", "profile", "signupdatekey") VALUES
(1, 'Acme Corp', 'Key account.
Renewal due in March.', TRUE, 12500.00, '6f1c2d3e-4b5a-4c6d-8e7f-9a0b1c2d3e4f', '2026-01-02 10:00:00+00:00', '\x89504e470d0a'::bytea, '<profile tier="gold"/>', 20260101),
(2, 'O''Brien & Co', NULL, TRUE, -42.50, NULL, '2026-01-03 09:30:15.250000+05:30', NULL, NULL, 20260103),
(5, 'Café Ωmega 🚀', 'Path C:\exports\2026 and a tab	here', FALSE, NULL, '00000000-0000-0000-0000-000000000005', NULL, '\x'::bytea, NULL, NULL),
(7, 'LegacyImport', 'NUL characters are stripped (see manifest warnings)', TRUE, 0.00, NULL, NULL, NULL, NULL, 20260110);
