-- Generated by dbmigration. Data for divadim.DimDate -> livebit_divadim.dimdate.
INSERT INTO "livebit_divadim"."dimdate" ("datekey", "fulldate", "dayname") VALUES
(20260101, '2026-01-01', 'Thursday'),
(20260102, '2026-01-02', 'Friday'),
(20260103, '2026-01-03', 'Saturday'),
(20260104, '2026-01-04', 'Sunday'),
(20260105, '2026-01-05', 'Monday'),
(20260106, '2026-01-06', 'Tuesday'),
(20260107, '2026-01-07', 'Wednesday'),
(20260108, '2026-01-08', 'Thursday'),
(20260109, '2026-01-09', 'Friday'),
(20260110, '2026-01-10', 'Saturday');
INSERT INTO "livebit_divadim"."dimdate" ("datekey", "fulldate", "dayname") VALUES
(20260111, '2026-01-11', 'Sunday'),
(20260112, '2026-01-12', 'Monday'),
(20260113, '2026-01-13', 'Tuesday'),
(20260114, '2026-01-14', 'Wednesday'),
(20260115, '2026-01-15', 'Thursday'),
(20260116, '2026-01-16', 'Friday'),
(20260117, '2026-01-17', 'Saturday'),
(20260118, '2026-01-18', 'Sunday'),
(20260119, '2026-01-19', 'Monday'),
(20260120, '2026-01-20', 'Tuesday');
