-- Generated by dbmigration. Data for divadim.DimDate -> livebit_divadim.dimdate.
INSERT INTO "livebit_divadim"."dimdate" ("datekey", "fulldate", "dayname") VALUES
(20260121, '2026-01-21', 'Wednesday'),
(20260122, '2026-01-22', 'Thursday'),
(20260123, '2026-01-23', 'Friday'),
(20260124, '2026-01-24', 'Saturday'),
(20260125, '2026-01-25', 'Sunday'),
(20260126, '2026-01-26', 'Monday'),
(20260127, '2026-01-27', 'Tuesday'),
(20260128, '2026-01-28', 'Wednesday'),
(20260129, '2026-01-29', 'Thursday'),
(20260130, '2026-01-30', 'Friday');
INSERT INTO "livebit_divadim"."dimdate" ("datekey", "fulldate", "dayname") VALUES
(20260131, '2026-01-31', 'Saturday'),
(20260201, '2026-02-01', 'Sunday'),
(20260202, '2026-02-02', 'Monday'),
(20260203, '2026-02-03', 'Tuesday'),
(20260204, '2026-02-04', 'Wednesday'),
(20260205, '2026-02-05', 'Thursday'),
(20260206, '2026-02-06', 'Friday'),
(20260207, '2026-02-07', 'Saturday'),
(20260208, '2026-02-08', 'Sunday'),
(20260209, '2026-02-09', 'Monday');
