"""Regenerate ``examples/example-export/``: a small synthetic LiveBit export.

    python examples/generate_example.py                       # rewrite the example
    python examples/generate_example.py --verify-url URL      # ... then load it into URL

No database connection is needed to generate it: an in-memory LiveBit-like
database (schemas dbo, divadim, Sandbox; identity, bit default, nvarchar(max),
decimal, uniqueidentifier, datetimeoffset, varbinary, xml, date, a cross-schema
foreign key, a view and a procedure) is exported with the real exporter. The
previous example is deleted first. ``generated_at`` is fixed so regenerating
produces no diff. A tiny ``max_data_file_mb`` shows data split into parts.
"""

from __future__ import annotations

import argparse
import shutil
import sys
import uuid
from datetime import date, datetime, timedelta, timezone
from decimal import Decimal
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "src"))

from dbmigration.config import (
    DiscoveryConfig,
    MigrationConfig,
    NamingConfig,
    Plan,
    RoutinesConfig,
    TargetConfig,
)
from dbmigration.exporter import export_database, iter_failures, load_dump
from dbmigration.model import (
    Column,
    Database,
    ForeignKey,
    Index,
    Routine,
    SourceKind,
    Table,
    View,
)

OUT_ROOT = HERE / "example-export"
GENERATED_AT = "2026-01-01T00:00:00Z"
MAX_DATA_FILE_MB = 0.001  # ~1 KB, only to show .partNNNN files; the default is 45
BATCH_SIZE = 10

README = """# Example export (synthetic LiveBit)

Generated by `python examples/generate_example.py` with the real exporter from a
small in-memory LiveBit-like database; no real data. See
[docs/10-export-and-load.md](../../docs/10-export-and-load.md) for the layout.

`livebit/data/livebit_divadim__dimdate.part0001.sql`, `.part0002.sql`, ... show
how a table's data is split once a file would pass `--max-data-file-mb` (set
to about 1 KB here to force it; the default is 45 MB).

Load it into any PostgreSQL database to see the load report:

    dbmigrate load-dump examples/example-export/livebit --target-url postgresql://...
"""


def build_database() -> Database:
    dimdate = Table(
        schema="divadim", name="DimDate",
        columns=[
            Column("DateKey", "int", nullable=False, ordinal=1),
            Column("FullDate", "date", ordinal=2),
            Column("DayName", "nvarchar", char_length=20, ordinal=3),
        ],
        primary_key=Index("PK_DimDate", ["DateKey"], unique=True, is_primary=True),
        approx_row_count=40,
    )
    customers = Table(
        schema="dbo", name="Customers",
        columns=[
            Column("Id", "int", nullable=False, is_identity=True, ordinal=1),
            Column("Name", "nvarchar", char_length=100, nullable=False, ordinal=2),
            Column("Notes", "nvarchar", char_length=-1, ordinal=3),
            Column("IsActive", "bit", nullable=False, default="((1))", ordinal=4),
            Column("Balance", "decimal", numeric_precision=18, numeric_scale=2, ordinal=5),
            Column("ExternalId", "uniqueidentifier", ordinal=6),
            Column("UpdatedAt", "datetimeoffset", numeric_scale=7, ordinal=7),
            Column("Photo", "varbinary", char_length=-1, ordinal=8),
            Column("Profile", "xml", ordinal=9),
            Column("SignupDateKey", "int", ordinal=10),
        ],
        primary_key=Index("PK_Customers", ["Id"], unique=True, is_primary=True),
        indexes=[Index("IX_Customers_Name", ["Name"])],
        foreign_keys=[ForeignKey("FK_Customers_DimDate", ["SignupDateKey"], "divadim", "DimDate",
                                 ["DateKey"])],
        approx_row_count=4,
    )
    audit = Table(
        schema="Sandbox", name="AuditLog",
        columns=[
            Column("Id", "bigint", nullable=False, is_identity=True, ordinal=1),
            Column("Message", "nvarchar", char_length=-1, ordinal=2),
            Column("LoggedAt", "datetime2", numeric_scale=3, ordinal=3),
        ],
        primary_key=Index("PK_AuditLog", ["Id"], unique=True, is_primary=True),
        approx_row_count=0,
    )
    view = View(
        "dbo", "v_ActiveCustomers",
        "CREATE VIEW [dbo].[v_ActiveCustomers] AS\r\n"
        "SELECT c.[Id], c.[Name], d.[FullDate] AS [SignupDate]\r\n"
        "FROM [dbo].[Customers] c\r\n"
        "LEFT JOIN [divadim].[DimDate] d ON d.[DateKey] = c.[SignupDateKey]\r\n"
        "WHERE ISNULL(c.[Name], '') <> ''\r\n",
    )
    procedure = Routine(
        "dbo", "usp_TouchCustomer", "procedure", "tsql",
        "CREATE PROCEDURE [dbo].[usp_TouchCustomer] @CustomerId int AS\r\n"
        "UPDATE dbo.Customers SET Name = Name WHERE Id = @CustomerId;\r\n",
    )
    return Database(
        subscription="(direct)", server="coe-index-db-server.database.windows.net",
        kind=SourceKind.AZURE_SQL, name="LiveBit",
        tables=[customers, dimdate, audit], views=[view], routines=[procedure],
    )


def build_rows() -> dict[str, list[tuple]]:
    ist = timezone(timedelta(hours=5, minutes=30))
    first = date(2026, 1, 1)
    days = [first + timedelta(days=i) for i in range(40)]
    return {
        "divadim.DimDate": [
            (int(d.strftime("%Y%m%d")), d, d.strftime("%A")) for d in days
        ],
        "dbo.Customers": [
            (1, "Acme Corp", "Key account.\r\nRenewal due in March.", True,
             Decimal("12500.00"), uuid.UUID("6f1c2d3e-4b5a-4c6d-8e7f-9a0b1c2d3e4f"),
             datetime(2026, 1, 2, 10, 0, 0, tzinfo=timezone.utc), b"\x89PNG\r\n",
             '<profile tier="gold"/>', 20260101),
            (2, "O'Brien & Co", None, True, Decimal("-42.50"), None,
             datetime(2026, 1, 3, 9, 30, 15, 250000, tzinfo=ist), None, None, 20260103),
            (5, "Café Ωmega 🚀", "Path C:\\exports\\2026 and a tab\there", False,
             None, uuid.UUID("00000000-0000-0000-0000-000000000005"), None, b"",
             None, None),
            (7, "Legacy\x00Import", "NUL characters are stripped (see manifest warnings)",
             True, Decimal("0.00"), None, None, None, None, 20260110),
        ],
        "Sandbox.AuditLog": [],
    }


def generate(out_root: Path = OUT_ROOT):
    if out_root.exists():
        shutil.rmtree(out_root)
    plan = Plan(
        target=TargetConfig(supabase_project_ref="your-project-ref"),
        naming=NamingConfig(),
        discovery=DiscoveryConfig(),
        migration=MigrationConfig(batch_size=BATCH_SIZE),
        routines=RoutinesConfig(),
    )
    rows = build_rows()

    def reader(table: Table):
        yield rows[table.qualified]

    result = export_database(plan, build_database(), out_root, reader, data_format="insert",
                             max_data_file_mb=MAX_DATA_FILE_MB, generated_at=GENERATED_AT)
    (out_root / "README.md").write_text(README, encoding="utf-8")
    return result


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--verify-url", help="Postgres URL to load the example into afterwards "
                                             "(use an empty scratch database).")
    args = parser.parse_args(argv)

    result = generate()
    print(f"Wrote {result.out_dir.relative_to(HERE.parent)}: {result.tables} tables, "
          f"{result.views} views, {result.routines} routines, {result.rows} rows, "
          f"{len(result.data_files)} data files.")
    if not args.verify_url:
        return 0
    report = load_dump(result.out_dir, args.verify_url)
    totals = report["totals"]
    print(f"Load: {totals['ok']} ok, {totals['failed']} failed, "
          f"{totals['row_mismatches']} row-count mismatches.")
    for line in iter_failures(report):
        print(f"  FAILED {line}")
    return 0 if report["ok"] else 1


if __name__ == "__main__":
    sys.exit(main())
