"""Export a source database to per-object files in the repo, and load them back.

``export_database`` writes one file per object so every table, view and routine
can be verified on its own (``<schema>`` is always the *target* schema)::

  export/<db>/
    manifest.json                        what was exported + the exact load order
    00_schemas.sql                       CREATE SCHEMA for every target schema
    tables/<schema>__<table>.sql         CREATE TABLE + its indexes
    data/<schema>__<table>.sql           INSERT statements (``.tsv`` for COPY), or
    data/<schema>__<table>.part0001.sql  ... parts when above max_data_file_mb
    sequences.sql                        identity resets, one statement per line
    foreign_keys.sql                     foreign keys, one statement per line
    views/<schema>__<view>.sql           converted views (with REVIEW comments)
    routines/<schema>__<name>.sql        converted procedures and functions
    source/views/..., source/routines/...  the original T-SQL, verbatim

``load_dump`` replays ``manifest.json``'s ``load_order`` into a Postgres
database, one transaction per file (per statement for sequences/foreign keys),
then compares every table's row count with the export and returns a report.
"""

from __future__ import annotations

import contextlib
import heapq
import json
import math
import os
import re
import shutil
from collections.abc import Callable, Iterable, Iterator
from dataclasses import dataclass, field
from datetime import datetime, timezone
from decimal import Decimal
from pathlib import Path
from urllib.parse import parse_qsl, unquote, urlsplit, urlunsplit

from .config import Plan
from .model import Database, Table
from .naming import quote_ident, sanitize_identifier
from .pipeline import TableDDL, build_table_statements, schema_create_statements, schema_map_for
from .transform.ddl import plan_columns
from .transform.tsql_to_plpgsql import convert_routine
from .transform.views import convert_view

# Callable that yields batches of rows for a table (wired to a live extractor by
# the CLI; a fake in tests). Rows are tuples in column-ordinal order.
DataReader = Callable[[Table], Iterator[list[tuple]]]

MB = 1024 * 1024
DEFAULT_MAX_DATA_FILE_MB = 45.0
# An INSERT statement is flushed once it holds batch_size rows or this many bytes.
INSERT_STATEMENT_MAX_BYTES = 1_000_000
DATA_FORMATS = ("insert", "copy")
GENERATED = "-- Generated by dbmigration."
GITATTRIBUTES = (
    "# Generated by dbmigration: data files hold CR/LF inside values and source/ is\n"
    "# verbatim, so git must never convert line endings here.\n"
    "* -text\n"
)

# Files/directories export_database owns inside export/<db>/ (the old layout's
# numbered files included) and removes before writing, so stale files from an
# earlier export can never be mistaken for part of this one.
_GENERATED_DIRS = ("tables", "data", "views", "routines", "source")
_GENERATED_FILES = (
    "manifest.json", "manifest.json.tmp", "00_schemas.sql", "sequences.sql", "foreign_keys.sql",
    "load_report.json", ".gitattributes",
    "01_schema.sql", "02_views.sql", "03_routines.sql", "04_foreign_keys.sql",
)


@dataclass
class ExportResult:
    database: str
    out_dir: Path
    schemas: int = 0
    tables: int = 0
    views: int = 0
    procedures: int = 0
    functions: int = 0
    rows: int = 0
    data_files: list[str] = field(default_factory=list)
    data_bytes: int = 0
    review_items: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    manifest: dict = field(default_factory=dict)

    @property
    def routines(self) -> int:
        return self.procedures + self.functions


# --- value encoders ------------------------------------------------------------

def _float_special(value: float) -> str | None:
    if math.isnan(value):
        return "NaN"
    if math.isinf(value):
        return "Infinity" if value > 0 else "-Infinity"
    return None


def _decimal_special(value: Decimal) -> str:
    if value.is_nan():
        return "NaN"
    return "-Infinity" if value.is_signed() else "Infinity"


def encode_copy_value(value) -> str:
    r"""Encode one value into a Postgres COPY *text* field.

    NULL -> ``\N``; NUL characters are dropped from text (Postgres text cannot
    hold them); backslash/tab/newline/carriage-return are escaped; bytes become
    ``\x<hex>`` (then escaped). Round-trips through ``COPY ... FROM STDIN``.
    """
    if value is None:
        return r"\N"
    if isinstance(value, bool):
        return "t" if value else "f"
    if isinstance(value, int):
        return str(int(value))
    if isinstance(value, Decimal):
        return format(value, "f") if value.is_finite() else _decimal_special(value)
    if isinstance(value, float):
        return _float_special(value) or repr(value)
    if isinstance(value, (bytes, bytearray, memoryview)):
        s = "\\x" + bytes(value).hex()
    else:
        s = (value if isinstance(value, str) else str(value)).replace("\x00", "")
    return (
        s.replace("\\", "\\\\")
        .replace("\t", "\\t")
        .replace("\n", "\\n")
        .replace("\r", "\\r")
    )


def encode_copy_row(row: tuple) -> str:
    return "\t".join(encode_copy_value(v) for v in row) + "\n"


def encode_sql_literal(value) -> str:
    """Encode one value as a Postgres SQL literal for an INSERT statement.

    Assumes ``standard_conforming_strings = on`` (the default, and set by
    :func:`load_dump`), so backslashes are literal and only single quotes need
    escaping (by doubling). NUL characters are dropped from text.
    """
    if value is None:
        return "NULL"
    if isinstance(value, bool):  # before int: bool is an int subclass
        return "TRUE" if value else "FALSE"
    if isinstance(value, int):
        return str(int(value))
    if isinstance(value, Decimal):
        if value.is_finite():
            return format(value, "f")  # plain digits, never exponent notation
        return f"'{_decimal_special(value)}'::numeric"
    if isinstance(value, float):
        special = _float_special(value)
        return f"'{special}'::float8" if special else repr(value)
    if isinstance(value, (bytes, bytearray, memoryview)):
        return "'\\x" + bytes(value).hex() + "'::bytea"
    s = value if isinstance(value, str) else str(value)  # datetime, date, time, UUID, ...
    return "'" + s.replace("\x00", "").replace("'", "''") + "'"


def _nul_count(row: tuple) -> int:
    return sum(v.count("\x00") for v in row if isinstance(v, str) and "\x00" in v)


def _to_utf8(text: str) -> tuple[bytes, int]:
    """Encode *text* as UTF-8; unpaired surrogates become U+FFFD. Returns (bytes, replaced)."""
    try:
        return text.encode("utf-8"), 0
    except UnicodeEncodeError:
        fixed = text.encode("utf-16-le", "surrogatepass").decode("utf-16-le", "replace")
        return fixed.encode("utf-8"), fixed.count("\ufffd") - text.count("\ufffd")


def _comment(text: object) -> str:
    """Collapse *text* to one line so it is safe inside a ``--`` comment."""
    return " ".join(str(text).replace("\x00", "").split())


# --- export ----------------------------------------------------------------------

@dataclass
class _TableData:
    files: list[str] = field(default_factory=list)
    rows: int = 0
    bytes: int = 0
    nul_chars: int = 0
    bad_unicode: int = 0


class _ChunkedWriter:
    """Write blocks to ``<stem>.partNNNN<ext>``, starting a new part when one is full.

    A part only exceeds *limit* when a single block is larger than it. With a
    single part the file is renamed to ``<stem><ext>``.
    """

    def __init__(self, directory: Path, stem: str, ext: str, limit: int, header: bytes = b""):
        self.directory = directory
        self.stem = stem
        self.ext = ext
        self.limit = limit
        self.header = header
        self.parts: list[Path] = []
        self._fh = None
        self._size = 0
        self._has_payload = False

    def write(self, block: bytes) -> None:
        if self._fh is None or (self._has_payload and self._size + len(block) > self.limit):
            self._open_next()
        self._fh.write(block)
        self._size += len(block)
        self._has_payload = True

    def _open_next(self) -> None:
        self.close()
        self.directory.mkdir(parents=True, exist_ok=True)
        path = self.directory / f"{self.stem}.part{len(self.parts) + 1:04d}{self.ext}"
        self._fh = path.open("wb", buffering=MB)
        self.parts.append(path)
        self._size = len(self.header)
        self._has_payload = False
        self._fh.write(self.header)

    def close(self) -> None:
        if self._fh is not None:
            self._fh.close()
            self._fh = None

    def finish(self, empty_body: bytes = b"") -> list[Path]:
        if self._fh is None and not self.parts:
            self._open_next()
            self._fh.write(empty_body)
        self.close()
        if len(self.parts) == 1:
            single = self.directory / f"{self.stem}{self.ext}"
            self.parts[0].replace(single)
            self.parts = [single]
        return self.parts


def _export_table_data(
    db_dir: Path,
    stem: str,
    tddl: TableDDL,
    columns: list[str],
    data_reader: DataReader,
    data_format: str,
    batch_size: int,
    limit: int,
) -> _TableData:
    table = tddl.table
    stats = _TableData()
    ncols = len(columns)
    target = f"{tddl.target_schema}.{tddl.target_table}"

    def rows() -> Iterator[tuple]:
        for batch in data_reader(table):
            for row in batch:
                if len(row) != ncols:
                    raise ValueError(
                        f"{table.qualified}: a row has {len(row)} values but the table has "
                        f"{ncols} columns"
                    )
                stats.nul_chars += _nul_count(row)
                stats.rows += 1
                yield row

    if data_format == "copy":
        writer = _ChunkedWriter(db_dir / "data", stem, ".tsv", limit)
        with contextlib.closing(writer):
            for row in rows():
                block, bad = _to_utf8(encode_copy_row(row))
                stats.bad_unicode += bad
                writer.write(block)
            parts = writer.finish()
    else:
        header = f"{GENERATED} Data for {_comment(table.qualified)} -> {target}.\n".encode()
        writer = _ChunkedWriter(db_dir / "data", stem, ".sql", limit, header=header)
        qualified = f"{quote_ident(tddl.target_schema)}.{quote_ident(tddl.target_table)}"
        col_list = ", ".join(quote_ident(c) for c in columns)
        insert = f"INSERT INTO {qualified} ({col_list}) VALUES\n".encode()
        pending: list[bytes] = []
        pending_bytes = 0
        with contextlib.closing(writer):
            for row in rows():
                block, bad = _to_utf8("(" + ", ".join([encode_sql_literal(v) for v in row]) + ")")
                stats.bad_unicode += bad
                pending.append(block)
                pending_bytes += len(block) + 2
                if len(pending) >= batch_size or pending_bytes >= INSERT_STATEMENT_MAX_BYTES:
                    writer.write(insert + b",\n".join(pending) + b";\n")
                    pending, pending_bytes = [], 0
            if pending:
                writer.write(insert + b",\n".join(pending) + b";\n")
            empty = f"-- (no rows in {_comment(table.qualified)})\n".encode()
            parts = writer.finish(empty_body=empty)

    stats.files = [f"data/{p.name}" for p in parts]
    stats.bytes = sum(p.stat().st_size for p in parts)
    return stats


def _clean_previous_export(db_dir: Path) -> None:
    for name in _GENERATED_DIRS:
        path = db_dir / name
        if path.is_dir() and not path.is_symlink():
            shutil.rmtree(path)
    for name in _GENERATED_FILES:
        path = db_dir / name
        if path.is_file():
            path.unlink()


def _write_text(path: Path, text: str) -> int:
    """Write *text* as UTF-8 exactly (no newline translation). Returns replaced chars."""
    path.parent.mkdir(parents=True, exist_ok=True)
    data, bad = _to_utf8(text)
    path.write_bytes(data)
    return bad


def _sql_file(header_lines: list[str], statements: list[str], *, empty: str) -> str:
    lines = [GENERATED, *(f"-- {_comment(h)}" for h in header_lines), ""]
    lines += statements if statements else [f"-- {empty}"]
    return "\n".join(lines) + "\n"


def _one_line(statement: str) -> str:
    return " ".join(statement.split())


def _unique_stem(stem: str, used: set[str], warnings: list[str], what: str) -> str:
    candidate, n = stem, 2
    while candidate in used:
        candidate = f"{stem}_{n}"
        n += 1
    used.add(candidate)
    if candidate != stem:
        warnings.append(
            f"{what}: file name {stem} already used by another object; written as {candidate}"
        )
    return candidate


def _flag_text(flag) -> str:
    return f"{flag.severity}: {flag.message}" + (f" [{flag.snippet}]" if flag.snippet else "")


def _view_order(views: list[dict]) -> list[dict]:
    """Order views so a view comes after the views its body references.

    References are found by name, so a false match only changes the order; a
    cycle falls back to file-name order for the views involved.
    """
    if len(views) < 2:
        return views
    by_name: dict[str, list[int]] = {}
    for i, v in enumerate(views):
        by_name.setdefault(v["_name"], []).append(i)
    names = sorted(by_name, key=len, reverse=True)
    pattern = re.compile(
        r"(?<![\w$])(" + "|".join(re.escape(n) for n in names) + r")(?![\w$])", re.IGNORECASE
    )
    deps: list[set[int]] = []
    for i, v in enumerate(views):
        body = v["_ddl"].split(" AS\n", 1)[-1]
        found = {j for m in pattern.finditer(body) for j in by_name.get(m.group(1).lower(), [])}
        deps.append(found - {i})
    users: dict[int, set[int]] = {i: set() for i in range(len(views))}
    for i, d in enumerate(deps):
        for j in d:
            users[j].add(i)
    remaining = [len(d) for d in deps]
    ready = [(views[i]["file"], i) for i, n in enumerate(remaining) if n == 0]
    heapq.heapify(ready)
    order: list[int] = []
    while ready:
        _, i = heapq.heappop(ready)
        order.append(i)
        for u in users[i]:
            remaining[u] -= 1
            if remaining[u] == 0:
                heapq.heappush(ready, (views[u]["file"], u))
    placed = set(order)
    order += sorted((i for i in range(len(views)) if i not in placed), key=lambda i: views[i]["file"])
    return [views[i] for i in order]


def export_database(
    plan: Plan,
    db: Database,
    out_root: Path,
    data_reader: DataReader | None = None,
    data_format: str = "insert",
    max_data_file_mb: float = DEFAULT_MAX_DATA_FILE_MB,
    *,
    generated_at: str | None = None,
) -> ExportResult:
    """Write the per-object dump for one database into ``out_root/<db>/``.

    ``data_reader`` yields row batches per table; pass ``None`` (or set
    ``plan.migration.data`` false) to export schema only. ``data_format`` is
    ``"insert"`` (``.sql`` INSERT statements) or ``"copy"`` (``.tsv`` COPY text).
    A table's data is split into ``.partNNNN`` files so that no file grows past
    ``max_data_file_mb``; INSERT statements hold at most
    ``plan.migration.batch_size`` rows or about 1 MB. Files generated by an
    earlier export in the same directory are removed first; ``manifest.json`` is
    written last, so its presence marks a complete export.
    """
    if data_format not in DATA_FORMATS:
        raise ValueError(f"data_format must be one of {DATA_FORMATS}, not {data_format!r}")
    if not max_data_file_mb > 0:
        raise ValueError("max_data_file_mb must be greater than 0")

    db_dir = Path(out_root) / sanitize_identifier(db.name)
    _clean_previous_export(db_dir)
    db_dir.mkdir(parents=True, exist_ok=True)
    # Text values keep their CR/LF inside SQL literals and the source/ files are
    # verbatim: stop git from converting line endings anywhere in the dump.
    (db_dir / ".gitattributes").write_bytes(GITATTRIBUTES.encode())
    result = ExportResult(database=db.name, out_dir=db_dir)
    warnings = result.warnings
    export_data = plan.migration.data and data_reader is not None
    limit = max(1, int(max_data_file_mb * MB))
    batch_size = max(1, int(plan.migration.batch_size))
    bad_unicode = 0

    smap = schema_map_for(plan, db)
    target_schemas = sorted(set(smap.values()))
    schema_stmts = schema_create_statements(plan, db)
    bad_unicode += _write_text(
        db_dir / "00_schemas.sql",
        _sql_file([f"Target schemas for {db.name}. Run first."], schema_stmts,
                  empty="(no schemas)"),
    )
    result.schemas = len(schema_stmts)

    # Tables: DDL file, then data file(s) per table, in (schema, table) order.
    tddls = sorted(
        build_table_statements(plan, db),
        key=lambda t: (t.target_schema, t.target_table, t.table.qualified),
    )
    used: set[str] = set()
    table_entries: list[dict] = []
    data_order: list[str] = []
    for tddl in tddls:
        table = tddl.table
        stem = _unique_stem(
            f"{tddl.target_schema}__{tddl.target_table}", used, warnings, f"table {table.qualified}"
        )
        table_file = f"tables/{stem}.sql"
        header = [f"Table {table.qualified} -> {tddl.target_schema}.{tddl.target_table}"]
        header += [f"NOTE: {n}" for n in tddl.notes]
        bad_unicode += _write_text(
            db_dir / table_file,
            _sql_file(header, [tddl.create_sql, *tddl.index_sqls], empty="(no DDL)"),
        )
        columns = [spec.name for spec in plan_columns(table, db.kind)]
        entry = {
            "source": table.qualified,
            "target_schema": tddl.target_schema,
            "target_table": tddl.target_table,
            "columns": len(table.columns),
            "column_names": columns,
            "approx_source_rows": table.approx_row_count,
            "exported_rows": None,
            "table_file": table_file,
            "data_files": [],
            "notes": list(tddl.notes),
        }
        if export_data:
            stats = _export_table_data(
                db_dir, stem, tddl, columns, data_reader, data_format, batch_size, limit
            )
            entry["exported_rows"] = stats.rows
            entry["data_files"] = stats.files
            data_order += stats.files
            result.rows += stats.rows
            result.data_bytes += stats.bytes
            if stats.nul_chars:
                warnings.append(
                    f"{table.qualified}: stripped {stats.nul_chars} NUL character(s) from text "
                    "values (PostgreSQL text cannot store NUL)"
                )
            if stats.bad_unicode:
                warnings.append(
                    f"{table.qualified}: replaced {stats.bad_unicode} invalid Unicode "
                    "character(s) (unpaired surrogates) with U+FFFD"
                )
        table_entries.append(entry)
    result.tables = len(table_entries)
    result.data_files = data_order

    # Post-load statements: identity resets and foreign keys, one per line.
    seq_stmts = [_one_line(s) for t in tddls for s in t.identity_reset_sqls]
    fk_stmts = [_one_line(s) for t in tddls for s in t.fk_sqls]
    bad_unicode += _write_text(
        db_dir / "sequences.sql",
        _sql_file(["Identity sequence resets: run after all data is loaded.",
                   "One statement per line."], seq_stmts, empty="(no identity columns)"),
    )
    bad_unicode += _write_text(
        db_dir / "foreign_keys.sql",
        _sql_file(["Foreign keys: run after all data is loaded.", "One statement per line."],
                  fk_stmts, empty="(no foreign keys)"),
    )

    # Views: converted DDL + original T-SQL, ordered so dependencies load first.
    used = set()
    views: list[dict] = []
    for view in sorted(db.views, key=lambda v: (smap[v.schema], sanitize_identifier(v.name),
                                                 v.qualified)):
        tschema = smap[view.schema]
        conv = convert_view(view, tschema, smap, db.kind)
        stem = _unique_stem(f"{tschema}__{conv.view_name}", used, warnings, f"view {view.qualified}")
        file, source_file = f"views/{stem}.sql", f"source/views/{stem}.sql"
        ddl = conv.ddl.replace("\x00", "")
        bad_unicode += _write_text(
            db_dir / file,
            _sql_file([f"View {view.qualified} -> {tschema}.{conv.view_name}",
                       f"Original T-SQL: {source_file}"], [ddl], empty="(empty)"),
        )
        bad_unicode += _write_text(db_dir / source_file, view.definition)
        views.append({
            "source": view.qualified,
            "target": f"{tschema}.{conv.view_name}",
            "file": file,
            "source_file": source_file,
            "review_items": [_flag_text(f) for f in conv.flags],
            "_name": conv.view_name,
            "_ddl": ddl,
        })
        result.review_items += [
            f"view {view.qualified}: {f.message}" for f in conv.flags if f.severity == "manual"
        ]
    view_load_order = [v["file"] for v in _view_order(views)]
    for v in views:
        del v["_name"], v["_ddl"]
    result.views = len(views)

    # Routines: converted procedures and functions + original T-SQL.
    used = set()
    routines: list[dict] = []
    for routine in sorted(db.routines, key=lambda r: (smap[r.schema], sanitize_identifier(r.name),
                                                      r.schema, r.name)):
        tschema = smap[routine.schema]
        conv = convert_routine(routine, tschema)
        source = f"{routine.schema}.{routine.name}"
        stem = _unique_stem(f"{tschema}__{conv.routine_name}", used, warnings,
                            f"{routine.kind} {source}")
        file, source_file = f"routines/{stem}.sql", f"source/routines/{stem}.sql"
        header = [f"{routine.kind.capitalize()} {source} -> {tschema}.{conv.routine_name}",
                  f"Original source: {source_file}"]
        if not conv.converted:
            header.append("NOT CONVERTED: port by hand from the original source.")
        bad_unicode += _write_text(
            db_dir / file, _sql_file(header, [conv.ddl.replace("\x00", "")], empty="(empty)")
        )
        bad_unicode += _write_text(db_dir / source_file, routine.definition)
        routines.append({
            "source": source,
            "target": f"{tschema}.{conv.routine_name}",
            "kind": routine.kind,
            "converted": conv.converted,
            "file": file,
            "source_file": source_file,
            "review_items": [_flag_text(f) for f in conv.flags],
        })
        result.review_items += [
            f"routine {source}: {f.message}" for f in conv.flags if f.severity == "manual"
        ]
        if routine.kind == "procedure":
            result.procedures += 1
        else:
            result.functions += 1

    if bad_unicode:
        warnings.append(
            f"replaced {bad_unicode} invalid Unicode character(s) (unpaired surrogates) with "
            "U+FFFD in DDL or source files"
        )
    if not export_data:
        warnings.append("table data was not exported (schema only)")

    load_order = ["00_schemas.sql", *(e["table_file"] for e in table_entries), *data_order,
                  "sequences.sql", "foreign_keys.sql", *view_load_order,
                  *(r["file"] for r in routines)]
    manifest = {
        "database": db.name,
        "subscription": db.subscription,
        "server": db.server,
        "kind": db.kind.value,
        "generated_at": generated_at or _utc_now(),
        "data_format": data_format if export_data else None,
        "max_data_file_mb": max_data_file_mb,
        "target_schemas": target_schemas,
        "counts": {
            "schemas": result.schemas,
            "tables": result.tables,
            "views": result.views,
            "procedures": result.procedures,
            "functions": result.functions,
            "routines": result.routines,
            "rows": result.rows,
            "data_files": len(result.data_files),
            "data_bytes": result.data_bytes,
        },
        "tables": table_entries,
        "views": views,
        "routines": routines,
        "warnings": warnings,
        "review_items": result.review_items,
        "load_order": load_order,
    }
    tmp = db_dir / "manifest.json.tmp"
    tmp.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    tmp.replace(db_dir / "manifest.json")
    result.manifest = manifest
    return result


def _utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


# --- SQL splitting -------------------------------------------------------------------

_SQL_TOKEN = re.compile(
    r"(?<![\w$])[Ee]'(?:[^'\\]|\\.|'')*'"  # E'...' escape string
    r"|'[^']*(?:''[^']*)*'"  # '...' string ('' is a quote)
    r'|"[^"]*(?:""[^"]*)*"'  # "quoted identifier"
    r"|--[^\n]*"  # line comment
    r"|/\*"  # block comment (may nest)
    r"|(?<![\w$])\$(?:[^\W\d]\w*)?\$"  # dollar-quote tag
    r"|;",
    re.DOTALL,
)
_BLOCK_COMMENT = re.compile(r"/\*|\*/")
_NON_SPACE = re.compile(r"\S")


def _skip_block_comment(text: str, pos: int) -> int:
    depth = 1
    while depth:
        m = _BLOCK_COMMENT.search(text, pos)
        if m is None:
            return len(text)
        depth += 1 if m.group() == "/*" else -1
        pos = m.end()
    return pos


def split_sql_statements(text: str) -> list[str]:
    """Split a SQL script into statements on top-level ``;``.

    Quotes, quoted identifiers, dollar quoting and (nested) comments are
    respected; statements holding nothing but comments are dropped.
    """
    statements: list[str] = []
    start = pos = 0
    has_code = False
    while True:
        m = _SQL_TOKEN.search(text, pos)
        gap_end = m.start() if m else len(text)
        if not has_code and _NON_SPACE.search(text, pos, gap_end):
            has_code = True
        if m is None:
            break
        token = m.group()
        pos = m.end()
        if token == ";":
            if has_code:
                statements.append(text[start:pos].strip())
            start, has_code = pos, False
        elif token.startswith("--"):
            continue
        elif token == "/*":
            pos = _skip_block_comment(text, pos)
        elif token.startswith("$"):
            close = text.find(token, pos)
            pos = len(text) if close < 0 else close + len(token)
            has_code = True
        else:
            has_code = True
    tail = text[start:].strip()
    if has_code and tail:
        statements.append(tail)
    return statements


# --- load ------------------------------------------------------------------------

# Session settings the dump relies on (INSERT literals assume standard strings).
_SESSION_SETTINGS = (
    "SET standard_conforming_strings = on",
    "SET statement_timeout = 0",
    "SET client_min_messages = warning",
    "SET xmloption = content",
    "SET DateStyle = 'ISO, YMD'",
    "SET TimeZone = 'UTC'",
)
_PER_STATEMENT_FILES = ("sequences.sql", "foreign_keys.sql")
_RETRYABLE_PREFIXES = ("views/", "routines/")
_MAX_ERROR_CHARS = 2000


def redact_url(url: str) -> str:
    """Return a connection URL/DSN with any password replaced by ``***``."""
    if "://" not in url:
        return re.sub(r"(?i)(password\s*=\s*)('(?:[^'\\]|\\.)*'|\S+)", r"\1***", url)
    parts = urlsplit(url)
    netloc = parts.netloc
    if "@" in netloc:
        userinfo, _, hostinfo = netloc.rpartition("@")
        if ":" in userinfo:
            netloc = f"{userinfo.split(':', 1)[0]}:***@{hostinfo}"
    query = re.sub(r"(?i)(^|&)(password=)[^&]*", r"\1\2***", parts.query)
    return urlunsplit((parts.scheme, netloc, parts.path, query, parts.fragment))


def _secrets_in(url: str) -> list[str]:
    """Passwords present in *url* (or the environment), to scrub from error text."""
    found: list[str] = []
    user = ""
    if "://" in url:
        parts = urlsplit(url)
        userinfo = parts.netloc.rpartition("@")[0] if "@" in parts.netloc else ""
        user = unquote(userinfo.split(":", 1)[0])
        if ":" in userinfo:
            raw = userinfo.split(":", 1)[1]
            found += [raw, unquote(raw)]
        found += [v for k, v in parse_qsl(parts.query) if k.lower() == "password"]
    else:
        found += [m.group(1).strip("'") for m in re.finditer(r"(?i)password\s*=\s*(\S+)", url)]
    found.append(os.environ.get("SUPABASE_DB_PASSWORD", ""))
    # Very short values, or one equal to the user name, would mangle ordinary text.
    return sorted({s for s in found if len(s) >= 6 and s != user}, key=len, reverse=True)


def _kind_of(rel: str) -> str:
    if rel == "00_schemas.sql":
        return "schemas"
    if rel in _PER_STATEMENT_FILES:
        return rel.removesuffix(".sql")
    head = rel.split("/", 1)[0] if "/" in rel else ""
    return head if head in ("tables", "data", "views", "routines") else "other"


def _preview(statement: str, limit: int = 300) -> str:
    while statement.startswith("--"):  # drop leading comment lines (file headers)
        statement = statement.partition("\n")[2].lstrip()
    text = " ".join(statement.split())
    return text if len(text) <= limit else text[: limit - 3] + "..."


class _StatementError(Exception):
    def __init__(self, index: int, statement: str, cause: Exception):
        super().__init__(str(cause))
        self.index = index
        self.statement = statement
        self.cause = cause


class _Target:
    """A psycopg connection (autocommit; transactions opened explicitly)."""

    def __init__(self, url: str):
        self.url = url
        self.conn = None

    def ensure(self) -> None:
        if self.conn is not None and not self.conn.closed and not self.conn.broken:
            return
        self.close()
        import psycopg

        self.conn = psycopg.connect(
            self.url, autocommit=True, prepare_threshold=None, client_encoding="UTF8"
        )
        with self.conn.cursor() as cur:
            for setting in _SESSION_SETTINGS:
                cur.execute(setting)

    def close(self) -> None:
        if self.conn is not None:
            with contextlib.suppress(Exception):  # closing a broken connection
                self.conn.close()
            self.conn = None

    def run_statements(self, statements: list[str]) -> int:
        """Run *statements* in one transaction. Returns rows affected."""
        rows = 0
        with self.conn.transaction(), self.conn.cursor() as cur:
            for i, stmt in enumerate(statements):
                try:
                    cur.execute(stmt)
                except Exception as exc:
                    raise _StatementError(i, stmt, exc) from exc
                rows += max(cur.rowcount, 0)
        return rows

    def run_copy(self, path: Path, qualified: str, columns: list[str]) -> int:
        cols = f" ({', '.join(quote_ident(c) for c in columns)})" if columns else ""
        with self.conn.transaction(), self.conn.cursor() as cur:
            with cur.copy(f"COPY {qualified}{cols} FROM STDIN") as copy, path.open("rb") as fh:
                while chunk := fh.read(MB):
                    copy.write(chunk)
            return max(cur.rowcount, 0)

    def count_rows(self, qualified: str) -> int:
        with self.conn.transaction(), self.conn.cursor() as cur:
            cur.execute(f"SELECT count(*) FROM {qualified}")
            return int(cur.fetchone()[0])


def _resolve_inside(root: Path, rel: str) -> Path | None:
    """``root / rel`` if it stays inside *root*, else None (manifest paths are untrusted)."""
    root = root.resolve()
    path = (root / rel).resolve()
    return path if root in path.parents else None


class _DumpLoader:
    """Runs load_order entries against a :class:`_Target` and builds result entries."""

    def __init__(self, dump_dir: Path, target: _Target, manifest: dict, secrets: list[str],
                 stop_on_error: bool):
        self.dump_dir = dump_dir
        self.target = target
        self.secrets = secrets
        self.stop_on_error = stop_on_error
        self.tables = [t for t in manifest.get("tables") or [] if isinstance(t, dict)]
        self.by_data_file = {f: t for t in self.tables for f in t.get("data_files") or []}

    def scrub(self, text: str) -> str:
        for secret in self.secrets:
            text = text.replace(secret, "***")
        return text[:_MAX_ERROR_CHARS]

    def entry(self, rel: str, ok: bool, error: object = None, **extra) -> dict:
        item = {"file": rel, "kind": _kind_of(rel), "ok": ok, **extra}
        if error is not None:
            item["error"] = self.scrub(str(error).strip() or type(error).__name__)
            sqlstate = getattr(getattr(error, "diag", None), "sqlstate", None)
            if sqlstate:
                item["sqlstate"] = sqlstate
        return item

    def attempt(self, rel: str) -> list[dict]:
        """Load one load_order entry. Returns its result entries (one per statement
        for sequences.sql / foreign_keys.sql, otherwise exactly one)."""
        path = _resolve_inside(self.dump_dir, rel)
        if path is None or not path.is_file():
            return [self.entry(rel, False, "file not found inside the dump directory")]
        try:
            self.target.ensure()
        except Exception as exc:  # noqa: BLE001 - reported, never raised
            return [self.entry(rel, False, f"cannot connect: {exc}")]

        if rel.startswith("data/") and path.suffix == ".tsv":
            table = self.by_data_file.get(rel)
            if table is None:
                return [self.entry(rel, False, "no table in manifest.json lists this data file")]
            qualified = f"{quote_ident(table['target_schema'])}.{quote_ident(table['target_table'])}"
            try:
                rows = self.target.run_copy(path, qualified, list(table.get("column_names") or []))
            except Exception as exc:  # noqa: BLE001
                return [self.entry(rel, False, exc)]
            return [self.entry(rel, True, rows=rows)]

        try:
            # Bytes, not read_text(): universal newlines would turn a CR inside a
            # string literal into LF and silently change the data.
            statements = split_sql_statements(path.read_bytes().decode("utf-8"))
        except (OSError, UnicodeDecodeError) as exc:
            return [self.entry(rel, False, exc)]

        if rel in _PER_STATEMENT_FILES:
            entries = []
            for stmt in statements:
                try:
                    self.target.ensure()
                    self.target.run_statements([stmt])
                except _StatementError as exc:
                    entries.append(self.entry(rel, False, exc.cause, statement=_preview(stmt)))
                except Exception as exc:  # noqa: BLE001
                    entries.append(self.entry(rel, False, exc, statement=_preview(stmt)))
                else:
                    entries.append(self.entry(rel, True, statement=_preview(stmt)))
                if not entries[-1]["ok"] and self.stop_on_error:
                    break
            return entries or [self.entry(rel, True, statements=0)]

        try:
            rows = self.target.run_statements(statements)
        except _StatementError as exc:
            return [self.entry(rel, False, exc.cause, statement=_preview(exc.statement),
                               statement_index=exc.index + 1, statements=len(statements))]
        except Exception as exc:  # noqa: BLE001
            return [self.entry(rel, False, exc, statements=len(statements))]
        extra = {"rows": rows} if rel.startswith("data/") else {}
        return [self.entry(rel, True, statements=len(statements), **extra)]

    def row_checks(self) -> list[dict]:
        checks = []
        for t in self.tables:
            if t.get("exported_rows") is None:
                continue
            check = {"table": f"{t['target_schema']}.{t['target_table']}",
                     "source": t.get("source"), "expected": t["exported_rows"],
                     "actual": None, "match": False}
            try:
                self.target.ensure()
                check["actual"] = self.target.count_rows(
                    f"{quote_ident(t['target_schema'])}.{quote_ident(t['target_table'])}"
                )
                check["match"] = check["actual"] == check["expected"]
            except Exception as exc:  # noqa: BLE001
                check["error"] = self.scrub(str(exc).strip())
            checks.append(check)
        return checks


def _read_manifest(dump_dir: Path) -> tuple[dict, str | None]:
    """Return (manifest, None), or ({}, why it cannot be used)."""
    try:
        manifest = json.loads((dump_dir / "manifest.json").read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        return {}, str(exc)
    if not isinstance(manifest, dict) or not isinstance(manifest.get("load_order"), list):
        return {}, "manifest.json has no load_order list"
    return manifest, None


def load_dump(dump_dir: Path | str, target_url: str, stop_on_error: bool = False) -> dict:
    """Load an export directory into the Postgres database at *target_url*.

    Follows ``manifest.json``'s ``load_order``: each file runs in its own
    transaction, except ``sequences.sql`` and ``foreign_keys.sql`` whose
    statements (one per line) each run in their own transaction. Every file or
    statement outcome is recorded; loading continues past failures unless
    *stop_on_error*. A failed view or routine is retried once the rest has
    loaded (it may use an object that loads later). Finally every table's row
    count is compared with ``exported_rows``. Returns the report (JSON-able,
    password redacted); ``report["ok"]`` is False on any failure or mismatch.
    """
    dump_dir = Path(dump_dir)
    results: list[dict] = []
    report: dict = {
        "dump_dir": str(dump_dir),
        "database": None,
        "target": redact_url(target_url),
        "started_at": _utc_now(),
        "finished_at": None,
        "ok": False,
        "stopped_early": False,
        "totals": {},
        "by_kind": {},
        "failures": [],
        "row_checks": [],
        "results": results,
    }
    target = _Target(target_url)
    manifest, problem = _read_manifest(dump_dir)
    if problem:
        results.append({"file": "manifest.json", "kind": "other", "ok": False, "error": problem})
    loader = _DumpLoader(dump_dir, target, manifest, _secrets_in(target_url), stop_on_error)
    report["database"] = manifest.get("database")

    if manifest:
        try:
            target.ensure()
        except Exception as exc:  # noqa: BLE001 - reported, never raised
            results.append(loader.entry("(connect)", False, exc))
            manifest = {}

    if manifest:
        # Failed views/routines: (file, entries of the latest attempt), decided
        # after everything else has loaded.
        deferred: list[tuple[str, list[dict]]] = []
        for rel in (str(r) for r in manifest["load_order"]):
            entries = loader.attempt(rel)
            ok = all(e["ok"] for e in entries)
            if not ok and rel.startswith(_RETRYABLE_PREFIXES):
                deferred.append((rel, entries))
                continue
            results.extend(entries)
            if not ok and stop_on_error:
                report["stopped_early"] = True
                break
        attempts = 1
        while deferred and not report["stopped_early"]:
            attempts += 1
            outcomes = [(rel, loader.attempt(rel)) for rel, _ in deferred]
            for _, entries in outcomes:
                for e in entries:
                    e["attempts"] = attempts
            done = [entries for _, entries in outcomes if all(e["ok"] for e in entries)]
            if not done or len(done) == len(outcomes):  # no progress, or all loaded
                deferred = outcomes
                break
            for entries in done:
                results.extend(entries)
            deferred = [(rel, e) for rel, e in outcomes if not all(x["ok"] for x in e)]
        for _, entries in deferred:
            results.extend(entries)
        if any(not e["ok"] for _, entries in deferred for e in entries) and stop_on_error:
            report["stopped_early"] = True
        if not report["stopped_early"]:
            report["row_checks"] = loader.row_checks()
    target.close()

    failures = []
    for r in results:
        if not r["ok"]:
            failure = {"file": r["file"]}
            if "statement" in r:
                failure["statement"] = r["statement"]
            failure["error"] = r.get("error", "")
            failures.append(failure)
    by_kind: dict[str, dict[str, int]] = {}
    for r in results:
        counts = by_kind.setdefault(r["kind"], {"ok": 0, "failed": 0})
        counts["ok" if r["ok"] else "failed"] += 1
    mismatches = sum(1 for c in report["row_checks"] if not c["match"])
    report["failures"] = failures
    report["by_kind"] = by_kind
    report["totals"] = {
        "ok": len(results) - len(failures),
        "failed": len(failures),
        "row_mismatches": mismatches,
        "rows_loaded": sum(r.get("rows", 0) for r in results if r["ok"]),
    }
    report["ok"] = not failures and not mismatches and not report["stopped_early"]
    report["finished_at"] = _utc_now()
    return report


def iter_failures(report: dict) -> Iterable[str]:
    """One human-readable line per failure / row mismatch in a load report."""
    for f in report.get("failures", []):
        where = f["file"] + (f" [{f['statement']}]" if f.get("statement") else "")
        yield f"{where}: {_comment(f.get('error', ''))}"
    for c in report.get("row_checks", []):
        if not c["match"]:
            yield (f"{c['table']}: expected {c['expected']} rows, found {c['actual']}"
                   + (f" ({_comment(c['error'])})" if c.get("error") else ""))
