-- Generated by dbmigration.
-- Table dbo.TableMetadataDictionary -> livebit_dbo.tablemetadatadictionary

CREATE TABLE IF NOT EXISTS "livebit_dbo"."tablemetadatadictionary" (
  "tableid" text,
  "tablename" text,
  "tablerowcount" text,
  "tablecolumncount" text,
  "primarykeycsv" text,
  "tableuniquecolumncsv" text,
  "table_semantic_name" text,
  "table_summary_description" text,
  "table_sensitivity_level" text,
  "table_sample_questions_min_5_and_max_10" text,
  "table_llm_gpt_keywords_synonyms" text,
  "table_related_tables_csv_seprated" text,
  "table_usage_notes" text,
  "review_by" text,
  "ischanged" text,
  "change_comment_vp_1223_why_changed" text
);
