-- Generated by dbmigration.
-- Table aidd.usage_events -> livebit_aidd.usage_events
-- NOTE: column event_at: datetimeoffset -> timestamptz: instant kept, original UTC offset not kept; fractional seconds rounded to microseconds
-- NOTE: column created_at: datetimeoffset -> timestamptz: instant kept, original UTC offset not kept; fractional seconds rounded to microseconds
-- NOTE: column updated_at: datetimeoffset -> timestamptz: instant kept, original UTC offset not kept; fractional seconds rounded to microseconds

CREATE TABLE IF NOT EXISTS "livebit_aidd"."usage_events" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "tokens_input" integer,
  "tokens_output" integer,
  "cost_usd" numeric(10,6),
  "event_at" timestamptz DEFAULT now(),
  "tenant_id" uuid NOT NULL,
  "user_id" uuid,
  "request_id" uuid,
  "model_id" uuid,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL,
  PRIMARY KEY ("id")
);
