-- Generated by dbmigration.
-- Table aidd.llm_requests -> livebit_aidd.llm_requests
-- NOTE: column created_at: datetimeoffset -> timestamptz: instant kept, original UTC offset not kept; fractional seconds rounded to microseconds
-- NOTE: column updated_at: datetimeoffset -> timestamptz: instant kept, original UTC offset not kept; fractional seconds rounded to microseconds

CREATE TABLE IF NOT EXISTS "livebit_aidd"."llm_requests" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "prompt_hash" varchar(255),
  "prompt_excerpt" varchar(1000),
  "private" boolean DEFAULT false,
  "latency_ms" integer,
  "tenant_id" uuid NOT NULL,
  "user_id" uuid,
  "conversation_id" uuid,
  "message_id" uuid,
  "route_applied_id" uuid,
  "selected_model_id" uuid,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL,
  PRIMARY KEY ("id")
);
