-- Generated by dbmigration.
-- Table divaconfig.StoredProcedureParameters -> livebit_divaconfig.storedprocedureparameters

CREATE TABLE IF NOT EXISTS "livebit_divaconfig"."storedprocedureparameters" (
  "parameterid" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "procedureid" integer NOT NULL,
  "parametername" varchar(255) NOT NULL,
  "parameterdatatype" varchar(50),
  "parameterisoptional" boolean DEFAULT false,
  "parameterdefaultvalue" varchar(255),
  "parameterdefaultdynamicvalue" varchar(255),
  "type2active" boolean DEFAULT true NOT NULL,
  "type2startdate" timestamp DEFAULT now(),
  "type2enddate" timestamp,
  PRIMARY KEY ("parameterid")
);
