-- Generated by dbmigration.
-- Table divaconfig.sampleData_sample -> livebit_divaconfig.sampledata_sample
-- NOTE: column CreatedTime: fractional seconds rounded to microseconds

CREATE TABLE IF NOT EXISTS "livebit_divaconfig"."sampledata_sample" (
  "masterdataid" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "mastername" varchar(255) NOT NULL,
  "mastervalue" text NOT NULL,
  "masterdisplaytext" text,
  "masterdescription" text,
  "isactive" boolean NOT NULL,
  "createddate" date NOT NULL,
  "createdtime" time NOT NULL,
  "createddatetime" timestamp NOT NULL,
  "masterint" integer,
  "masterfloat" double precision,
  "sortorder" integer,
  "createdat" timestamp NOT NULL,
  "updatedat" timestamp NOT NULL
);
