-- Generated by dbmigration.
-- Table aidd.tenants -> livebit_aidd.tenants
-- NOTE: column created_at: datetimeoffset -> timestamptz: instant kept, original UTC offset not kept; fractional seconds rounded to microseconds
-- NOTE: column updated_at: datetimeoffset -> timestamptz: instant kept, original UTC offset not kept; fractional seconds rounded to microseconds

CREATE TABLE IF NOT EXISTS "livebit_aidd"."tenants" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "name" varchar(255) NOT NULL,
  "slug" varchar(255) NOT NULL,
  "status" varchar(50) DEFAULT 'active',
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "tenants_tenants_slug" ON "livebit_aidd"."tenants" ("slug");
CREATE UNIQUE INDEX IF NOT EXISTS "tenants_uq__tenants__32dd1e4cc9cbc37e" ON "livebit_aidd"."tenants" ("slug");
