-- Generated by dbmigration.
-- Table dbo.DMS_FactFunctionaStatsBRIMArchive -> livebit_dbo.dms_factfunctionastatsbrimarchive

CREATE TABLE IF NOT EXISTS "livebit_dbo"."dms_factfunctionastatsbrimarchive" (
  "syncdatatype" varchar(100),
  "configidcount" integer,
  "totoalattributevalue" integer,
  "attributevaluematched" integer,
  "attributevaluenotmatched" integer,
  "percentagematched" double precision,
  "percentagenotmatched" double precision,
  "archiveddate" timestamp NOT NULL
);
