-- Generated by dbmigration.
-- Table dbo.DMS_SharePoint_Patient_Base -> livebit_dbo.dms_sharepoint_patient_base

CREATE TABLE IF NOT EXISTS "livebit_dbo"."dms_sharepoint_patient_base" (
  "patientid" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "firstname" varchar(50) NOT NULL,
  "lastname" varchar(50) NOT NULL,
  "dateofbirth" date NOT NULL,
  "gender" char(1),
  "phonenumber" varchar(15),
  "email" varchar(100),
  "address" varchar(255),
  "city" varchar(100),
  "state" varchar(50),
  "postalcode" varchar(20),
  "country" varchar(50),
  "emergencycontact" varchar(100),
  "emergencyphone" varchar(15),
  "insuranceprovider" varchar(100),
  "insurancenumber" varchar(50),
  "allergies" varchar(50),
  "medicalhistory" varchar(50),
  "datecreated" timestamp,
  "datemodified" timestamp,
  "patientname" varchar(100)
);
