-- Generated by dbmigration.
-- Table aidd.routing_rules -> livebit_aidd.routing_rules
-- NOTE: column created_at: datetimeoffset -> timestamptz: instant kept, original UTC offset not kept; fractional seconds rounded to microseconds
-- NOTE: column updated_at: datetimeoffset -> timestamptz: instant kept, original UTC offset not kept; fractional seconds rounded to microseconds

CREATE TABLE IF NOT EXISTS "livebit_aidd"."routing_rules" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "name" varchar(255) NOT NULL,
  "criteria" text DEFAULT '{}',
  "strategy" varchar(50) NOT NULL,
  "fallback_model_ids" text DEFAULT '[]',
  "active" boolean DEFAULT true,
  "tenant_id" uuid NOT NULL,
  "primary_model_id" uuid,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL,
  PRIMARY KEY ("id")
);
