-- Generated by dbmigration.
-- Table dbo.DMS_FTP_Medicine -> livebit_dbo.dms_ftp_medicine

CREATE TABLE IF NOT EXISTS "livebit_dbo"."dms_ftp_medicine" (
  "medicineid" integer NOT NULL,
  "medicinename" varchar(100),
  "medicinecategory" varchar(100),
  "createddt" timestamp DEFAULT now(),
  PRIMARY KEY ("medicineid")
);
