-- Generated by dbmigration.
-- Table divadim.DateDimension -> livebit_divadim.datedimension
-- NOTE: column Day: tinyint widened to smallint
-- NOTE: column Weekday: tinyint widened to smallint
-- NOTE: column FiscalQuarter: tinyint widened to smallint
-- NOTE: column HalfYear: tinyint widened to smallint
-- NOTE: column WeekOfYear: tinyint widened to smallint
-- NOTE: column Month: tinyint widened to smallint
-- NOTE: column Quarter: tinyint widened to smallint

CREATE TABLE IF NOT EXISTS "livebit_divadim"."datedimension" (
  "datekey" integer NOT NULL,
  "date" date NOT NULL,
  "day" smallint NOT NULL,
  "daysuffix" char(2) NOT NULL,
  "weekday" smallint NOT NULL,
  "weekdayname" varchar(10) NOT NULL,
  "weekdayabbreviation" char(3) NOT NULL,
  "isweekend" boolean NOT NULL,
  "isholiday" boolean DEFAULT false NOT NULL,
  "holidaytext" varchar(64),
  "fiscalyear" integer NOT NULL,
  "fiscalquarter" smallint NOT NULL,
  "halfyear" smallint NOT NULL,
  "season" varchar(10) NOT NULL,
  "weekofyear" smallint NOT NULL,
  "month" smallint NOT NULL,
  "monthname" varchar(10) NOT NULL,
  "quarter" smallint NOT NULL,
  "year" integer NOT NULL,
  "firstdayofmonth" date NOT NULL,
  "lastdayofmonth" date NOT NULL,
  PRIMARY KEY ("datekey")
);
