-- Generated by dbmigration.
-- Table dbo.DMS_CompareCode -> livebit_dbo.dms_comparecode

CREATE TABLE IF NOT EXISTS "livebit_dbo"."dms_comparecode" (
  "comparecode" varchar(50),
  "codedescription" varchar(300),
  "easycode" varchar(5),
  "pbidesc" varchar(99),
  "codeid" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL
);
