-- Generated by dbmigration.
-- Table dbo.DMS_SQL_Patient -> livebit_dbo.dms_sql_patient

CREATE TABLE IF NOT EXISTS "livebit_dbo"."dms_sql_patient" (
  "patientid" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "firstname" varchar(50),
  "lastname" varchar(50),
  "dateofbirth" date,
  "gender" char(1),
  "phonenumber" varchar(20),
  "email" varchar(100),
  "address" varchar(200),
  "city" varchar(100),
  "state" varchar(100),
  "postalcode" varchar(20),
  "country" varchar(50),
  "emergencycontact" varchar(100),
  "emergencyphone" varchar(20),
  "insuranceprovider" varchar(100),
  "insurancenumber" varchar(50),
  "allergies" varchar(50),
  "medicalhistory" varchar(50),
  "patientname" varchar(100)
);
