-- Generated by dbmigration.
-- Table dbo.DivaTempDistinctCounts -> livebit_dbo.divatempdistinctcounts

CREATE TABLE IF NOT EXISTS "livebit_dbo"."divatempdistinctcounts" (
  "distinctvaluecount" bigint,
  "schemaname" varchar(128),
  "tablename" varchar(128),
  "columnname" varchar(128),
  "maxlengthorvalue" text,
  "minlengthorvalue" text,
  "qualitycheckallnullvoidonemany" varchar(50),
  "qualitycheckallnullvoidonevalue" text
);
