-- Generated by dbmigration.
-- Table dbo.sysdiagrams -> livebit_dbo.sysdiagrams
-- NOTE: column definition: binary length not preserved (bytea is variable length)

CREATE TABLE IF NOT EXISTS "livebit_dbo"."sysdiagrams" (
  "name" varchar(128) NOT NULL,
  "principal_id" integer NOT NULL,
  "diagram_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "version" integer,
  "definition" bytea,
  PRIMARY KEY ("diagram_id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "sysdiagrams_uk_principal_name" ON "livebit_dbo"."sysdiagrams" ("principal_id", "name");
