-- Generated by dbmigration.
-- Table dbo.Approval -> livebit_dbo.approval

CREATE TABLE IF NOT EXISTS "livebit_dbo"."approval" (
  "approvalid" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "companyid" integer,
  "userid" integer,
  "surveyproductid" integer,
  "surveyid" integer,
  "roleid" integer,
  "consultantid" integer,
  "isapproved" boolean NOT NULL,
  "approvedtilldate" timestamp NOT NULL,
  "approvaltype" varchar(100)
);
