-- Generated by dbmigration.
-- Table divaconfig.StoredProcedures -> livebit_divaconfig.storedprocedures

CREATE TABLE IF NOT EXISTS "livebit_divaconfig"."storedprocedures" (
  "procedureid" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "procedurename" varchar(255) NOT NULL,
  "proceduredescription" varchar(500),
  "proceduredefinition" text,
  "procedurecreatedby" varchar(100),
  "procedurecreateddate" timestamp DEFAULT now(),
  "procedureismanualonly" boolean,
  "procedureisingestiononly" boolean,
  "procedurecategory1" varchar(100),
  "procedurecategory2" varchar(100),
  "procedurecategory3" varchar(100),
  "procedurecategory4" varchar(100),
  "procedurecategory5" varchar(100),
  "type2active" boolean DEFAULT true NOT NULL,
  "type2startdate" timestamp DEFAULT now(),
  "type2enddate" timestamp,
  PRIMARY KEY ("procedureid")
);
