-- Generated by dbmigration.
-- Table divaconfig.TableList -> livebit_divaconfig.tablelist

CREATE TABLE IF NOT EXISTS "livebit_divaconfig"."tablelist" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "fulltablename" varchar(256) NOT NULL,
  PRIMARY KEY ("id")
);
