-- Generated by dbmigration.
-- Table dbo.FactEval -> livebit_dbo.facteval
-- NOTE: foreign key FK_FactSurveyResponses_DimSurvey1 was untrusted/disabled at the source; created NOT VALID (enforced for new rows only)

CREATE TABLE IF NOT EXISTS "livebit_dbo"."facteval" (
  "evalid" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "surveyid" integer NOT NULL,
  "questionid" integer NOT NULL,
  "responseid" integer NOT NULL,
  "userid" integer NOT NULL,
  "questionstartdisplaydatatime" timestamp NOT NULL,
  "questionresponcesubmiteddatetime" timestamp NOT NULL,
  "recordresponcetype" varchar(50) NOT NULL,
  "backendrecorddatatime" timestamp NOT NULL,
  "trackerid" integer NOT NULL,
  "comment" text,
  PRIMARY KEY ("surveyid", "questionid", "responseid", "userid")
);
