-- Generated by dbmigration.
-- Table zora.company -> livebit_zora.company

CREATE TABLE IF NOT EXISTS "livebit_zora"."company" (
  "company_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "company_name" varchar(255) NOT NULL,
  "company_primary_domain" varchar(255) NOT NULL,
  "company_custom_domain_allowed" boolean NOT NULL,
  "company_plan_id" varchar(50),
  "company_plan_expiry" timestamp,
  "company_type" varchar(50),
  "company_industry" varchar(100),
  "company_headquarters" varchar(100),
  "company_founded_year" integer,
  "company_revenue" numeric(15,2),
  "company_number_of_employees" integer,
  "company_market_segment" varchar(100),
  "company_parent_company_id" bigint,
  "company_global_presence" text,
  "company_website_url" varchar(255),
  "company_contact_info" text,
  "company_description" text,
  "company_is_consulting_company" boolean,
  "consulting_company_id" bigint,
  "is_superadmin_defined" boolean DEFAULT false NOT NULL,
  "is_consulting_defined" boolean DEFAULT false NOT NULL,
  "created_at" timestamp DEFAULT (now() at time zone 'utc'),
  "updated_at" timestamp DEFAULT (now() at time zone 'utc'),
  PRIMARY KEY ("company_id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "company_uq__company__6d1b87cb53c8a863" ON "livebit_zora"."company" ("company_name");
CREATE UNIQUE INDEX IF NOT EXISTS "company_uq__company__f884c4b5975da603" ON "livebit_zora"."company" ("company_primary_domain");
