-- Generated by dbmigration.
-- Table divaconfig.ColumnValue -> livebit_divaconfig.columnvalue

CREATE TABLE IF NOT EXISTS "livebit_divaconfig"."columnvalue" (
  "columnvalueid" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "databasename" varchar(255) NOT NULL,
  "schemaname" varchar(255) NOT NULL,
  "tablename" varchar(255) NOT NULL,
  "columnname" varchar(255) NOT NULL,
  "value" text,
  "valuecount" text,
  "displaytext" text,
  "description" text,
  "isactive" boolean DEFAULT true NOT NULL,
  "sortorder" integer,
  "createdat" timestamp DEFAULT now() NOT NULL,
  "updatedat" timestamp DEFAULT now() NOT NULL,
  "isdeleted" boolean DEFAULT false,
  PRIMARY KEY ("columnvalueid")
);
