-- Generated by dbmigration.
-- Table dbo.IndustryTypeSample -> livebit_dbo.industrytypesample

CREATE TABLE IF NOT EXISTS "livebit_dbo"."industrytypesample" (
  "industrytypeid" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "industrytypename" varchar(255) NOT NULL,
  "industrytypeshortname" varchar(50),
  "industrytypedescription" varchar(255),
  "industrytypecategory" varchar(255)
);
