-- Generated by dbmigration.
-- Table Sandbox.CloudOMax -> livebit_sandbox.cloudomax

CREATE TABLE IF NOT EXISTS "livebit_sandbox"."cloudomax" (
  "id" integer,
  "name" varchar(50),
  "created_at" timestamp
);
