-- Generated by dbmigration.
-- Table dbo.BuildSurvey_bkp -> livebit_dbo.buildsurvey_bkp

CREATE TABLE IF NOT EXISTS "livebit_dbo"."buildsurvey_bkp" (
  "buildsurveyid" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "surveyproductname" varchar(255),
  "surveyproductcategory" varchar(255),
  "additionalcontext" varchar(255),
  "surveyname" varchar(255),
  "questionnum" integer,
  "surveyproductid" integer,
  "status" varchar(50),
  "createddate" timestamp,
  "createdby" varchar(255),
  "updateddate" timestamp,
  "updatedby" varchar(255)
);
