-- Generated by dbmigration.
-- Table zora.click -> livebit_zora.click

CREATE TABLE IF NOT EXISTS "livebit_zora"."click" (
  "click_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "url_id" bigint NOT NULL,
  "link_id" bigint NOT NULL,
  "clicked_at" timestamp DEFAULT (now() at time zone 'utc'),
  "referrer" varchar(2000),
  "user_agent" varchar(512),
  "device_type" varchar(100),
  "operating_system" varchar(100),
  "browser_type" varchar(100),
  "ip" varchar(50),
  "geo_country" varchar(100),
  "geo_city" varchar(100),
  "is_qr_scan" boolean DEFAULT false NOT NULL,
  PRIMARY KEY ("click_id")
);
