-- Generated by dbmigration.
-- Table dbo.DMS_SharePoint_Medicine_Base -> livebit_dbo.dms_sharepoint_medicine_base

CREATE TABLE IF NOT EXISTS "livebit_dbo"."dms_sharepoint_medicine_base" (
  "medicineid" integer NOT NULL,
  "medicinename" varchar(100),
  "medicinecategory" varchar(100),
  "createddt" timestamp
);
