-- Generated by dbmigration.
-- Table aidd.quotas -> livebit_aidd.quotas
-- NOTE: column reset_at: datetimeoffset -> timestamptz: instant kept, original UTC offset not kept; fractional seconds rounded to microseconds
-- NOTE: column created_at: datetimeoffset -> timestamptz: instant kept, original UTC offset not kept; fractional seconds rounded to microseconds
-- NOTE: column updated_at: datetimeoffset -> timestamptz: instant kept, original UTC offset not kept; fractional seconds rounded to microseconds

CREATE TABLE IF NOT EXISTS "livebit_aidd"."quotas" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "period" varchar(7) NOT NULL,
  "token_limit" integer NOT NULL,
  "token_used" integer DEFAULT 0,
  "requests_limit" integer,
  "requests_used" integer DEFAULT 0,
  "reset_at" timestamptz NOT NULL,
  "tenant_id" uuid NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL,
  PRIMARY KEY ("id")
);
