-- Generated by dbmigration.
-- Table divaconfig.CompanyInfo -> livebit_divaconfig.companyinfo

CREATE TABLE IF NOT EXISTS "livebit_divaconfig"."companyinfo" (
  "companyid" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "companyname" varchar(200) NOT NULL,
  "contactperson" varchar(150),
  "contactemail" varchar(150),
  "contactphone" varchar(20),
  "logo" varchar(255),
  "primarythemecolor" varchar(7),
  "secondarythemecolor" varchar(7),
  "companyurl" varchar(255),
  "helpurl" varchar(255),
  "teamsurl" varchar(255),
  "sharepointurl" varchar(255),
  "customurl" varchar(255),
  "address" varchar(255),
  "country" varchar(100),
  "state" varchar(100),
  "city" varchar(100),
  "postalcode" varchar(20),
  "taxid" varchar(50),
  "industry" varchar(100),
  "subscriptionplan" varchar(50),
  "createdby" varchar(100) NOT NULL,
  "createddate" timestamp DEFAULT now(),
  "updatedby" varchar(100),
  "updateddate" timestamp,
  PRIMARY KEY ("companyid")
);
