-- Generated by dbmigration.
-- Table diva.Users -> livebit_diva.users

CREATE TABLE IF NOT EXISTS "livebit_diva"."users" (
  "userid" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "email" varchar(255) NOT NULL,
  "isverified" boolean DEFAULT false,
  "firstname" varchar(100),
  "lastname" varchar(100),
  "createddate" timestamp DEFAULT now(),
  "lastlogindate" timestamp,
  "isactive" boolean DEFAULT true,
  "profilepictureurl" text,
  "userroleid" integer,
  "dateofbirth" date,
  "phonenumber" varchar(15),
  "authprovider" varchar(50),
  "lastupdateddate" timestamp DEFAULT now(),
  "recenttoken" varchar(2048),
  "lastbrowserip" varchar(45),
  "refreshtoken" varchar(2048),
  "isemailverified" boolean,
  "emailverifieddate" timestamp,
  "consentgiven" boolean DEFAULT false,
  "usertimezone" varchar(50),
  "b2cobjectid" varchar(100),
  "externalprovidername" varchar(50),
  "externalproviderid" varchar(100),
  "identityprovider" varchar(50),
  "identityprovideruserid" varchar(100),
  PRIMARY KEY ("userid")
);
CREATE UNIQUE INDEX IF NOT EXISTS "users_uq__users__a9d10534688cb65b" ON "livebit_diva"."users" ("email");
