-- Generated by dbmigration.
-- Table divaconfig.UserRoles -> livebit_divaconfig.userroles

CREATE TABLE IF NOT EXISTS "livebit_divaconfig"."userroles" (
  "userroleid" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "userid" integer NOT NULL,
  "roleid" integer NOT NULL,
  "assigneddate" timestamp DEFAULT now() NOT NULL,
  "isactive" boolean DEFAULT true NOT NULL,
  PRIMARY KEY ("userroleid")
);
