-- Generated by dbmigration.
-- Table divadim.DimMasterTable -> livebit_divadim.dimmastertable

CREATE TABLE IF NOT EXISTS "livebit_divadim"."dimmastertable" (
  "dimmasterkey" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "dimtablename" varchar(255) NOT NULL,
  "dimtabledescription" text,
  "dimtablestoredprocedure" varchar(255),
  "dimtableisfullypopulated" boolean DEFAULT false NOT NULL,
  "dimtablegranularity" varchar(255),
  "dimtableprimarykeycolumn" varchar(255) NOT NULL,
  "dimtablelastupdated" timestamp DEFAULT now(),
  "dimtablecreateddate" timestamp DEFAULT now()
);
