-- Generated by dbmigration.
-- Table divaconfig.CardDisplayPerSubtab -> livebit_divaconfig.carddisplaypersubtab

CREATE TABLE IF NOT EXISTS "livebit_divaconfig"."carddisplaypersubtab" (
  "carddisplayid" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "subtabid" integer NOT NULL,
  "chartdisplayname" varchar(255) NOT NULL,
  "chartdisplayvalue" varchar(255) NOT NULL,
  "chartdisplayvalueprefix" varchar(50),
  "chartdisplayvaluesuffix" varchar(50),
  "chartdisplaydescription" varchar(500)
);
