-- Generated by dbmigration.
-- Table divaconfig.SubTabTable -> livebit_divaconfig.subtabtable

CREATE TABLE IF NOT EXISTS "livebit_divaconfig"."subtabtable" (
  "subtabid" integer,
  "parenttabid" integer,
  "tabtablename" varchar(300)
);
