-- Generated by dbmigration.
-- Table dbo.chat_context_config -> livebit_dbo.chat_context_config

CREATE TABLE IF NOT EXISTS "livebit_dbo"."chat_context_config" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "table_name" varchar(100) NOT NULL,
  "enable_for_chat" boolean DEFAULT true NOT NULL,
  "category" varchar(100),
  "description" varchar(255),
  PRIMARY KEY ("id")
);
