-- Generated by dbmigration.
-- Table aidd.user_plan_subscriptions -> livebit_aidd.user_plan_subscriptions
-- NOTE: column starts_at: datetimeoffset -> timestamptz: instant kept, original UTC offset not kept; fractional seconds rounded to microseconds
-- NOTE: column renews_at: datetimeoffset -> timestamptz: instant kept, original UTC offset not kept; fractional seconds rounded to microseconds
-- NOTE: column created_at: datetimeoffset -> timestamptz: instant kept, original UTC offset not kept; fractional seconds rounded to microseconds
-- NOTE: column updated_at: datetimeoffset -> timestamptz: instant kept, original UTC offset not kept; fractional seconds rounded to microseconds

CREATE TABLE IF NOT EXISTS "livebit_aidd"."user_plan_subscriptions" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "starts_at" timestamptz NOT NULL,
  "renews_at" timestamptz,
  "status" varchar(50) DEFAULT 'active',
  "meta" text DEFAULT '{}',
  "tenant_id" uuid NOT NULL,
  "plan_id" uuid NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL,
  PRIMARY KEY ("id")
);
