-- Generated by dbmigration.
-- Table zora.link -> livebit_zora.link
-- NOTE: column link_hash: binary length not preserved (bytea is variable length)

CREATE TABLE IF NOT EXISTS "livebit_zora"."link" (
  "link_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "original_url" varchar(2000) NOT NULL,
  "link_hash" bytea,
  "title" varchar(255),
  "description" text,
  "url_type" varchar(50),
  "language_code" varchar(10),
  "access_count" bigint DEFAULT 0 NOT NULL,
  "last_accessed_at" timestamp,
  "created_at" timestamp DEFAULT (now() at time zone 'utc'),
  PRIMARY KEY ("link_id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "link_uq_link_hash" ON "livebit_zora"."link" ("link_hash");
