-- Generated by dbmigration.
-- Table divaconfig.DatabaseConfig -> livebit_divaconfig.databaseconfig

CREATE TABLE IF NOT EXISTS "livebit_divaconfig"."databaseconfig" (
  "databaseid" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "databasename" varchar(255) NOT NULL,
  "databasetype" varchar(100) NOT NULL,
  "databaseusedfor" varchar(255) NOT NULL,
  "databaseowner" varchar(255),
  "collationname" varchar(255),
  "compatibilitylevel" integer,
  "recoverymodel" varchar(50),
  "keyname" varchar(255),
  "lastsyncmetadatadatetime" timestamp,
  "statedesc" varchar(100),
  "createdat" timestamp DEFAULT now(),
  "updatedat" timestamp DEFAULT now(),
  PRIMARY KEY ("databaseid")
);
