-- Generated by dbmigration.
-- Table divaconfig.Roles -> livebit_divaconfig.roles

CREATE TABLE IF NOT EXISTS "livebit_divaconfig"."roles" (
  "roleid" integer NOT NULL,
  "rolename" varchar(255) NOT NULL,
  "description" varchar(255),
  PRIMARY KEY ("roleid")
);
