-- Generated by dbmigration.
-- Table dbo.DMS_SAP_Medicine -> livebit_dbo.dms_sap_medicine

CREATE TABLE IF NOT EXISTS "livebit_dbo"."dms_sap_medicine" (
  "medicineid" integer NOT NULL,
  "medicinename" varchar(100),
  "medicinecategory" varchar(100),
  "createddt" timestamp DEFAULT now(),
  PRIMARY KEY ("medicineid")
);
