-- Generated by dbmigration.
-- Table dbo.Question -> livebit_dbo.question
-- NOTE: foreign key FK_DimQuestion_DimSurvey was untrusted/disabled at the source; created NOT VALID (enforced for new rows only)

CREATE TABLE IF NOT EXISTS "livebit_dbo"."question" (
  "questionid" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "questionsurveyid" integer,
  "questiontext" text,
  "questionshorttext" varchar(255),
  "questiongrouptext" varchar(255),
  "questionshortabbrev" varchar(50),
  "questionsort" integer,
  "questionismultimark" boolean,
  "questionisscale" boolean,
  "questionistopbox" boolean,
  "questionisskipquestion" boolean,
  "questionskiptoquestionid" integer,
  "questiongroup1text" varchar(100),
  "questiongroup2text" varchar(100),
  "questiongroup3text" varchar(100),
  "questiongroup4text" varchar(100),
  "questiongroup5text" varchar(100),
  "questionchoiceaigenrated" varchar(900),
  "questionscale" integer,
  "iscomment" boolean DEFAULT false,
  "commenttext" varchar(200) DEFAULT 'Do you want describe in details :',
  PRIMARY KEY ("questionid")
);
