-- Generated by dbmigration.
-- Table divaconfig.StoredProcedureAccess -> livebit_divaconfig.storedprocedureaccess

CREATE TABLE IF NOT EXISTS "livebit_divaconfig"."storedprocedureaccess" (
  "accessid" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "procedureid" integer,
  "userid" integer,
  "hasexecuteaccess" boolean DEFAULT false,
  "type2active" boolean DEFAULT true NOT NULL,
  "type2startdate" timestamp DEFAULT now(),
  "type2enddate" timestamp
);
