-- Generated by dbmigration.
-- Table dbo.SampleEmployees -> livebit_dbo.sampleemployees

CREATE TABLE IF NOT EXISTS "livebit_dbo"."sampleemployees" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "employeesname" varchar(100),
  "joiningdate" date,
  "position" varchar(50),
  "salary" numeric(10,2),
  PRIMARY KEY ("id")
);
