-- Generated by dbmigration.
-- Table divadim.DimMasterColumn -> livebit_divadim.dimmastercolumn

CREATE TABLE IF NOT EXISTS "livebit_divadim"."dimmastercolumn" (
  "dimmastercolumnkey" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "dimmasterkey" integer NOT NULL,
  "columnname" varchar(100) NOT NULL,
  "columndescription" varchar(500),
  "columndatatype" varchar(50),
  "isnullable" boolean,
  "isprimarykey" boolean,
  "columnorder" integer,
  "columncreateddate" timestamp DEFAULT now(),
  "columnlastupdated" timestamp DEFAULT now(),
  PRIMARY KEY ("dimmastercolumnkey")
);
