-- Generated by dbmigration.
-- Table dbo.ExecutionLog -> livebit_dbo.executionlog

CREATE TABLE IF NOT EXISTS "livebit_dbo"."executionlog" (
  "logid" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "executionguid" text,
  "procedurename" varchar(255) NOT NULL,
  "starttime" timestamp NOT NULL,
  "endtime" timestamp,
  "parameterdetails" text,
  "status" text,
  "errormessage" text,
  "openaistepname" varchar(255),
  "openaiparameterdetails" text,
  "openaiprompt" text,
  "additionalloggingdetails" text,
  "surveyid" text,
  "surveyproductid" text,
  "step3_query" text,
  "step3_q_output" text,
  "step4_query" text,
  "step4_resp_output" text,
  PRIMARY KEY ("logid")
);
