-- Generated by dbmigration.
-- Table dbo.SurveyBk12132024 -> livebit_dbo.surveybk12132024

CREATE TABLE IF NOT EXISTS "livebit_dbo"."surveybk12132024" (
  "surveyid" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "surveyproductid" integer,
  "surveycategory" varchar(100),
  "surveyname" varchar(500),
  "surveydesc" text,
  "surveylastupdated" timestamp,
  "surveystartdate" timestamp,
  "surveyenddate" timestamp,
  "surveysalesyeardate" timestamp,
  "surveynextresetrunningwindowindays" integer,
  "surveyislockedforseason" boolean,
  "surveygroup1" varchar(100),
  "surveygroup2" varchar(100),
  "surveygroup3" varchar(100),
  "surveygenratedbyai" boolean,
  "surveyaiverifiedbyhuman" boolean,
  "surveyapprovedbyuserid" integer,
  "surveyrequestbyuserid" integer,
  "surveylogofileurl" varchar(500)
);
