-- Generated by dbmigration.
-- Table divaconfig.LogCustomeSp -> livebit_divaconfig.logcustomesp
-- NOTE: column TransactionStartDateTime: fractional seconds rounded to microseconds
-- NOTE: column TransactionEndDateTime: fractional seconds rounded to microseconds

CREATE TABLE IF NOT EXISTS "livebit_divaconfig"."logcustomesp" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "storedprocedureexecutionid" uuid NOT NULL,
  "batchid" bigint,
  "storedprocedurename" text NOT NULL,
  "storedprocedureparameterall" text,
  "loginname" varchar(128),
  "clientid" varchar(128),
  "appname" varchar(128),
  "transactionstartdatetime" timestamp NOT NULL,
  "transactionenddatetime" timestamp,
  "transactiontype" char(10) NOT NULL,
  "spid" smallint,
  "errormessage" text,
  "executiontime" integer,
  "cputime" bigint,
  "elapsedtime" bigint,
  "logicalreads" bigint,
  "physicalreads" bigint,
  "logicalwrites" bigint,
  "executioncount" integer,
  "maxgrantkb" bigint,
  "maxusedgrantkb" bigint,
  "sessionid" varchar(50),
  "loginnamesession" varchar(128),
  "programname" varchar(128),
  "azurecorrelationid" varchar(100),
  "client_net_address" varchar(128),
  "executioncontext" text,
  "executionsqcontext" integer,
  "executionpipelinecontext" varchar(200),
  "errorseverity" integer,
  "errorline" integer
);
CREATE INDEX IF NOT EXISTS "logcustomesp_ix_logcustomesp_transactionstartdatetime" ON "livebit_divaconfig"."logcustomesp" ("transactionstartdatetime");
