-- Generated by dbmigration.
-- Table zora.domain -> livebit_zora.domain

CREATE TABLE IF NOT EXISTS "livebit_zora"."domain" (
  "domain_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "company_id" bigint,
  "user_id" bigint,
  "domain_name" varchar(255) NOT NULL,
  "is_domain_verified" boolean DEFAULT false NOT NULL,
  "is_domain_primary" boolean DEFAULT false NOT NULL,
  "domain_verification_token" varchar(255),
  "created_at" timestamp DEFAULT (now() at time zone 'utc'),
  "updated_at" timestamp DEFAULT (now() at time zone 'utc'),
  PRIMARY KEY ("domain_id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "domain_uq__domain__f01cdb5ee8fdfb8a" ON "livebit_zora"."domain" ("domain_name");
