-- Generated by dbmigration.
-- Table dbo.DMS_FactAttributeStatsBRIM -> livebit_dbo.dms_factattributestatsbrim

CREATE TABLE IF NOT EXISTS "livebit_dbo"."dms_factattributestatsbrim" (
  "configid" integer,
  "fields" varchar(600),
  "syncdatatype" varchar(100),
  "configcategory" varchar(400),
  "generalcolumnname" varchar(100),
  "configidcount" integer,
  "totoalattributevalue" integer,
  "attributevaluematched" integer,
  "attributevaluenotmatched" integer,
  "percentagematched" double precision,
  "percentagenotmatched" double precision,
  "lastrundatetime" timestamp
);
