-- Generated by dbmigration.
-- Table dbo.SurveyGroup -> livebit_dbo.surveygroup

CREATE TABLE IF NOT EXISTS "livebit_dbo"."surveygroup" (
  "surveyproductid" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "surveyproductcategory" varchar(100),
  "surveyproductname" varchar(100) NOT NULL,
  "surveyproductdesc" text,
  "surveyproductsort" integer,
  "surveyproductisopen" boolean,
  "numberofq" integer,
  PRIMARY KEY ("surveyproductid")
);
