-- Generated by dbmigration.
-- Table dbo.UserIndustry -> livebit_dbo.userindustry

CREATE TABLE IF NOT EXISTS "livebit_dbo"."userindustry" (
  "userindustryid" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "userindustryuserid" integer NOT NULL,
  "userindustrytypeid" integer NOT NULL,
  PRIMARY KEY ("userindustryid")
);
