-- Generated by dbmigration.
-- Table dbo.SurveyGroupBK12132024 -> livebit_dbo.surveygroupbk12132024

CREATE TABLE IF NOT EXISTS "livebit_dbo"."surveygroupbk12132024" (
  "surveyproductid" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "surveyproductcategory" varchar(100),
  "surveyproductname" varchar(100) NOT NULL,
  "surveyproductdesc" text,
  "surveyproductsort" integer,
  "surveyproductisopen" boolean,
  "numberofq" integer
);
