-- Generated by dbmigration.
-- Table aidd.verification_codes -> livebit_aidd.verification_codes
-- NOTE: column expires_at: fractional seconds rounded to microseconds
-- NOTE: column created_at: fractional seconds rounded to microseconds
-- NOTE: column updated_at: fractional seconds rounded to microseconds

CREATE TABLE IF NOT EXISTS "livebit_aidd"."verification_codes" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "email" varchar(255) NOT NULL,
  "code" varchar(6) NOT NULL,
  "expires_at" timestamp NOT NULL,
  "used" boolean DEFAULT false NOT NULL,
  "created_at" timestamp DEFAULT now(),
  "updated_at" timestamp DEFAULT now(),
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "verification_codes_idx_verification_codes_email_code" ON "livebit_aidd"."verification_codes" ("email", "code");
CREATE INDEX IF NOT EXISTS "verification_codes_idx_verification_codes_email_used" ON "livebit_aidd"."verification_codes" ("email", "used");
CREATE INDEX IF NOT EXISTS "verification_codes_idx_verification_codes_expires_at" ON "livebit_aidd"."verification_codes" ("expires_at");
