-- Generated by dbmigration.
-- Table divaconfig.ProcedureTabMapping -> livebit_divaconfig.proceduretabmapping

CREATE TABLE IF NOT EXISTS "livebit_divaconfig"."proceduretabmapping" (
  "mappingid" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "procedureid" integer NOT NULL,
  "subtabid" integer NOT NULL,
  "proceduretabmappingdescription" varchar(500),
  "proceduretabmappingcreateddate" timestamp DEFAULT now(),
  "type2active" boolean DEFAULT true NOT NULL,
  "type2startdate" timestamp DEFAULT now(),
  "type2enddate" timestamp
);
