-- Generated by dbmigration.
-- Table dbo.Roles -> livebit_dbo.roles

CREATE TABLE IF NOT EXISTS "livebit_dbo"."roles" (
  "roleid" integer NOT NULL,
  "rolename" varchar(255) NOT NULL,
  "description" varchar(255),
  PRIMARY KEY ("roleid")
);
