-- Generated by dbmigration.
-- Table dbo.Survey -> livebit_dbo.survey
-- NOTE: foreign key FK_DimSurvey_DimSurveyProduct was untrusted/disabled at the source; created NOT VALID (enforced for new rows only)

CREATE TABLE IF NOT EXISTS "livebit_dbo"."survey" (
  "surveyid" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "surveyproductid" integer,
  "surveycategory" varchar(100),
  "surveyname" varchar(500),
  "surveydesc" text,
  "surveylastupdated" timestamp,
  "surveystartdate" timestamp,
  "surveyenddate" timestamp,
  "surveysalesyeardate" timestamp,
  "surveynextresetrunningwindowindays" integer,
  "surveyislockedforseason" boolean,
  "surveygroup1" varchar(100),
  "surveygroup2" varchar(100),
  "surveygroup3" varchar(100),
  "surveygenratedbyai" boolean,
  "surveyaiverifiedbyhuman" boolean,
  "surveyapprovedbyuserid" integer,
  "surveyrequestbyuserid" integer,
  "surveylogofileurl" varchar(500),
  PRIMARY KEY ("surveyid")
);
