-- Generated by dbmigration.
-- Table divaconfig.PortalTabsConfig -> livebit_divaconfig.portaltabsconfig

CREATE TABLE IF NOT EXISTS "livebit_divaconfig"."portaltabsconfig" (
  "tabid" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "basetabname" varchar(100) NOT NULL,
  "tabname" varchar(100) NOT NULL,
  "iseditable" boolean DEFAULT true,
  "isvisible" boolean DEFAULT true,
  "logo" varchar(255),
  "primarythemecolor" varchar(7),
  "secondarythemecolor" varchar(7),
  "createdby" varchar(100) NOT NULL,
  "createddate" timestamp DEFAULT now(),
  "updatedby" varchar(100),
  "updateddate" timestamp,
  "tabsq" integer,
  PRIMARY KEY ("tabid")
);
