-- Generated by dbmigration.
-- Table divaconfig.TableInfo -> livebit_divaconfig.tableinfo

CREATE TABLE IF NOT EXISTS "livebit_divaconfig"."tableinfo" (
  "tableid" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "tabledatabasename" varchar(255) NOT NULL,
  "tableschemaname" varchar(255) NOT NULL,
  "tablename" varchar(255) NOT NULL,
  "tabledescription" text,
  "tablerowcount" bigint,
  "tablecolumncount" integer,
  "tableidentitycolumnname" varchar(255),
  "tableprimarycolumncsv" text,
  "tableuniquecolumncsv" text,
  "istableeditable" boolean DEFAULT false,
  "isdeleted" boolean DEFAULT false,
  "tablemetadatasyncdatetime" timestamp,
  "createdat" timestamp DEFAULT now(),
  "updatedat" timestamp DEFAULT now(),
  PRIMARY KEY ("tableid")
);
