-- Generated by dbmigration.
-- Table aidd.messages -> livebit_aidd.messages
-- NOTE: column created_at: datetimeoffset -> timestamptz: instant kept, original UTC offset not kept; fractional seconds rounded to microseconds
-- NOTE: column updated_at: datetimeoffset -> timestamptz: instant kept, original UTC offset not kept; fractional seconds rounded to microseconds

CREATE TABLE IF NOT EXISTS "livebit_aidd"."messages" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "role" varchar(50) NOT NULL,
  "content" text,
  "content_full" text,
  "sequence" bigint NOT NULL,
  "tokens_prompt" integer,
  "tokens_completion" integer,
  "tenant_id" uuid NOT NULL,
  "conversation_id" uuid NOT NULL,
  "user_id" uuid,
  "model_id" uuid,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL,
  "is_interrupted" boolean DEFAULT false NOT NULL,
  "metadata" text,
  "message_type" varchar(50),
  PRIMARY KEY ("id")
);
