-- Generated by dbmigration.
-- Table dbo.DivaTempInsertValues -> livebit_dbo.divatempinsertvalues

CREATE TABLE IF NOT EXISTS "livebit_dbo"."divatempinsertvalues" (
  "sourcetable" varchar(256),
  "columnname" varchar(128),
  "parsedvalue" text,
  "datatype" varchar(50),
  "sortorder" integer
);
