-- Generated by dbmigration.
-- Table aidd.plans -> livebit_aidd.plans
-- NOTE: column created_at: datetimeoffset -> timestamptz: instant kept, original UTC offset not kept; fractional seconds rounded to microseconds
-- NOTE: column updated_at: datetimeoffset -> timestamptz: instant kept, original UTC offset not kept; fractional seconds rounded to microseconds

CREATE TABLE IF NOT EXISTS "livebit_aidd"."plans" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "plan_name" varchar(255) NOT NULL,
  "description" text,
  "is_free_plan" boolean DEFAULT false,
  "max_short_links" integer,
  "max_redirects" integer,
  "max_custom_aliases" integer,
  "max_bulk_shorten" integer,
  "max_qr_codes" integer,
  "max_campaigns" integer,
  "max_dashboard_count" integer,
  "data_retention_days" integer,
  "api_limit_per_month" integer,
  "custom_domain_allowed" boolean DEFAULT false,
  "features" text DEFAULT '{}',
  "monthly_token_quota" integer,
  "rate_card" text DEFAULT '{}',
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL,
  PRIMARY KEY ("id")
);
