-- Generated by dbmigration.
-- Table divaconfig.SubTabsConfig -> livebit_divaconfig.subtabsconfig

CREATE TABLE IF NOT EXISTS "livebit_divaconfig"."subtabsconfig" (
  "subtabid" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "parenttabid" integer NOT NULL,
  "basetabname" varchar(100) NOT NULL,
  "subtabname" varchar(100) NOT NULL,
  "subtabsq" integer,
  "iseditable" boolean DEFAULT true,
  "isvisible" boolean DEFAULT true,
  "logo" varchar(255),
  "primarythemecolor" varchar(20),
  "secondarythemecolor" varchar(20),
  "createdby" varchar(50) NOT NULL,
  "createddate" timestamp DEFAULT now(),
  "updatedby" varchar(50),
  "updateddate" timestamp,
  "isdirect" boolean,
  "tabtablename" varchar(200),
  "isappadmin" boolean DEFAULT false NOT NULL,
  "isadmin" boolean DEFAULT false NOT NULL,
  "isuser" boolean DEFAULT false NOT NULL,
  "iscontributor" boolean DEFAULT false NOT NULL,
  PRIMARY KEY ("subtabid")
);
