-- Generated by dbmigration.
-- Table dbo.DMS_FactFunctionaStats -> livebit_dbo.dms_factfunctionastats

CREATE TABLE IF NOT EXISTS "livebit_dbo"."dms_factfunctionastats" (
  "syncdatatype" varchar(100),
  "configidcount" integer,
  "totoalattributevalue" integer,
  "attributevaluematched" integer,
  "attributevaluenotmatched" integer,
  "percentagematched" double precision,
  "percentagenotmatched" double precision
);
