-- Generated by dbmigration.
-- Table dbo.Company -> livebit_dbo.company

CREATE TABLE IF NOT EXISTS "livebit_dbo"."company" (
  "companyid" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "companyname" varchar(100) NOT NULL,
  "companytype" varchar(50),
  "companyindustry" varchar(100),
  "companyheadquarters" varchar(100),
  "companyfoundedyear" integer,
  "companyrevenue" numeric(15,2),
  "companynumberofemployees" integer,
  "companymarketsegment" varchar(100),
  "companyparentcompanyid" integer,
  "companyglobalpresence" text,
  "companywebsiteurl" varchar(255),
  "companycontactinfo" text,
  "companydescription" text,
  "companyisconsultingcompany" boolean,
  "consultingcompanyid" integer,
  PRIMARY KEY ("companyid")
);
