-- Generated by dbmigration.
-- Table dbo.DivaTempInsert -> livebit_dbo.divatempinsert

CREATE TABLE IF NOT EXISTS "livebit_dbo"."divatempinsert" (
  "sourcetable" varchar(256),
  "columnname" varchar(255) NOT NULL,
  "columnsort" integer NOT NULL,
  "customcastforcrud" varchar(255),
  "isnullable" boolean NOT NULL,
  "isidentity" boolean NOT NULL,
  "datatype" varchar(100) NOT NULL
);
