-- Generated by dbmigration.
-- Table zora.shortUrl -> livebit_zora.shorturl

CREATE TABLE IF NOT EXISTS "livebit_zora"."shorturl" (
  "url_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "company_id" bigint,
  "user_id" bigint NOT NULL,
  "domain_id" bigint,
  "link_id" bigint NOT NULL,
  "alias" varchar(50) NOT NULL,
  "expires_at" timestamp,
  "password_hash" varchar(512),
  "category_suggestions" varchar(500),
  "fraud_detection" varchar(500),
  "suggested_aliases" varchar(500),
  "tags" varchar(500),
  "is_bookmark" boolean,
  "bookmark_title" varchar(200),
  "bookmark_description" varchar(2000),
  "created_at" timestamp DEFAULT (now() at time zone 'utc') NOT NULL,
  "updated_at" timestamp,
  PRIMARY KEY ("url_id")
);
