-- Generated by dbmigration.
-- Table dbo.Table1 -> livebit_dbo.table1

CREATE TABLE IF NOT EXISTS "livebit_dbo"."table1" (
  "tableid" double precision,
  "tablename" varchar(255),
  "tablerowcount" double precision,
  "tablecolumncount" double precision,
  "primarykeycsv" varchar(255),
  "tableuniquecolumncsv" varchar(255),
  "table_semantic_name" varchar(255),
  "table_summary_description" varchar(255),
  "table_sensitivity_level" varchar(255),
  "table_sample_questions_min_5_and_max_10" text,
  "table_llm_gpt_keywords_synonyms" varchar(255),
  "table_related_tables_csv_seprated" text,
  "table_usage_notes" text,
  "review_by" varchar(255),
  "ischanged" varchar(255),
  "change_comment__vp_1223_why_changed" varchar(255)
);
