-- Generated by dbmigration.
-- Table Sandbox.ClouOMax -> livebit_sandbox.clouomax

CREATE TABLE IF NOT EXISTS "livebit_sandbox"."clouomax" (
  "id" integer,
  "name" varchar(50),
  "created_at" timestamp
);
