-- Generated by dbmigration.
-- Table aidd.conversations -> livebit_aidd.conversations
-- NOTE: column archived_at: datetimeoffset -> timestamptz: instant kept, original UTC offset not kept; fractional seconds rounded to microseconds
-- NOTE: column created_at: datetimeoffset -> timestamptz: instant kept, original UTC offset not kept; fractional seconds rounded to microseconds
-- NOTE: column updated_at: datetimeoffset -> timestamptz: instant kept, original UTC offset not kept; fractional seconds rounded to microseconds

CREATE TABLE IF NOT EXISTS "livebit_aidd"."conversations" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "title" varchar(500),
  "mode" varchar(50) DEFAULT 'single_model',
  "metadata" text DEFAULT '{}',
  "archived_at" timestamptz,
  "tenant_id" uuid NOT NULL,
  "user_id" uuid,
  "current_model_id" uuid,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL,
  PRIMARY KEY ("id")
);
