-- Generated by dbmigration.
-- Table zora.plans -> livebit_zora.plans

CREATE TABLE IF NOT EXISTS "livebit_zora"."plans" (
  "plan_id" varchar(50) NOT NULL,
  "plan_name" varchar(100) NOT NULL,
  "description" varchar(255),
  "is_free_plan" boolean DEFAULT false NOT NULL,
  "created_at" timestamp DEFAULT (now() at time zone 'utc') NOT NULL,
  "last_updated_at" timestamp DEFAULT (now() at time zone 'utc') NOT NULL,
  "max_short_links" integer DEFAULT 100 NOT NULL,
  "max_redirects" integer DEFAULT 5 NOT NULL,
  "max_custom_aliases" integer DEFAULT 100 NOT NULL,
  "max_bulk_shorten" integer DEFAULT 0 NOT NULL,
  "max_qr_codes" integer DEFAULT 5 NOT NULL,
  "max_campaigns" integer DEFAULT 0 NOT NULL,
  "max_dashboard_count" integer DEFAULT 10 NOT NULL,
  "data_retention_days" integer DEFAULT 30 NOT NULL,
  "api_limit_per_month" integer DEFAULT 5000 NOT NULL,
  "custom_domain_allowed" boolean DEFAULT false NOT NULL,
  PRIMARY KEY ("plan_id")
);
