-- Generated by dbmigration.
-- Table dbo.IndustryType -> livebit_dbo.industrytype

CREATE TABLE IF NOT EXISTS "livebit_dbo"."industrytype" (
  "industrytypeid" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "industrytypename" varchar(255) NOT NULL,
  "industrytypeshortname" varchar(50),
  "industrytypedescription" text,
  "industrytypecategory" varchar(255),
  PRIMARY KEY ("industrytypeid")
);
