-- Generated by dbmigration.
-- Table dbo.Response_bkp -> livebit_dbo.response_bkp

CREATE TABLE IF NOT EXISTS "livebit_dbo"."response_bkp" (
  "responseid" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "responsequestionid" integer,
  "responsetext" text,
  "responseweightage" integer,
  "responsesort" integer,
  "responseisdefaultchoice" boolean,
  "responseiscompulsorychoice" boolean,
  "responseistopboxchoice" boolean,
  "responseisbottomboxchoice" boolean,
  "responseisaveragechoice" boolean,
  "responseisskipchoice" boolean,
  "responsegroup1" varchar(100),
  "responsegroup2" varchar(100),
  "responsegroup3" varchar(100),
  "responsegroup4" varchar(100),
  "responsegroup5" varchar(100),
  "responcedescriptiontoachivethislarge" varchar(900),
  "responcedescriptiontoachivethisshort" varchar(900),
  "responceaveragedaystoachive" integer
);
