-- Generated by dbmigration.
-- Table dbo.Orders -> livebit_dbo.orders

CREATE TABLE IF NOT EXISTS "livebit_dbo"."orders" (
  "orderid" bigint,
  "orderdate" timestamp,
  "customerid" integer,
  "totalamount" numeric(18,2),
  "status" varchar(255)
);
