-- Generated by dbmigration.
-- Table aidd.llm_models -> livebit_aidd.llm_models
-- NOTE: column created_at: datetimeoffset -> timestamptz: instant kept, original UTC offset not kept; fractional seconds rounded to microseconds
-- NOTE: column updated_at: datetimeoffset -> timestamptz: instant kept, original UTC offset not kept; fractional seconds rounded to microseconds

CREATE TABLE IF NOT EXISTS "livebit_aidd"."llm_models" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "name" varchar(255) NOT NULL,
  "capabilities" text DEFAULT '{}',
  "pricing" text DEFAULT '{"input_per_1k": 0.02, "output_per_1k": 0.06}',
  "max_tokens" integer,
  "status" varchar(50) DEFAULT 'active',
  "provider_id" uuid NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL,
  "api_key" varchar(255),
  "api_version" varchar(50),
  "api_endpoint" varchar(500),
  "temperature" double precision,
  "top_p" double precision,
  "model" varchar(255),
  "display_order" integer,
  PRIMARY KEY ("id")
);
