-- Generated by dbmigration.
-- Table dbo.Tracker -> livebit_dbo.tracker

CREATE TABLE IF NOT EXISTS "livebit_dbo"."tracker" (
  "trackerid" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "userid" integer NOT NULL,
  "surveyid" integer,
  "lastanswerquestionid" integer,
  "iscompleted" boolean,
  "completiondate" timestamp,
  "lastupdateddate" timestamp NOT NULL
);
