-- Generated by dbmigration.
-- Table dbo.kevinaccount2 -> livebit_dbo.kevinaccount2

CREATE TABLE IF NOT EXISTS "livebit_dbo"."kevinaccount2" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(255)
);
