-- Generated by dbmigration.
-- Table divaconfig.DynamicCRUDExecutionLog -> livebit_divaconfig.dynamiccrudexecutionlog
-- NOTE: column CRUDProcedureExecutionStart: fractional seconds rounded to microseconds

CREATE TABLE IF NOT EXISTS "livebit_divaconfig"."dynamiccrudexecutionlog" (
  "logid" uuid DEFAULT gen_random_uuid() NOT NULL,
  "crudschematable" varchar(255) NOT NULL,
  "crudoperationtype" varchar(50) NOT NULL,
  "crudparametersused" text,
  "cruddebug" text,
  "crudprocedureexecutionstart" timestamp DEFAULT now(),
  "crudexecutionstatus" varchar(50) NOT NULL,
  "cruderrormessage" text,
  PRIMARY KEY ("logid")
);
