-- Generated by dbmigration.
-- Table aidd.llm_responses -> livebit_aidd.llm_responses
-- NOTE: column created_at: datetimeoffset -> timestamptz: instant kept, original UTC offset not kept; fractional seconds rounded to microseconds
-- NOTE: column updated_at: datetimeoffset -> timestamptz: instant kept, original UTC offset not kept; fractional seconds rounded to microseconds

CREATE TABLE IF NOT EXISTS "livebit_aidd"."llm_responses" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "status" varchar(50) NOT NULL,
  "completion_excerpt" varchar(1000),
  "raw" text,
  "tokens_prompt" integer,
  "tokens_completion" integer,
  "cost_usd" numeric(10,6),
  "latency_ms" integer,
  "request_id" uuid NOT NULL,
  "model_id" uuid,
  "assistant_message_id" uuid,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL,
  PRIMARY KEY ("id")
);
