-- Generated by dbmigration.
-- Table divaconfig.StoredProcSubTabOperation -> livebit_divaconfig.storedprocsubtaboperation

CREATE TABLE IF NOT EXISTS "livebit_divaconfig"."storedprocsubtaboperation" (
  "spstid" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "procedureid" integer NOT NULL,
  "subtabid" integer NOT NULL,
  "createddate" timestamp DEFAULT now(),
  "modifieddate" timestamp,
  "status" varchar(50) DEFAULT 'Active',
  "defaultparameterlist" varchar(700),
  "spstidsq" integer,
  "spstidesc" varchar(700)
);
