-- Generated by dbmigration.
-- Table dbo.DMS_ConfigIDBusinessPartnerPercetage -> livebit_dbo.dms_configidbusinesspartnerpercetage

CREATE TABLE IF NOT EXISTS "livebit_dbo"."dms_configidbusinesspartnerpercetage" (
  "configid" integer,
  "totalbp" integer,
  "matchedbp" integer NOT NULL,
  "percetagematchedbp" double precision NOT NULL,
  "notmatchedbp" integer NOT NULL,
  "percetagenotmatchedbp" double precision NOT NULL
);
