-- Generated by dbmigration.
-- Table dbo.DMS_SAP_MedicinePurchaseType -> livebit_dbo.dms_sap_medicinepurchasetype

CREATE TABLE IF NOT EXISTS "livebit_dbo"."dms_sap_medicinepurchasetype" (
  "purchaseid" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "patientid" integer,
  "medicinename" varchar(100),
  "purchasetype" varchar(50),
  "purchasedate" date,
  "quantity" integer,
  "price" numeric(10,2),
  "paymentmethod" varchar(50),
  "insurancecovered" varchar(5)
);
