Create View vwUser
as
SELECT  [UserID]
      ,[UserFirstName]
      ,[UserLastName]
      ,[UserEmail]
      ,[UserPhoneNumber]
      ,[UserAge]
      ,[UserGender]
      ,[UserEducationLevel]
      ,[UserOccupation]
      ,[UserIncomeRange]
      ,[UserCountry]
      ,[UserState]
      ,[UserCity]
      ,[UserLinkedInProfileLink]
      ,[UserFacebookProfileLink]
      ,[UserInstagramProfileLink]
      ,[UserTwitterProfileLink]
      ,[UserCurrentCompanyLink]
      ,[UserPastCompaniesLink]
      ,[UserCompanyID]
      ,[AuthId]
      ,[UserCommunicationEmail]
      ,[UserPhone]
      ,[UserStreet1]
      ,[UserStreet2]
      ,[UserZip]
      ,[UserJobTitle]
      ,[UserCompanyEmail]
      ,[UserCompanyName]
      ,[UserJobIndustry]
      ,[UserProfessionalExpertise]
      ,[UserProfessionalSkills]
      ,[UserCommunityInvolvement]
      ,[UserUniversityAttended]
      ,[UserGraduationYear]
      ,[UserLeadershipProgramGraduatedFrom]
      ,[UserIsToBeRegistered]
      ,[UserIsAlumni]
      ,[UserIsInCurrentClass]
      ,[UserIsChamberMember]
      ,[UserLeadershipBatchYear]
      ,[UserInterestedInLeadershipTopics]
      ,[UserSeekingMentor]
      ,[UserWillingToBeMentor]
      ,[UserMentorshipInvolvementList]
      ,[UserWillingToBeGuestSpeaker]
      ,[UserGuestSpeakerTopicPreference]
      ,[UserIsActive]
      ,[UserMemberSinceDate]
      ,[UserLastUpdated]
,[CompanyName], [CompanyType], [CompanyIndustry], [CompanyHeadquarters], [CompanyFoundedYear], [CompanyRevenue], [CompanyNumberOfEmployees], [CompanyMarketSegment], [CompanyParentCompanyID], [CompanyGlobalPresence], [CompanyWebsiteURL], [CompanyContactInfo], [CompanyDescription], [CompanyIsConsultingCompany], [ConsultingCompanyID]
  FROM [dbo].[User] u 
  left join [dbo].[Company]  c on u.[UserCompanyID]=c.[CompanyID]