-- Generated by dbmigration.
-- Target schemas for LiveBit. Run first.

CREATE SCHEMA IF NOT EXISTS "livebit_aidd";
CREATE SCHEMA IF NOT EXISTS "livebit_dbo";
CREATE SCHEMA IF NOT EXISTS "livebit_diva";
CREATE SCHEMA IF NOT EXISTS "livebit_divaconfig";
CREATE SCHEMA IF NOT EXISTS "livebit_divadim";
CREATE SCHEMA IF NOT EXISTS "livebit_sandbox";
CREATE SCHEMA IF NOT EXISTS "livebit_zora";
