-- Generated by dbmigration.
-- Foreign keys: run after all data is loaded.
-- One statement per line.

ALTER TABLE "livebit_dbo"."facteval" ADD CONSTRAINT "facteval_fk_factsurveyresponses_dimsurvey1" FOREIGN KEY ("surveyid") REFERENCES "livebit_dbo"."survey" ("surveyid") ON DELETE NO ACTION ON UPDATE NO ACTION NOT VALID;
ALTER TABLE "livebit_dbo"."facteval" ADD CONSTRAINT "facteval_fk_factsurveyresponses_dimresponse1" FOREIGN KEY ("responseid") REFERENCES "livebit_dbo"."response" ("responseid") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "livebit_dbo"."facteval" ADD CONSTRAINT "facteval_fk_factsurveyresponses_dimuser1" FOREIGN KEY ("userid") REFERENCES "livebit_dbo"."user" ("userid") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "livebit_dbo"."question" ADD CONSTRAINT "question_fk_dimquestion_dimsurvey" FOREIGN KEY ("questionsurveyid") REFERENCES "livebit_dbo"."survey" ("surveyid") ON DELETE NO ACTION ON UPDATE NO ACTION NOT VALID;
ALTER TABLE "livebit_dbo"."response" ADD CONSTRAINT "response_fk_dimresponse_dimquestion" FOREIGN KEY ("responsequestionid") REFERENCES "livebit_dbo"."question" ("questionid") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "livebit_dbo"."survey" ADD CONSTRAINT "survey_fk_dimsurvey_dimsurveyproduct" FOREIGN KEY ("surveyproductid") REFERENCES "livebit_dbo"."surveygroup" ("surveyproductid") ON DELETE NO ACTION ON UPDATE NO ACTION NOT VALID;
ALTER TABLE "livebit_dbo"."user" ADD CONSTRAINT "user_fk_dimuser_dimcompany" FOREIGN KEY ("usercompanyid") REFERENCES "livebit_dbo"."company" ("companyid") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "livebit_dbo"."userindustry" ADD CONSTRAINT "userindustry_fk_userindustry_user" FOREIGN KEY ("userindustryuserid") REFERENCES "livebit_dbo"."user" ("userid") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "livebit_dbo"."userindustry" ADD CONSTRAINT "userindustry_fk_userindustry_industrytype" FOREIGN KEY ("userindustrytypeid") REFERENCES "livebit_dbo"."industrytype" ("industrytypeid") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "livebit_divaconfig"."userroles" ADD CONSTRAINT "userroles_fk__userroles__useri__6f8b439a" FOREIGN KEY ("userid") REFERENCES "livebit_diva"."users" ("userid") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "livebit_divaconfig"."userroles" ADD CONSTRAINT "userroles_fk__userroles__rolei__707f67d3" FOREIGN KEY ("roleid") REFERENCES "livebit_divaconfig"."roles" ("roleid") ON DELETE NO ACTION ON UPDATE NO ACTION;
